### ISSUE TITLE
Unified API: binding target is garbage collected

### ISSUE THREAD

**Issue by alxbog** [MvvmCross/MvvmCross#902] opened 2015-02-02 15:44 UTC
Here is a sample ViewModel:

```
public class FirstViewModel : MvxViewModel
{
    public async void Init()
    {
        while (true)
        {
            await Task.Delay(2000);
            Hidden = !Hidden;
        }
    }

    private bool _hidden;

    public bool Hidden
    {
        get { return _hidden; }
        set
        {
            _hidden = value;
            RaisePropertyChanged(() => Hidden);
        }
    }
}
```

And corresponding View:

```
public class FirstView : MvxViewController
{
    public override void ViewDidLoad()
    {
        base.ViewDidLoad();

        var testView = new UIView(View.Bounds) { BackgroundColor = UIColor.Red };
        Add(testView);

        var set = this.CreateBindingSet<FirstView, FirstViewModel>();
        set.Bind(testView).For(v => v.Hidden).To(vm => vm.Hidden);
        set.Apply();
    }

    public override void ViewDidAppear(bool animated)
    {
        base.ViewDidAppear(animated);
        GC.Collect();
    }
}
```

The problem here is that Hidden binding doesn't work. Each time Hidden property of ViewModel is set the MVVMCross emits this error:

> Weak Target is null in MvxUIViewHiddenTargetBinding - skipping set

This behaviour appears in Unified API projects because of using [new reference counting](http://developer.xamarin.com/guides/ios/advanced_topics/newrefcount/) of Xamarin.iOS. You can read more details on why _testView_ gets garbage collected in [this question](http://stackoverflow.com/questions/28263138/migrating-to-unified-api-and-new-reference-counting) on SO.

I suppose MVVMCross uses weak references for serving bindings.

Anyway, can this problem be solved in a right way on the side of MVVMCross?

**Comment by alxbog** [comment] 2015-02-02 16:12
Another example of binding (without creating any new objects) which doesn't work now:
```
set.Bind(NavigationItem).For(ni => ni.Title).To(vm => vm.SomeTextProperty);
```

The workaround is to always store binding targets to View's private fields. But it really seems strange to store NavigationItem as a private field.

**Comment by alxbog** [comment] 2015-02-02 16:17
By the way, this behaviour is not reproduced when binding a button (target) to ViewModel commands.

**Comment by slodge** [comment] 2015-02-02 16:46
That's not the behaviour I was seeing when I was testing - mostly in December - but maybe Xam have changed their algorithms...

If they have - and if their new algorithms still don't resolve the issues of circular references when contained objects reference their containers - then `private fields` sounds like the way forwards - off the top of my head, I'm not sure what else I can suggest... but that's only an initial reaction...

**Comment by nitescua** [comment] 2015-02-02 16:57
@alxbog the reason why it's not reproduced on a button (target) could it because the button is an outlet (a private field in the designer generated class) ?

**Comment by alxbog** [comment] 2015-02-02 17:14
@slodge I guess the new refcount system resolves issues with circular references, but one of its side effects is that **managed** instances derived from NSObject doesn't store references to its **managed** children as they did before. As an illustration, here is a decompiled code from UIViewController.View implementation:
```
public virtual UIView View
{
    [Export("view", ArgumentSemantic.Retain)] get
    {
    UIApplication.EnsureUIThread();
    UIView uiView = !this.IsDirectBinding ? Runtime.GetNSObject<UIView>(Messaging.IntPtr_objc_msgSendSuper(this.SuperHandle, Selector.GetHandle("view"))) : Runtime.GetNSObject<UIView>(Messaging.IntPtr_objc_msgSend(this.Handle, Selector.GetHandle("view")));
    if (!NSObject.IsNewRefcountEnabled())
        this.__mt_View_var = (object) uiView;
    return uiView;
    }
    [Export("setView:", ArgumentSemantic.Retain)] set
    {
    UIApplication.EnsureUIThread();
    if (this.IsDirectBinding)
        Messaging.void_objc_msgSend_IntPtr(this.Handle, Selector.GetHandle("setView:"), value != null ? value.Handle : IntPtr.Zero);
    else
        Messaging.void_objc_msgSendSuper_IntPtr(this.SuperHandle, Selector.GetHandle("setView:"), value != null ? value.Handle : IntPtr.Zero);
    if (NSObject.IsNewRefcountEnabled())
        return;
    this.__mt_View_var = (object) value;
    }
}
```
See NSObject.IsNewRefcountEnabled() check.

@nitescua No, I'm not using the designer. I guess in case of buttons MVVMCross adds events to buttons when applying bindings. So Xamarin keeps the managed instance to pass events back from native to managed instances.

**Comment by nitescua** [comment] 2015-02-02 17:25
does this require changes in the MvvmCross data-binding engine from using weak reference to strong reference?

**Comment by slodge** [comment] 2015-02-02 17:31
if you use strong references then binding to any singleton (or long-living) view model objects will cause iOS UIKit objects to hang around too long.

**Comment by nitescua** [comment] 2015-02-02 17:38
you're right, but usually we do not bind to a singleton?
we bind to view-models which have same lifetime as the view.

with strong referencing, if you would need to bind to singleton you would be aware of that and clear binding yourself (not sure if there is any way to clear binding).

or maybe, have a fluent way to specify that the binding should be strong or weak.
have it use the strong referencing by default and only use weak referencing by request, something like:
<code>
set.Bind(NavigationItem).For(ni => ni.Title).To(vm => vm.SomeTextProperty).Weak();
</code>
 
or maybe there's another better way

**Comment by slodge** [comment] 2015-02-02 17:46
> you're right, but usually we do not bind to a singleton?

I've seen it reported a lot (but would need to search around for "long living view model" topics...)

One common scenario I remember is: where some singleton/service is shared between multiple viewmodels and exposed by those viewmodels as a public property - with the views then binding to sub-properties on that service...

For now, still need to see what's happening/changing within GC on the xamarin side - "stable" is relative :)

**Comment by alxbog** [comment] 2015-02-02 17:46
Another approach could be:
```
set.Bind(NavigationItem).For(ni => ni.Title).To(vm => vm.SomeTextProperty).LifetimeAsView();
```
This explicitly tells the binding system to use strong reference with the same lifetime as a containing view.

**Comment by alxbog** [comment] 2015-02-02 18:18
Just as a reference, I'm describing the current GC behaviour I see (with new refcount enabled).

There are two types of managed objects. I took the definition from Xamarin's article:
* **Peer objects** - they're merely wrappers around native objects.
* **Derived objects** - they extend or incorporate new functionality.

For example:
* UIButton managed instance is **peer object**.
* CustomButton managed instance is **derived object**, provided CustomButton is a subclass of UIButton.
* UIButton managed instance with added event handler is **derived object**.

If a **peer object** don't have any managed references, it gets garbage collected even if the native object is still alive. The reasoning here is that it can always be restored if needed from the native object.

A **derived object** otherwise is not garbage collected while the native object is alive.

Furthermore, current Xamarin implementation doesn't store references between managed objects in most cases. For example, UIViewController managed instance doesn't store its view as a backing field. And even a UIView instance doesn't store its subviews as a backing field.

**Comment by alxbog** [comment] 2015-02-02 18:38
It looks like calling MarkDirty() method on binding targets (when they're NSObjects) could solve the problem. This method promotes peer objects to derived objects. But this method is protected and is a part of internal implementation.

Here is it:
```
/// <summary>
/// Promotes a regular peer object (IsDirectBinding is true) into a toggleref object.
/// </summary>
/// 
/// <remarks>
/// This turns a regular peer object (one that has
/// 	  IsDirectBinding set to true) into a toggleref object.  This
/// 	  is necessary when you are storing to a backing field whose
/// 	  objc_c semantics is not copy or retain.  This is an internal
/// 	  method.
/// 
/// </remarks>
protected void MarkDirty()
{
    if (!NSObject.use_new_refcounting || this.registered_toggleref || Class.IsCustomType(this.GetType()))
    return;
    this.registered_toggleref = true;
    NSObject.RegisterToggleRef(this);
}
```

**Comment by nitescua** [comment] 2015-02-02 18:40
Not sure but for the moment isn't the best solution to just disable the new GC behavior from the project settings?

**Comment by nitescua** [comment] 2015-02-02 18:54
I see `WeakReference` is used in `MvxTargetBinding`. Replacing it to 'object' will make some bindings start working.
There are several other places and ways which weak referencing is used. Commands for example.
It take some time to understand how everything works.

I see there is already a way to clear bindings for a specific target: https://github.com/MvvmCross/MvvmCross/blob/3.5/Cirrious/Cirrious.MvvmCross.Binding/BindingContext/MvxBindingContextOwnerExtensions.Clear.cs
So for people who bind to singletons they need to call clear bindings on those views which are bound to the singleton instances.

**Comment by slodge** [comment] 2015-02-03 09:44
Good digging :+1: @alxbog 

If this is a long-term issue (and not a stable-blip), I'd vote that any solution should be iOS (and maybe Mac) specific - there's no point in adding strong references to Droid just to solve something that feels odd (and maybe even "buggy") in the iOS GC.

Of course, that's assuming Xam don't switch across to doing similar lifetime tricks in Droid too :)

Be good to know if this is effecting other people - and which versions people are seeing it in..

The easiest workaround (in the short term) is to make the binding `set` a member variable of the view?

**Comment by JohnCashman** [comment] 2015-02-03 12:44
Seeming this issue in VS using the simulator and Xamarin.iOS 8.6.0.0

**Comment by nitescua** [comment] 2015-02-03 15:29
I just created a Unified app and the option "Use the reference counting extension" is not checked in any configuration.
According to http://developer.xamarin.com/guides/ios/advanced_topics/newrefcount/ it should be enabled by default.

**Comment by alxbog** [comment] 2015-02-03 15:34
@nitescua It's just a bug in presentation of project settings. You can use NSObject.IsNewRefcountEnabled() to get the actual setting value at runtime. For me it returns true in Unified API projects.

**Comment by nitescua** [comment] 2015-02-03 15:43
wow, but that means there's no way to disable it, isn't it?  :(

**Comment by nitescua** [comment] 2015-02-03 18:51
It's so weird my app works fine. I'd expected to see bindings stop working with the new ref counting.

**Comment by nitescua** [comment] 2015-02-04 13:57
I'm not able to reproduce the behavior in my app.
I'm testing in Release config on a device.

**Comment by slodge** [comment] 2015-02-05 20:46
Still confused on this one too..

Not clear whether this is consistently happen across Xam stable...

However, the good news is that I think this can be solved within Mvx relatively easily... and that it would be a solution that would add extra benefits **without** breaking the rule that the `ViewModel` should never have a strong reference back to the `View`

The fix, I think, is to adjust the MvxBindingContext so that it stores:

-  a `List<Tuple<object, IMvxUpdateableBinding>>` in place of `List<IMvxUpdateableBinding>` on
https://github.com/MvvmCross/MvvmCross/blob/3.5/Cirrious/Cirrious.MvvmCross.Binding/BindingContext/MvxBindingContext.cs#L21

- and similarly a `List<KeyValuePair<object, IList<Tuple<object,IMvxUpdateableBinding>>>>` on the next line (the first object in this generic monster is the `clearKey`, the second object is the `target` - the thing that we think is being GC'd in the new world)

This would then necessitate a breaking change of API for methods like `public virtual void `RegisterBinding(IMvxUpdateableBinding binding)` - they'd need to become `public virtual void RegisterBinding(object target, IMvxUpdateableBinding binding)` - but this probably wouldn't affect too many devs...

Something like:

```
public class MvxBindingContext
	: IMvxBindingContext
{
	private readonly List<Action> _delayedActions = new List<Action>();

	private readonly List<KeyValuePair<object,IMvxUpdateableBinding>> _directBindings = new List<KeyValuePair<object,IMvxUpdateableBinding>>();

	private readonly List<KeyValuePair<object, IList<KeyValuePair<object, IMvxUpdateableBinding>>>> _viewBindings =
		new List<KeyValuePair<object, IList<KeyValuePair<object,IMvxUpdateableBinding>>>>();

	private object _dataContext;

	public MvxBindingContext()
		: this((object) null)
	{
	}

	public MvxBindingContext(object dataContext)
	{
		_dataContext = dataContext;
	}

	public MvxBindingContext(IDictionary<object, string> firstBindings)
		: this(null, firstBindings)
	{
	}

	public MvxBindingContext(object dataContext, IDictionary<object, string> firstBindings)
	{
		foreach (var kvp in firstBindings)
		{
			_delayedActions.Add(() =>
				{
					var bindings = Binder.Bind(DataContext, kvp.Key, kvp.Value);
					foreach (var b in bindings)
						RegisterBinding(b);
				});
		}
		if (dataContext != null)
			DataContext = dataContext;
	}

	public MvxBindingContext(IDictionary<object, IEnumerable<MvxBindingDescription>> firstBindings)
		: this(null, firstBindings)
	{
	}

	public MvxBindingContext(object dataContext,
		IDictionary<object, IEnumerable<MvxBindingDescription>> firstBindings)
	{
		foreach (var kvp in firstBindings)
		{
			_delayedActions.Add(() =>
				{
					var bindings = Binder.Bind(DataContext, kvp.Key, kvp.Value);
					foreach (var b in bindings)
						RegisterBinding(kvp.Key, b);
				});
		}
		if (dataContext != null)
			DataContext = dataContext;
	}

	~MvxBindingContext()
	{
		Dispose(false);
	}

	public void Dispose()
	{
		Dispose(true);
		GC.SuppressFinalize(this);
	}

	protected virtual void Dispose(bool disposing)
	{
		if (disposing)
		{
			ClearAllBindings();
		}
	}

	private IMvxBinder _binder;

	protected IMvxBinder Binder
	{
		get
		{
			_binder = _binder ?? Mvx.Resolve<IMvxBinder>();
			return _binder;
		}
	}

	public object DataContext
	{
		get { return _dataContext; }
		set
		{
			_dataContext = value;
			OnDataContextChange();
			var handler = DataContextChanged;
			if (handler != null)
				handler(this, EventArgs.Empty);
		}
	}

	public event EventHandler DataContextChanged;

	protected virtual void OnDataContextChange()
	{
		// update existing bindings
		foreach (var binding in _viewBindings)
		{
			foreach (var bind in binding.Value)
			{
				bind.Value.DataContext = _dataContext;
			}
		}

		foreach (var binding in _directBindings)
		{
			binding.Value.DataContext = _dataContext;
		}

		// add new bindings
		if (_delayedActions.Count == 0)
		{
			return;
		}

		foreach (var action in _delayedActions)
		{
			action();
		}
		_delayedActions.Clear();
	}

	public virtual void DelayBind(Action action)
	{
		_delayedActions.Add(action);
	}

	public virtual void RegisterBinding(object target, IMvxUpdateableBinding binding)
	{
		_directBindings.Add(KeyValuePair.Create(target,binding));
	}

	public virtual void RegisterBindingsWithClearKey(object clearKey, IList<KeyValuePair<object,IMvxUpdateableBinding>> bindings)
	{
		if (clearKey == null)
			return;

		_viewBindings.Add(new KeyValuePair<object, IList<KeyValuePair<object, IMvxUpdateableBinding>>>(clearKey, bindings));
	}

	public virtual void RegisterBindingWithClearKey(object clearKey, object target, IMvxUpdateableBinding binding)
	{
		if (clearKey == null)
		{
			RegisterBinding(binding);   
		}

		var list = new List<KeyValuePair<object, IMvxUpdateableBinding>>() {KeyValuePair.Create(target, binding)};
		_viewBindings.Add(new KeyValuePair<object, IList<KeyValuePair<object, IMvxUpdateableBinding>>>(clearKey, list));
	}

	public virtual void ClearBindings(object clearKey)
	{
		if (clearKey == null)
			return;

		for (var i = _viewBindings.Count - 1; i >= 0; i--)
		{
			var candidate = _viewBindings[i];
			if (candidate.Key.Equals(clearKey))
			{
				foreach (var binding in candidate.Value)
				{
					binding.Value.Dispose();
				}
				_viewBindings.RemoveAt(i);
			}
		}
	}

	public virtual void ClearAllBindings()
	{
		ClearAllViewBindings();
		ClearAllDirectBindings();
		ClearAllDelayedBindings();
	}

	protected virtual void ClearAllDelayedBindings()
	{
		_delayedActions.Clear();
	}

	protected virtual void ClearAllDirectBindings()
	{
		foreach (var binding in _directBindings)
		{
			binding.Value.Dispose();
		}
		_directBindings.Clear();
	}

	protected virtual void ClearAllViewBindings()
	{
		foreach (var kvp in _viewBindings)
		{
			foreach (var binding in kvp.Value)
			{
				binding.Value.Dispose();
			}
		}
		_viewBindings.Clear();
	}
}
```

**Comment by slodge** [comment] 2015-02-05 20:55
@alxbog I can't explain your button observation right now... except maybe if the `Click` subscription in https://github.com/MvvmCross/MvvmCross/blob/1eeea41e110934e52bf7e6682d8751b885206844/Cirrious/Cirrious.MvvmCross.Binding.Droid/Target/MvxViewClickBinding.cs#L31 somehow promotes the object within xam's new GC...

**Comment by alxbog** [comment] 2015-02-06 07:50
@slodge That's exactly the case. See [new refcount article](http://developer.xamarin.com/guides/ios/advanced_topics/newrefcount/). Example illustrates the similar case there.

**Comment by slodge** [comment] 2015-02-22 19:19
Has 3.5.1-alpha1 helped with this?

Keen to push alpha2 soon - but interested in feedback first :)

**Comment by andreinitescu** [comment] 2015-06-20 08:53
I'm on v3.5.1 and bindings stopped working :(

**Comment by andreinitescu** [comment] 2015-06-20 09:00
funny this worked before v3.5.1

**Comment by andreinitescu** [comment] 2015-06-20 10:53
I use this:

`this.AddBindings (new Dictionary<object, string> () {
				{ this.txtUsername, "Text Username; Placeholder [UsernameText]; Visibility IsBusy, Converter=InvertedVisibility" },
				{ this.txtPassword, "Text Password; Placeholder [PasswordText]; Visibility IsBusy, Converter=InvertedVisibility" },`

**Comment by Laumania** [comment] 2015-07-09 09:11
Anything new on this one? Just upgraded one of my iOS apps to 64bit and Unified API and see this problem, my binding simply doesn't work/trigger.

In the comments here I don't see a solution. I'm on MvvmCross 3.5.1. 

I see @andreinitescu has a potential workaround, but I would like to use the more fluent api :)

**Comment by Cheesebaron** [comment] 2016-12-06 17:12
Is someone still experiencing this. I've never seen this issue in any of my apps.

**Closed** 2017-04-29 15:15 UTC
Labels: Needs investigation
