### ISSUE TITLE
New navigation service creates two instances of VM and initialize the wrong one

### ISSUE THREAD

**Issue by mgochmuradov** [MvvmCross/MvvmCross#1943] opened 2017-06-14 07:36 UTC
Link to sample github project: [MvxNavigationServiceIssue](https://github.com/mgochmuradov/MvxNavigationServiceIssue)

### Steps to reproduce

1. Create Core and UI (WPF) project add nuget package (MvvmCross.StarterPack) on both projects

2. Create [SecondViewModel](https://github.com/mgochmuradov/MvxNavigationServiceIssue/blob/master/MvxNewNavigation.Core/ViewModels/SecondViewModel.cs)
```cs
    public class SecondViewModel : MvxViewModel
    {
        private static int _times = 0;
        public SecondViewModel() // <- ViewModel is being constructed TWICE
        {
            _times++;
            Title = "From Constructor " + _times;
        }

        private string _title;
        public string Title
        {
            get { return _title; }
            set { SetProperty(ref _title, value); }
        }

        public override Task Initialize()
        {
            // Called on a different instance than the one that is bound to view
            Title = "From Initializer";
            return base.Initialize();
        }
    }
```

3. On [MainViewModel](https://github.com/mgochmuradov/MvxNavigationServiceIssue/blob/master/MvxNewNavigation.Core/ViewModels/MainViewModel.cs) inject IMvxNavigationService, and add command to navigate to SecondViewModel
```cs
    public class MainViewModel : MvxViewModel
    {
        private readonly IMvxNavigationService _navigationService;
        public MainViewModel(IMvxNavigationService navigationService)
        {
            _navigationService = navigationService;
        }
        
        public override Task Initialize() // <- Never being called
        {
            return base.Initialize();
        }

        public IMvxAsyncCommand GoToSecondCommand =>
            new MvxAsyncCommand(GoToSecondAsync);
        private async Task GoToSecondAsync()
        {
            await _navigationService.Navigate<SecondViewModel>();
        }
    }
```

### Expected behavior
Construct `SecondViewModel`, navigate to `SecondView`, and call `Initialize()` method on `SecondViewModel`

### Actual behavior
`SecondViewModel` is being constructed twice, and one of them is set as BindingContext on `SecondView`, and `Initialize()` method is being called on the other one.

### Configuration

**Version:** 5.0.2

**Platform:** 
- [ ] iOS
- [ ] Android
- [X] WPF
- [ ] UWP

**Comment by mgochmuradov** [comment] 2017-06-14 09:43
This are the places where VM is being constructed:
    * [In NavigationService](https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross/Core/Core/Navigation/MvxNavigationService.cs#L173) which is then being initialized in [line 318](https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross/Core/Core/Navigation/MvxNavigationService.cs#L318)
    * And [in ViewModelLocator](https://github.com/MvvmCross/MvvmCross/blob/f9f6e2643d2defc6ccc033f899a8ecf599441e67/MvvmCross/Core/Core/ViewModels/MvxDefaultViewModelLocator.cs#L33) which is called from [ViewsContainer](https://github.com/MvvmCross/MvvmCross/blob/f9f6e2643d2defc6ccc033f899a8ecf599441e67/MvvmCross/Windows/Wpf/Views/MvxWpfViewsContainer.cs#L41) and bound to view

**Comment by Bowman74** [comment] 2017-06-14 14:35
Suspect a duplicate of #1921.

**Comment by Cheesebaron** [comment] 2017-06-19 12:12
Please open a new issue linking to this one if the issue persists.

**Closed** 2017-06-19 12:11 UTC
Labels: Bug, WPF

**Comment by adyshimony** [comment] 2017-07-17 14:32
This is still happening in version 5.06 with Xamarin forms, in IOS and android.
