### ISSUE TITLE
Check lifetimeMonitor on all platforms - decide what to do!

### ISSUE THREAD

**Issue by slodge** [MvvmCross/MvvmCross#161] opened 2013-02-16 15:32 UTC
lifetimeMonitor is important - but not really supported perfectly right now

And is perfect possible on all these targets?

**Comment by martijn00** [comment] 2015-01-24 12:36
Not sure what this issue means. @slodge could you explain this one, or close it.

**Comment by slodge** [comment] 2015-01-26 08:00
This is about the interface `IMvxLifetime` - https://github.com/MvvmCross/MvvmCross/blob/3.5/Cirrious/Cirrious.MvvmCross/Platform/IMvxLifetime.cs

This interface (or its replacement) could be really useful to developers wanting to track (cross-platform) whether an app is foreground/background/hibernating/reinflating/whatever...

To do this properly would require someone first really clearly understanding that `whatever` across all the platforms... is it even possible to unify the different lifetimes across Droid and Windows?

**Comment by nickrandolph** [comment] 2018-06-06 04:52
@martijn00 is this still something we want to look at further?

**Comment by nickrandolph** [comment] 2018-06-07 22:33
No feedback, so closing this issue

**Closed by nickrandolph** 2018-06-07 22:33 UTC
Labels: Code improvement, Feature request

**Comment by nmilcoff** [comment] 2018-06-07 22:50
This is something we also need to clean up at some point... I honestly don't see how closing the issue because nobody's actively working on it helps?

**Comment by nickrandolph** [comment] 2018-06-07 22:54
The point is to force a response... Like you gave. If the issue is still relevant/important I would expect feedback as such. If no feedback the issue should be dropped. Otherwise it will never get actioned

As it is, we aren't closing issues faster than they're being raised. If this is something that should be done, let's put it into a future project so it makes it into the roadmap.

**Comment by nmilcoff** [comment] 2018-06-07 23:01
I see your point, and it's ok. But I disagree on the necessity of having to close issues faster than they are raised. 

I think having open issues like this one, for future cleanups, do not harm the project in any way. And they help us not forget the fact we still need to work on this.

**Comment by nickrandolph** [comment] 2018-06-07 23:11
yeh I agree with the comment about having "feature request" issue that can be added over time. But realistically each of these feature requests either need to be on the roadmap (as confirmed by core team) or they need a contributor to champion the issue so that it gets worked on. 

The issues I'm closing are those that are very old and haven't had any comments/work done on them for a long time.
