### ISSUE TITLE
when i try to install MvvmCross.Droid.Support.Fragment getting error

### ISSUE THREAD

**Issue by Tharan** [MvvmCross/MvvmCross#2016] opened 2017-07-05 15:22 UTC
To help us fix your issue, please provide the information in the below template. 

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.
>
> Please only file bugs verified on latest version of MvvmCross and _stable_ Xamarin tools

### Steps to reproduce

1.go to nugget package and search MvvmCross.Droid.Support.Fragment

2. Click to install the package

3.Get the following error message. Please see the attached screen shot

### Expected behavior
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'MvvmCross.Droid.Shared 5.0.5'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0	

### Actual behavior
Tell us what happens instead

### Configuration

**Version:** 5.x

**Platform:** 
- [ yes] iOS
- [yes ] Android
![mvvmcross error](https://user-images.githubusercontent.com/732053/27871645-44cd0fd4-6174-11e7-89e4-bfc5cd450714.PNG)

- [ ] WPF
- [ ] UWP

**Comment by Cheesebaron** [comment] 2017-07-05 15:35
Duplicate of #2013

**Closed by Cheesebaron** 2017-07-05 15:35 UTC
