### ISSUE TITLE
How to use prepopulated DB in sqlite plugin

### ISSUE THREAD

**Issue by vinodh06** [MvvmCross/MvvmCross#1281] opened 2016-04-05 12:09 UTC
To help us fix your issue, please provide the information in the below template. 

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.

### Steps to reproduce

1.Need to add prepopulated sqlite in mvvmcross xamarin project for ios and android.So please tell me how to use prepopulated date base using mvvmcross sqlite plugin
2.

3.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Configuration

**Version:** 4.0.0

**Platform:** iOS/Android/WPF/Windows Store/Windows Phone Store/Windows UWP

**Comment by Cheesebaron** [comment] 2016-04-05 14:54
As I've pointed out in the other two issues you have created. Please fill out the issue template or actually use the body of the issue description to describe what your problem is. Also please keep GitHub for issues only and not questions about usage. Questions should preferably go on StackOverflow.

I'll keep closing your issues as long as you don't provide any description.

Duplicate of #1280 and #1279

**Closed by Cheesebaron** 2016-04-05 14:54 UTC
Labels: Duplicate

**Comment by vinodh06** [comment] 2016-04-06 06:28
Thanks for your response.
