### ISSUE TITLE
MvxTabbedPage use once appear two bar 

### ISSUE THREAD

**Issue by xyz20533** [MvvmCross/MvvmCross#2501] opened 2018-01-02 07:26 UTC
### Steps to reproduce :scroll:

![1514877209 1](https://user-images.githubusercontent.com/32668078/34476864-861fc186-efcf-11e7-84ca-63bea40dd924.jpg)
MvxTabbedPage of MvvmCross issues that statement once appear two bar,how sovle this issues?

### Expected behavior :thinking:
<?xml version="1.0" encoding="utf-8" ?>
<mvx:MvxTabbedPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="testt.Core.Pages.MainPage"
             xmlns:res="clr-namespace:testt.Core.Resources;assembly=testt.Core"
             xmlns:mvx="clr-namespace:MvvmCross.Forms.Views;assembly=MvvmCross.Forms"
             BarBackgroundColor="Blue"
             Title="Main">
  
</mvx:MvxTabbedPage>
This is my code but appear tow bar on screen,android have same issues.

### Configuration :wrench:

**Version:** 5.6.3

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [o ] :monkey: Xamarin.Forms

**Comment by nickrandolph** [comment] 2018-01-02 07:44
Any chance you can repro this using the Playground sample and share a link to your repo

**Comment by nmilcoff** [comment] 2018-01-05 18:36
Closing this issue as duplicate of #2500. If you find out this is indeed MvvmCross related, please feel free to re-open it.

**Closed by nmilcoff** 2018-01-05 18:36 UTC
Labels: Duplicate, Forms
