### ISSUE TITLE
Proguard necessary naming conventions

### ISSUE THREAD

**Issue by Miiite** [MvvmCross/MvvmCross#1228] opened 2016-01-28 09:32 UTC
When proguard is enabled in the Android project, the following proguard options are automatically generated by Java and/or Xamarin in the proguard_project_primary.cfg:
-keepclasseswithmembers class MvvmCross.binding.droid.views.MvxAutoCompleteTextView { *; }
-keepclasseswithmembers class MvvmCross.binding.droid.views.MvxDatePicker { *; }
-keepclasseswithmembers class MvvmCross.binding.droid.views.MvxExpandableListView { *; }
-keepclasseswithmembers class MvvmCross.binding.droid.views.MvxFrameControl { *; }
-keepclasseswithmembers class MvvmCross.binding.droid.views.MvxFrameLayout { *; }
-keepclasseswithmembers class MvvmCross.binding.droid.views.MvxGridView { *; }
-keepclasseswithmembers class MvvmCross.binding.droid.views.MvxImageView { *; }
-keepclasseswithmembers class MvvmCross.binding.droid.views.MvxLinearLayout { *; }
-keepclasseswithmembers class MvvmCross.binding.droid.views.MvxListItemView { *; }
-keepclasseswithmembers class MvvmCross.binding.droid.views.MvxListView { *; }
-keepclasseswithmembers class MvvmCross.binding.droid.views.MvxRadioGroup { *; }
-keepclasseswithmembers class MvvmCross.binding.droid.views.MvxRelativeLayout { *; }
-keepclasseswithmembers class MvvmCross.binding.droid.views.MvxSpinner { *; }
-keepclasseswithmembers class MvvmCross.binding.droid.views.MvxTableLayout { *; }
-keepclasseswithmembers class MvvmCross.binding.droid.views.MvxTimePicker { *; }

The package name "MvvmCross.binding.droid.views." is automatically generated based on directory structure.

The problem seems to be, that each of these views, are registered as their equivalent in lowercase, meaning that "MvvmCross.binding.droid.views.MvxSpinner" is actually registered as "mvvmcross.binding.droid.views.MvxSpinner "

So when proguard runs, the output (for this MvxSpinner example) is as follows :
"Warning: class [MvvmCross/binding/droid/views/MvxSpinner.class] unexpectedly contains class [mvvmcross.binding.droid.views.MvxSpinner]"

And when proguard output this kind of message, it actually ignores completely the class (ref: http://proguard.sourceforge.net/manual/troubleshooting.html#unexpectedclass).
So at runtime, the application will crash when trying to inflate an MvxSpinner object, because it simply does not exist in the installed java file.

The easy fix seems to rename, either the "MvvmCross" directory to "mvvmcross" for these views, or to change the Register attributes to "MvvmCross.binding.droid ..."

**Comment by tiftof** [comment] 2016-02-10 14:34
I'm looking into this as well.

This is indeed a problem because of the name space not matching with the directory structure. However, I don't understand why the MvvmCross directory is the only one in the path not in lower case.

For example:
MvxRadioGroup
* C# namespace: MvvmCross.Binding.Droid.Views
* registered as "mvvmcross.binding.droid.views.MvxRadioGroup"

Why is it then that only the root folder "MvvmCross" is not lower case?

**Comment by Cheesebaron** [comment] 2016-02-10 14:37
Root folder? I don't see a path here?

**Comment by tiftof** [comment] 2016-02-10 14:39
root folder of the class path in this warning:

"Warning: class [MvvmCross/binding/droid/views/MvxSpinner.class] unexpectedly contains class [mvvmcross.binding.droid.views.MvxSpinner]"

**Comment by Miiite** [comment] 2016-02-10 15:30
Yes that root folder in uppercase is very disturbing indeed ...

**Comment by tiftof** [comment] 2016-02-11 09:12
I think I know where the casing of the MvvmCross root folder is coming from.

I've also included the MvvmCross.Droid.Support.V7.AppCompat package in my solution. These views seem to be registered using CamelCase namespace instead of lowercase.
https://github.com/MvvmCross/MvvmCross-AndroidSupport/blob/master/MvvmCross.Droid.Support.V7.AppCompat/Widget/MvxAppCompatListView.cs#L22

These 2 packages of widgets get collected in the same root folder in the proguard input jar (makes sense). But as casing doesn't match, one of the two will run into problems when using proguard.

![screen shot 2016-02-11 at 10 10 46](https://cloud.githubusercontent.com/assets/3620157/12972748/f109170c-d0a7-11e5-9381-7aa12d1a5641.png)

**Comment by Cheesebaron** [comment] 2016-02-11 09:27
I've gone ahead and fixed the AndroidSupport stuff so that they are all registered lower case.

**Comment by tiftof** [comment] 2016-02-11 09:34
Now that is fast :) Thanks!

Is there a way to get Nuget packages for the head of the master?

I'll try proguard again here by including the MvvmCross Android projects directly

**Comment by Miiite** [comment] 2016-02-11 09:34
That is awesome news !
Thanks @Cheesebaron :)

**Comment by Miiite** [comment] 2016-02-11 09:36
And thanks @tiftof for digging deeper into this as weel :+1:

**Comment by Cheesebaron** [comment] 2016-02-11 09:43
Come over on [Slack](https://xamarinchat.herokuapp.com/) and receive :taco:'s for your efforts

**Comment by Cheesebaron** [comment] 2016-02-11 10:04
NuGet's being pushed now. 

Maybe some of you can make a sample project with ProGuard enabled just to show people how to use it. Or maybe a blog post or something like that?

**Comment by tiftof** [comment] 2016-02-11 10:14
I'm taking my first steps here with ProGuard. I'll report back on my findings once I've got a working project :)

**Comment by Miiite** [comment] 2016-02-11 10:16
A blog post would be much more usefull imo. 
This issue can be used as a test case to explain how proguard really works, and what problems you can encounter with (specially when using a library).
I'll try to start one later this week

**Comment by martijn00** [comment] 2016-02-18 10:13
I'll close this as the issue is fixed. A blog post would still be appreciated!

**Closed by martijn00** 2016-02-18 10:13 UTC

**Comment by Miiite** [comment] 2016-02-23 18:44
I finally took the time to write a short blog post about this.
It can be found here http://mitert.blogspot.fr/2016/02/xamarinandroid-naming-conventions.html .

I'm not a great writer, so any remarks / advice on this will be appreciated ;)

**Comment by Miiite** [comment] 2016-03-08 09:02
I finally took the time to test it in my project, but the issue does not look fixed. I still have this output by proguard :


Warning: class [MvvmCross/Droid/Support/V7/AppCompat/MvxCachingFragmentCompatActivity.class] unexpectedly contains class [mvvmcross.droid.support.v7.appcompat.MvxCachingFragmentCompatActivity]
Warning: class [MvvmCross/Droid/Support/V7/AppCompat/widget/MvxAppCompatAutoCompleteTextView.class] unexpectedly contains class [mvvmcross.droid.support.v7.appcompat.widget.MvxAppCompatAutoCompleteTextView]
Warning: class [MvvmCross/Droid/Support/V7/AppCompat/widget/MvxAppCompatImageView.class] unexpectedly contains class [mvvmcross.droid.support.v7.appcompat.widget.MvxAppCompatImageView]
Warning: class [MvvmCross/Droid/Support/V7/AppCompat/widget/MvxAppCompatListView.class] unexpectedly contains class [mvvmcross.droid.support.v7.appcompat.widget.MvxAppCompatListView]
Warning: class [MvvmCross/Droid/Support/V7/AppCompat/widget/MvxAppCompatRadioGroup.class] unexpectedly contains class [mvvmcross.droid.support.v7.appcompat.widget.MvxAppCompatRadioGroup]
Warning: class [MvvmCross/Droid/Support/V7/AppCompat/widget/MvxAppCompatSpinner.class] unexpectedly contains class [mvvmcross.droid.support.v7.appcompat.widget.MvxAppCompatSpinner]
Warning: class [MvvmCross/Droid/Support/V7/recyclerview/MvxRecyclerView.class] unexpectedly contains class [mvvmcross.droid.support.v7.recyclerview.MvxRecyclerView]
Warning: class [MvvmCross/binding/droid/views/MvxAutoCompleteTextView.class] unexpectedly contains class [mvvmcross.binding.droid.views.MvxAutoCompleteTextView]
Warning: class [MvvmCross/binding/droid/views/MvxDatePicker.class] unexpectedly contains class [mvvmcross.binding.droid.views.MvxDatePicker]
Warning: class [MvvmCross/binding/droid/views/MvxExpandableListView.class] unexpectedly contains class [mvvmcross.binding.droid.views.MvxExpandableListView]
Warning: class [MvvmCross/binding/droid/views/MvxFrameControl.class] unexpectedly contains class [mvvmcross.binding.droid.views.MvxFrameControl]
Warning: class [MvvmCross/binding/droid/views/MvxFrameLayout.class] unexpectedly contains class [mvvmcross.binding.droid.views.MvxFrameLayout]
Warning: class [MvvmCross/binding/droid/views/MvxGridView.class] unexpectedly contains class [mvvmcross.binding.droid.views.MvxGridView]
Warning: class [MvvmCross/binding/droid/views/MvxImageView.class] unexpectedly contains class [mvvmcross.binding.droid.views.MvxImageView]
Warning: class [MvvmCross/binding/droid/views/MvxLinearLayout.class] unexpectedly contains class [mvvmcross.binding.droid.views.MvxLinearLayout]
Warning: class [MvvmCross/binding/droid/views/MvxListItemView.class] unexpectedly contains class [mvvmcross.binding.droid.views.MvxListItemView]
Warning: class [MvvmCross/binding/droid/views/MvxListView.class] unexpectedly contains class [mvvmcross.binding.droid.views.MvxListView]
Warning: class [MvvmCross/binding/droid/views/MvxRadioGroup.class] unexpectedly contains class [mvvmcross.binding.droid.views.MvxRadioGroup]
Warning: class [MvvmCross/binding/droid/views/MvxRelativeLayout.class] unexpectedly contains class [mvvmcross.binding.droid.views.MvxRelativeLayout]
Warning: class [MvvmCross/binding/droid/views/MvxSpinner.class] unexpectedly contains class [mvvmcross.binding.droid.views.MvxSpinner]
Warning: class [MvvmCross/binding/droid/views/MvxTableLayout.class] unexpectedly contains class [mvvmcross.binding.droid.views.MvxTableLayout]
Warning: class [MvvmCross/binding/droid/views/MvxTimePicker.class] unexpectedly contains class [mvvmcross.binding.droid.views.MvxTimePicker]

@tiftof were you able to make it work ?

**Comment by tiftof** [comment] 2016-03-11 07:53
@Miiite Updating the MvvmCross packages worked perfectly for me. Any other problem I had with ProGuard had nothing to do with MvvmCross.

Maybe there are some leftover build artifacts which confuses Xamarin Android to still use MvvmCross instead of mvvmcross. Are you sure you updated all packages and did a clean build?

**Comment by Miiite** [comment] 2016-03-11 08:38
@tiftof Now that you say it, maybe the bin and obj directeories were not nuked correctly.
If it's worked for you, that should work for me too.

I'll try again with a proper clean, and report back here. Thanks for the feedback titof ;)

**Comment by Miiite** [comment] 2016-03-11 13:20
@tiftof I can confirm that I still face this issue.
Like you said in a previous post, maybe my problem comes from the packages I reference.

Proguard raises warnings for MvvmCross.Droid.Support.V7.AppCompat:

Warning: class [MvvmCross/Droid/Support/V7/AppCompat/MvxCachingFragmentCompatActivity.class] unexpectedly contains class [mvvmcross.droid.support.v7.appcompat.MvxCachingFragmentCompatActivity]
Warning: class [MvvmCross/Droid/Support/V7/AppCompat/widget/MvxAppCompatAutoCompleteTextView.class] unexpectedly contains class [mvvmcross.droid.support.v7.appcompat.widget.MvxAppCompatAutoCompleteTextView]
Warning: class [MvvmCross/Droid/Support/V7/AppCompat/widget/MvxAppCompatImageView.class] unexpectedly contains class [mvvmcross.droid.support.v7.appcompat.widget.MvxAppCompatImageView]
Warning: class [MvvmCross/Droid/Support/V7/AppCompat/widget/MvxAppCompatListView.class] unexpectedly contains class [mvvmcross.droid.support.v7.appcompat.widget.MvxAppCompatListView]
Warning: class [MvvmCross/Droid/Support/V7/AppCompat/widget/MvxAppCompatRadioGroup.class] unexpectedly contains class [mvvmcross.droid.support.v7.appcompat.widget.MvxAppCompatRadioGroup]
Warning: class [MvvmCross/Droid/Support/V7/AppCompat/widget/MvxAppCompatSpinner.class] unexpectedly contains class [mvvmcross.droid.support.v7.appcompat.widget.MvxAppCompatSpinner]

Recycler View :
Warning: class [MvvmCross/Droid/Support/V7/recyclerview/MvxRecyclerView.class] unexpectedly contains class [mvvmcross.droid.support.v7.recyclerview.MvxRecyclerView]

And MvvmCross.binding.droid:

Warning: class [MvvmCross/binding/droid/views/MvxAutoCompleteTextView.class] unexpectedly contains class [mvvmcross.binding.droid.views.MvxAutoCompleteTextView]
Warning: class [MvvmCross/binding/droid/views/MvxDatePicker.class] unexpectedly contains class [mvvmcross.binding.droid.views.MvxDatePicker]
Warning: class [MvvmCross/binding/droid/views/MvxExpandableListView.class] unexpectedly contains class [mvvmcross.binding.droid.views.MvxExpandableListView]
Warning: class [MvvmCross/binding/droid/views/MvxFrameControl.class] unexpectedly contains class [mvvmcross.binding.droid.views.MvxFrameControl]
Warning: class [MvvmCross/binding/droid/views/MvxFrameLayout.class] unexpectedly contains class [mvvmcross.binding.droid.views.MvxFrameLayout]
Warning: class [MvvmCross/binding/droid/views/MvxGridView.class] unexpectedly contains class [mvvmcross.binding.droid.views.MvxGridView]
Warning: class [MvvmCross/binding/droid/views/MvxImageView.class] unexpectedly contains class [mvvmcross.binding.droid.views.MvxImageView]
Warning: class [MvvmCross/binding/droid/views/MvxLinearLayout.class] unexpectedly contains class [mvvmcross.binding.droid.views.MvxLinearLayout]
Warning: class [MvvmCross/binding/droid/views/MvxListItemView.class] unexpectedly contains class [mvvmcross.binding.droid.views.MvxListItemView]
Warning: class [MvvmCross/binding/droid/views/MvxListView.class] unexpectedly contains class [mvvmcross.binding.droid.views.MvxListView]
Warning: class [MvvmCross/binding/droid/views/MvxRadioGroup.class] unexpectedly contains class [mvvmcross.binding.droid.views.MvxRadioGroup]
Warning: class [MvvmCross/binding/droid/views/MvxRelativeLayout.class] unexpectedly contains class [mvvmcross.binding.droid.views.MvxRelativeLayout]
Warning: class [MvvmCross/binding/droid/views/MvxSpinner.class] unexpectedly contains class [mvvmcross.binding.droid.views.MvxSpinner]
Warning: class [MvvmCross/binding/droid/views/MvxTableLayout.class] unexpectedly contains class [mvvmcross.binding.droid.views.MvxTableLayout]
Warning: class [MvvmCross/binding/droid/views/MvxTimePicker.class] unexpectedly contains class [mvvmcross.binding.droid.views.MvxTimePicker]

Just as @Cheesebaron said, the package names registered are know ALL in lowercase, so that's OK, but in my case proguard is still saying that this lowercase format does not match the location where he finds the corresponding java classes.

@tiftof what MvvmCross packages do you reference in your project (working with proguard) ?
Maybe these uppercase issues only happen with a certain combinaison of nuget packages ?!

**Comment by Miiite** [comment] 2016-03-11 13:48
Ok well ... I created a completely new project from scratch, and added all the mvvmcross droid nuget packages ... Turns out, when I build in release, the folder names in the __proguardinput__.jar are all in lowercase (so valid).

When I open the __proguardinput__.jar file in my own project (which referenced the nuget packages before), the folder names contain Uppercase letters.

So the MvvmCross configuration seems to be ok.

**Comment by Miiite** [comment] 2016-03-11 17:16
Ok I can finally put an end to this discussion / monologue :D

Here's what happened in my case, hoping it might help someone stuck on the same thing.

Before @Cheesebaron updated the Android packages, I had created my own implementation of the MvxCachingFragmentAppCompatActivity, and to match the syntax used in MvvmCross I registered it as 
 [Register("MvvmCross.Droid.Support.v7.AppCompat.CustomCachingActivity")]

And that's what my mistake was. Even though Cheesebaron's fix worked great, this register with uppercases was enough to modify the directory structure inside the inputproguard.jar file generated when building in Release, and therefore was raising errors for all kinds of MvvmCross classes ... Even though they were registered in lowercase ...

Anyways, thanks @tiftof for the quick feedback that helped me a lot !  (and thanks cheesebaron for the initial fix)
