### ISSUE TITLE
MvvmCross  Xamarin.Forms doesn't work with some syncfusion products such as SfNumericUpDown

### ISSUE THREAD

**Issue by curelom** [MvvmCross/MvvmCross#2961] opened 2018-06-13 22:45 UTC
### Steps to reproduce :scroll:

1.
In Playground.Forms,UI and Playground.Forms.Droid
Add Syncfusion.Xamarin.SfNumericUpDown nuget packages and Syncfusion.Xamarin.SfNumericUpDown.Android
2.
Add to a Page such as Tab1Page.xaml in Playground.Forms.Droid
xmlns:numeric="clr-namespace:Syncfusion.SfNumericUpDown.XForms;assembly=Syncfusion.SfNumericUpDown.XForms"
...
<numeric:SfNumericUpDown x:Name="numericUpDown"/>

3.

### Expected behavior :thinking:
Page should appear with numeric up down

### Actual behavior :bug:
E/mono-rt ( 6188): [ERROR] FATAL UNHANDLED EXCEPTION: MvvmCross.Exceptions.MvxException: Cannot replace MainPage root ---> System.InvalidCastException: Specified cast is not valid.

### Configuration :wrench:

**Version:** 6.1

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by nmilcoff** [comment] 2018-07-28 20:08
Although I could reproduce this issue (I'm attaching the stacktrace) I 100% believe this has nothing to do with MvvmCross. I would suggest you to fill in an issue to Syncfusion, as the exception occurs at the `Com.Syncfusion.Numericupdown.NumericTextBox.SetTextAndValue` method.

I'm closing this issue for the reason stated above. But please feel free to reopen it if you find out that there is actually something in MvvmCross causing it.

```c#
System.InvalidCastException: Specified cast is not valid.

07-28 19:54:45.894 I/MonoDroid( 9748): UNHANDLED EXCEPTION:In mgmain JNI_OnLoad

07-28 19:54:45.904 I/MonoDroid( 9748): System.InvalidCastException: Specified cast is not valid.
07-28 19:54:45.904 I/MonoDroid( 9748):   at (wrapper dynamic-method) System.Object.b704cd09-1d79-4cd1-85f6-201ffddc1bcb(intptr,intptr,intptr,intptr,intptr)
07-28 19:54:45.904 I/MonoDroid( 9748):   at (wrapper managed-to-native) Java.Interop.NativeMethods.java_interop_jnienv_call_nonvirtual_void_method_a(intptr,intptr&,intptr,intptr,intptr,Java.Interop.JniArgumentValue*)
07-28 19:54:45.904 I/MonoDroid( 9748):   at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00073] in <7802aa64ad574c33adca332a3fa9706a>:0 
07-28 19:54:45.904 I/MonoDroid( 9748):   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0001f] in <7802aa64ad574c33adca332a3fa9706a>:0 
07-28 19:54:45.904 I/MonoDroid( 9748):   at Android.Views.View.Measure (System.Int32 widthMeasureSpec, System.Int32 heightMeasureSpec) [0x00035] in <263adecfa58f4c449f1ff56156d886fd>:0 
07-28 19:54:45.904 I/MonoDroid( 9748):   at Xamarin.Forms.Platform.Android.AppCompat.TabbedPageRenderer.OnLayout (System.Boolean changed, System.Int32 l, System.Int32 t, System.Int32 r, System.Int32 b) [0x00182] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\TabbedPageRenderer.cs:375 
07-28 19:54:45.904 I/MonoDroid( 9748):   at Xamarin.Forms.Platform.Android.FormsViewGroup.n_OnLayout_ZIIII (System.IntPtr jnienv, System.IntPtr native__this, System.Boolean p0, System.Int32 p1, System.Int32 p2, System.Int32 p3, System.Int32 p4) [0x00008] in D:\a\1\s\Xamarin.Forms.Platform.Android.FormsViewGroup\obj\Release\generated\src\Xamarin.Forms.Platform.Android.FormsViewGroup.cs:198 
07-28 19:54:45.904 I/MonoDroid( 9748):   at (wrapper dynamic-method) System.Object.be14fbcb-300f-4b7a-b82e-6676a121b88e(intptr,intptr,bool,int,int,int,int)
07-28 19:54:45.904 W/dalvikvm( 9748): JNI WARNING: JNI function NewString called with exception pending
07-28 19:54:45.904 W/dalvikvm( 9748):              in Lmd58432a647068b097f9637064b8985a5e0/FragmentContainer;.n_onCreateView:(Landroid/view/LayoutInflater;Landroid/view/ViewGroup;Landroid/os/Bundle;)Landroid/view/View; (NewString)
07-28 19:54:45.904 W/dalvikvm( 9748): Pending exception is:
07-28 19:54:45.904 I/dalvikvm( 9748): android.runtime.JavaProxyThrowable: System.InvalidCastException: Specified cast is not valid.
07-28 19:54:45.904 I/dalvikvm( 9748):   at Com.Syncfusion.Numericupdown.NumericTextBox.SetTextAndValue (System.String formattedValue, System.Object intermediateValue) [0x00007] in <565118f1de4a4ea382933239eecb2b82>:0 
07-28 19:54:45.904 I/dalvikvm( 9748):   at Com.Syncfusion.Numericupdown.NumericTextBox.GetTextChange (System.Object s) [0x006f3] in <565118f1de4a4ea382933239eecb2b82>:0 
07-28 19:54:45.904 I/dalvikvm( 9748):   at Com.Syncfusion.Numericupdown.NumericTextBox.Init () [0x0003d] in <565118f1de4a4ea382933239eecb2b82>:0 
07-28 19:54:45.904 I/dalvikvm( 9748):   at Com.Syncfusion.Numericupdown.NumericTextBox.OnLoading () [0x0018d] in <565118f1de4a4ea382933239eecb2b82>:0 
07-28 19:54:45.904 I/dalvikvm( 9748):   at Com.Syncfusion.Numericupdown.NumericTextBox..ctor (Android.Content.Context context, Com.Syncfusion.Numericupdown.SfNumericUpDown numericUpDown) [0x000b7] in <565118f1de4a4ea382933239eecb2b82>:0 
07-28 19:54:45.904 I/dalvikvm( 9748):   at Com.Syncfusion.Numericupdown.SfNumericUpDown.InitializeControlSettings () [0x0000d] in <565118f1de4a4ea382933239eecb2b82>:0 
07-28 19:54:45.904 I/dalvikvm( 9748):   at Com.Syncfusion.Numericupdown.SfNumericUpDown..ctor (Android.C
07-28 19:54:45.904 I/dalvikvm( 9748): 	at md58432a647068b097f9637064b8985a5e0.FragmentContainer.n_onCreateView(Native Method)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at md58432a647068b097f9637064b8985a5e0.FragmentContainer.onCreateView(FragmentContainer.java:33)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2261)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2209)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:649)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:145)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.support.v4.view.ViewPager.populate(ViewPager.java:1238)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1616)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.view.View.measure(View.java:16497)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at md58432a647068b097f9637064b8985a5e0.TabbedPageRenderer.n_onLayout(Native Method)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at md58432a647068b097f9637064b8985a5e0.TabbedPageRenderer.onLayout(TabbedPageRenderer.java:73)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.view.View.layout(View.java:14817)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(FormsViewGroup.java:28)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at md58432a647068b097f9637064b8985a5e0.NavigationPageRenderer.n_onLayout(Native Method)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at md58432a647068b097f9637064b8985a5e0.NavigationPageRenderer.onLayout(NavigationPageRenderer.java:65)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.view.View.layout(View.java:14817)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(FormsViewGroup.java:28)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at md51558244f76c53b6aeda52c8a337f2c37.PlatformRenderer.n_onLayout(Native Method)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at md51558244f76c53b6aeda52c8a337f2c37.PlatformRenderer.onLayout(PlatformRenderer.java:63)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.view.View.layout(View.java:14817)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.view.View.layout(View.java:14817)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.view.View.layout(View.java:14817)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.view.View.layout(View.java:14817)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.view.View.layout(View.java:14817)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.view.View.layout(View.java:14817)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.view.View.layout(View.java:14817)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1987)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1744)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1000)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5670)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.view.Choreographer.doCallbacks(Choreographer.java:574)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.view.Choreographer.doFrame(Choreographer.java:544)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.os.Handler.handleCallback(Handler.java:733)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.os.Handler.dispatchMessage(Handler.java:95)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.os.Looper.loop(Looper.java:136)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at android.app.ActivityThread.main(ActivityThread.java:5017)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at java.lang.reflect.Method.invokeNative(Native Method)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at java.lang.reflect.Method.invoke(Method.java:515)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
07-28 19:54:45.904 I/dalvikvm( 9748): 	at dalvik.system.NativeStart.main(Native Method)
07-28 19:54:45.904 I/dalvikvm( 9748): "main" prio=5 tid=1 NATIVE
07-28 19:54:45.904 I/dalvikvm( 9748):   | group="main" sCount=0 dsCount=0 obj=0xa4c9dbd8 self=0xb87d84a0
07-28 19:54:45.904 I/dalvikvm( 9748):   | sysTid=9748 nice=0 sched=0/0 cgrp=[fopen-error:2] handle=-1217351584
07-28 19:54:45.904 I/dalvikvm( 9748):   | state=R schedstat=( 0 0 0 ) utm=162 stm=5095 core=1
07-28 19:54:45.914 I/dalvikvm( 9748):   #00  pc 000bd4b6  /system/lib/libdvm.so (dvmDumpNativeStack(DebugOutputTarget const*, int)+86)
07-28 19:54:45.914 I/dalvikvm( 9748):   #01  pc 00098093  /system/lib/libdvm.so (dvmDumpThreadEx(DebugOutputTarget const*, Thread*, bool)+1155)
07-28 19:54:45.914 I/dalvikvm( 9748):   #02  pc 00098386  /system/lib/libdvm.so (dvmDumpThread(Thread*, bool)+86)
07-28 19:54:45.914 I/dalvikvm( 9748):   #03  pc 0004ce17  /system/lib/libdvm.so (ScopedCheck::checkThread(int)+455)
07-28 19:54:45.914 I/dalvikvm( 9748):   #04  pc 00052905  /system/lib/libdvm.so
07-28 19:54:45.914 I/dalvikvm( 9748):   #05  pc 0000b077  /data/app-lib/com.mvvmcross.playground.forms-1/libmonodroid.so (java_interop_jnienv_new_string+55)
07-28 19:54:45.914 I/dalvikvm( 9748):   #06  pc 00023c43  <unknown>
07-28 19:54:45.914 I/dalvikvm( 9748):   at md58432a647068b097f9637064b8985a5e0.FragmentContainer.n_onCreateView(Native Method)
07-28 19:54:45.914 I/dalvikvm( 9748):   at md58432a647068b097f9637064b8985a5e0.FragmentContainer.onCreateView(FragmentContainer.java:33)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.support.v4.app.Fragment.performCreateView(Fragment.java:2261)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2209)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:649)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:145)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.support.v4.view.ViewPager.populate(ViewPager.java:1238)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1616)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.view.View.measure(View.java:16497)
07-28 19:54:45.914 I/dalvikvm( 9748):   at md58432a647068b097f9637064b8985a5e0.TabbedPageRenderer.n_onLayout(Native Method)
07-28 19:54:45.914 I/dalvikvm( 9748):   at md58432a647068b097f9637064b8985a5e0.TabbedPageRenderer.onLayout(TabbedPageRenderer.java:73)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.view.View.layout(View.java:14817)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.view.ViewGroup.layout(ViewGroup.java:4631)
07-28 19:54:45.914 I/dalvikvm( 9748):   at com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(FormsViewGroup.java:28)
07-28 19:54:45.914 I/dalvikvm( 9748):   at md58432a647068b097f9637064b8985a5e0.NavigationPageRenderer.n_onLayout(Native Method)
07-28 19:54:45.914 I/dalvikvm( 9748):   at md58432a647068b097f9637064b8985a5e0.NavigationPageRenderer.onLayout(NavigationPageRenderer.java:65)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.view.View.layout(View.java:14817)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.view.ViewGroup.layout(ViewGroup.java:4631)
07-28 19:54:45.914 I/dalvikvm( 9748):   at com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(FormsViewGroup.java:28)
07-28 19:54:45.914 I/dalvikvm( 9748):   at md51558244f76c53b6aeda52c8a337f2c37.PlatformRenderer.n_onLayout(Native Method)
07-28 19:54:45.914 I/dalvikvm( 9748):   at md51558244f76c53b6aeda52c8a337f2c37.PlatformRenderer.onLayout(PlatformRenderer.java:63)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.view.View.layout(View.java:14817)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.view.ViewGroup.layout(ViewGroup.java:4631)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.view.View.layout(View.java:14817)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.view.ViewGroup.layout(ViewGroup.java:4631)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.view.View.layout(View.java:14817)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.view.ViewGroup.layout(ViewGroup.java:4631)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.view.View.layout(View.java:14817)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.view.ViewGroup.layout(ViewGroup.java:4631)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.view.View.layout(View.java:14817)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.view.ViewGroup.layout(ViewGroup.java:4631)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.view.View.layout(View.java:14817)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.view.ViewGroup.layout(ViewGroup.java:4631)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.view.View.layout(View.java:14817)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.view.ViewGroup.layout(ViewGroup.java:4631)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1987)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1744)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1000)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5670)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.view.Choreographer.doCallbacks(Choreographer.java:574)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.view.Choreographer.doFrame(Choreographer.java:544)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.os.Handler.handleCallback(Handler.java:733)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.os.Handler.dispatchMessage(Handler.java:95)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.os.Looper.loop(Looper.java:136)
07-28 19:54:45.914 I/dalvikvm( 9748):   at android.app.ActivityThread.main(ActivityThread.java:5017)
07-28 19:54:45.914 I/dalvikvm( 9748):   at java.lang.reflect.Method.invokeNative(Native Method)
07-28 19:54:45.914 I/dalvikvm( 9748):   at java.lang.reflect.Method.invoke(Method.java:515)
07-28 19:54:45.914 I/dalvikvm( 9748):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
07-28 19:54:45.914 I/dalvikvm( 9748):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
07-28 19:54:45.914 I/dalvikvm( 9748):   at dalvik.system.NativeStart.main(Native Method)
07-28 19:54:45.914 I/dalvikvm( 9748): 
07-28 19:54:45.914 E/dalvikvm( 9748): VM aborting
07-28 19:54:45.914 F/libc    ( 9748): Fatal signal 6 (SIGABRT) at 0x00002614 (code=-6), thread 9748 (layground.forms)
```

**Closed by nmilcoff** 2018-07-28 20:08 UTC
