### ISSUE TITLE
Installing Color Plugin in nuget doesn't update everything to 3.0.13

### ISSUE THREAD

**Issue by markentner** [MvvmCross/MvvmCross#472] opened 2013-10-23 17:40 UTC
I installed the Color plug in today and many of the MvvmCross packages were automatically upgraded to 3.0.13.  However, not all of them were (i.e. MvvmCross Hot Tuna Starter Pack was not).  The project didn't build after the update because of the change from initialise to initialize.  Also, when I uninstalled the color plug in, the original versions of the packages did not get installed.  So, I still had the issue after installing.

Once I figured out where the issue was, I was able to update the other packages to 3.0.13 manually and things appear to be OK.

**Comment by martijn00** [comment] 2015-01-24 14:01
This is very easy to fix by mannually updating packages. Closing this for now.

**Closed** 2015-01-24 14:00 UTC
Labels: code improvement

**Comment by powerdude** [comment] 2015-01-24 16:51
this is probably not a good attitude to take.  The premise of nuget is violated here and the package should do the right thing and make sure things are installed correctly.  Putting this on all the consumers of the package instead of addressing the problem is not the ideal solution.

**Comment by slodge** [comment] 2015-01-26 07:39
Thanks @powerdude. I think your comment on the attitude is correct (see our manifesto in the wiki :)) - however, in this situation, I think the project is doing the right thing - because....:

1. The initial problem - the problems caused by changes from `Initialise` to `Initialize`. These were acknowledged as problems (I believe they were in the release notes too). We do go to quite long lengths to try to avoid "breaking changes" and will continue to do so - but sometimes it is better to fix things, and we tend to do this when we have big version numbers changes.

2. The secondary problem - nuget updating files like `Setup.cs` during updates. Actualy nuget shouln't do this - if the file already exists it should prompt you about whether you want it overwritten. Further, the general advice I try to promote is that users should remove the `StarterPack` level of nuget dependencies from `packages` once they have their app up and running - if they leave only the `libraries` level of dependency, then this will not cause files like `Setup.cs` to get updated. 
 
So, I think both of these now come down to better communication/information - and so I'm happy to see this issue closed.

Thanks again for the comment - hope we are heading in the right direction :)

Stuart
