### ISSUE TITLE
awaiting MvxViewModel.Initialize() is buggy

### ISSUE THREAD

**Issue by Gabriel1786** [MvvmCross/MvvmCross#3209] opened 2018-11-21 22:24 UTC
## 🐛 Bug Report

So the docs say that all heavy loading should be done in MvxViewModel.Initialize(), however anytime I put an await inside that method, the app doesnt load the VM's view. I originally had all my code from ViewCreated() inside Initialize().

```
namespace RDPReader.Core.ViewModels
{
    public class AppConfigViewModel : BaseViewModel
    {
        readonly IMvxNavigationService _navigationService;

        public AppConfigViewModel(IMvxNavigationService navigationService)
        {
            _navigationService = navigationService;

            ShowMainViewModelCommand = new MvxAsyncCommand(async () => await _navigationService.Navigate<MainViewModel>());
            ShowLoginViewModelCommand = new MvxAsyncCommand(async () => await _navigationService.Navigate<LoginViewModel>());
        }

        // MvvmCross Lifecycle
        public override async Task Initialize()
        {
            //await Task.Delay(4000);

            //return base.Initialize();
        }

        public override async void ViewCreated()
        {
            base.ViewCreated();

            await Task.Delay(1000);

            LoadingMessage = "Carregando X";

            await Task.Delay(1000);

            LoadingMessage = "Carregando Y";

            await Task.Delay(1000);


            await _navigationService.Navigate<MainViewModel>();
        }

        // MVVM Properties
        string _loadingMessage;
        public string LoadingMessage
        {
            get => _loadingMessage;
            set => SetProperty(ref _loadingMessage, value);
        }

        // MVVM Commands
        public IMvxAsyncCommand ShowMainViewModelCommand { get; }
        public IMvxAsyncCommand ShowLoginViewModelCommand { get; }

        // Private Methods
    }
}

```

### Expected behavior

I wanted to load some things and present to the user what is being loaded onscreen through LoadingMessage property, after completion navigate to next screen.

### Reproduction steps

Remove the commented await Task.Delay inside Initialize and it will stop working (it will stay stuck on SplashScreen), comment it again and it works. The question is why is it like that? For now I'm doing all the loading on ViewCreated(). So either there is a bug or the docs need to be updated.

### Configuration

**Version:** 6.2.2

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [x] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by xufeipyxis** [comment] 2018-11-27 07:57
I can confirm this bug in the playground project. 
In the `RootViewModel.cs`, just uncomment this line in `Initialize()` and the bug can be reproduced.

    // await Task.Delay(5000);

**Comment by pinkysek** [comment] 2018-11-27 13:41
I can confirm this bug too, when I call async method in Initialize() which has await Task.Delay(150) its stuck my app on LaunchScreen in iOS project.

**Comment by elucidsoft** [comment] 2018-11-29 17:00
I think this is what I'm seeing in #3221

**Comment by flostr** [comment] 2018-12-14 17:16
Happens for me too. I currently fixed this by removing the **await** in **MvxAppStart<TViewModel>.NavigateToFirstViewModel**>:
```
        protected override async Task NavigateToFirstViewModel(object hint = null)
        {
            try
            {
                //await NavigationService.Navigate<TViewModel>();
                NavigationService.Navigate<TViewModel>();
            }
            catch (System.Exception exception)
            {
                throw exception.MvxWrap("Problem navigating to ViewModel {0}", typeof(TViewModel).Name);
            }
        }
```

**Comment by sprzygoda** [comment] 2019-01-22 14:24
I ran into similar issue recently.  My solution was to create a separate "heavy stuff" method and call it from inside Initialize:

```
        public override Task Initialize()
        {
            return Task.Run(() => DoSomeHeavyStuffAsync());
        }

        public async Task DoSomeHeavyStuffAsync()
        {
            var res = await Foo();
            var something = await Bar(res);
            UseSomethingAsync(something);
        }
```

But it would be great if Initialize could just run as expected...

**Comment by sprzygoda** [comment] 2019-01-24 11:42
@Gabriel1786 
I came across similar issue few days ago and my solution was to just call another async method from inside Initialize()

```
public override Task Initialize()
        {
            return DoSomeAsyncStuffAsync();
        }

        public async Task DoSomeAsyncStuffAsync()
        {
            var result = await _customService.GetResultAsync();
            var something = await _anotherCustomService.GetSomethingElseAsync(result);
            DoSomethingElseAsync(something);
        }
```

**Comment by Mookker** [comment] 2019-04-01 11:54
Hi guys, any update on this one?
Still having this issue on iOS platform.
I've moved stuff to Start() method and it helps, but still looks weird.

**Comment by beylkhanovdamir** [comment] 2019-07-24 07:26
the same issue for me... 
as for temporary solution I've moved my initialization to ViewAppeared method

**Comment by sledderGIT** [comment] 2019-09-10 14:04
me too. I do as sprzygoda.

**Comment by Cheesebaron** [comment] 2021-04-06 07:29
Duplicate of #3114

**Closed by Cheesebaron** 2021-04-06 07:29 UTC
Labels: s/needs-investigation, up-for-grabs
