### ISSUE TITLE
ConfigureAwait(false) in MvxNavigationService.cs makes  `OnBeforeNavigate` and `OnAfterNavigate` run in different context

### ISSUE THREAD

**Issue by flyingxu** [MvvmCross/MvvmCross#3223] opened 2018-11-30 03:29 UTC
## 🐛 Bug Report

Personally, I don't like to use `ConfigureAwait(false)` in this package because MvvmCross is UI related. In this example in \MvvmCross\Navigation\MvxNavigationService.cs:
```
protected virtual async Task<bool> Navigate(MvxViewModelRequest request, IMvxViewModel viewModel, IMvxBundle presentationBundle = null, CancellationToken cancellationToken = default(CancellationToken))
{
	var hasNavigated = false;

	var args = new MvxNavigateEventArgs(viewModel, NavigationMode.Show, cancellationToken);
	OnBeforeNavigate(this, args);

	if (args.Cancel)
		return false;

	hasNavigated = await ViewDispatcher.ShowViewModel(request);
	if (!hasNavigated)
		return false;

	if (viewModel.InitializeTask?.Task != null)
		await viewModel.InitializeTask.Task.ConfigureAwait(false);

	OnAfterNavigate(this, args);
	return true;
}
```
Because of the `.ConfigureAwait(false);`, `OnBeforeNavigate` and `OnAfterNavigate` might run in different threads / context. I'm from MFC background, when I see some function like `OnBeforeNavigate` I would assume it's on UI context but it might not. 

### Expected behavior
`OnBeforeNavigate` and `OnAfterNavigate` should run on UI context, or at least in the same thread.
### Configuration

**Version:** 6.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by nickrandolph** [comment] 2018-12-02 21:10
This is by design and as such closing this bug. If you'd like to propose a different implementation, please raise a PR.

**Closed by nickrandolph** 2018-12-02 21:10 UTC

**Comment by flyingxu** [comment] 2018-12-07 07:01
Ok, I figured it out. I need to call

    base.InvokeOnMainThreadAsync(() => { });

this wrapper funciton is available in any ViewModel derived classes.
