### ISSUE TITLE
After navigating with back button Command can't be called

### ISSUE THREAD

**Issue by xyashapyx** [MvvmCross/MvvmCross#3064] opened 2018-08-10 13:46 UTC
## 🐛 Bug Report

I'm having IMvxAsyncCommand that calls Navigation to view with result, like 
var result = await NavigationService.Navigate<SecondViewModel, Parameter, Result>(parameter);
And when I'm navigating back from SecondViewModel with hardware button it is no longer possible to call this command.

### Configuration

**Version:** 6.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by xyashapyx** [comment] 2018-08-10 15:06
BTW, if I'm declaring my command as allowConcurrentExecutions = true all is working fine.

**Comment by nmilcoff** [comment] 2018-08-10 20:30
I noticed this as well, easy to reproduce.

As a workaround you can add this line to your SecondViewModel's OnDissapearing:

`ViewModel.CloseCompletionSource?.TrySetResult(false);`

**Comment by xyashapyx** [comment] 2018-10-10 09:21
@piotrekbigu you can innit your command with allowConcurrentExecutions = true. This is kind of work around.

**Comment by piotrekbigu** [comment] 2018-10-13 13:06
@xyashapyx
Yeah I know it but I do not want to give my commands a chance to execute concurrently :)

**Comment by indyjason79** [comment] 2018-10-22 18:16
We've been struggling with this issue for the last 6 months. We ended up removing the async from navigation all together and we also have to register the commands on every page load for some reason. If you set a command in the constructor to navigate, then navigate, then go back the command is no longer wired up. To get around this we call a private method called SetNavigationCommands in the ViewAppearing method to get it to work correctly. GIANT pain and ugly code because of this issue. We're not passing parameters like they are in the example. We were just trying to navigate normally using MvxAsyncCommand(() => _navigationService.Navigate<SettingsTabbedViewModel>());

**Comment by nwilliams** [comment] 2019-04-05 22:31
I believe this is related to the poor support for `CanExecute`/`CanExecuteChanged` functionality on `ICommand` (as called out in the [Data binding documentation](https://www.mvvmcross.com/documentation/fundamentals/data-binding) for MvvmCross). To work around it, I added a property to my ViewModel called `CanNavigate` and bound the `IsEnabled` property of my button to it.

```
public bool CanNavigate { get; } = true;

public IMvxCommand NavigateAsync => new MvxAsyncCommand(async () =>
{
    await navigationService.Navigate<NextPageViewModel>();

    await RaisePropertyChanged(() => CanNavigate);
});
```

And in my XAML:
`<Button mvx:Bi.nd="Command NavigateAsync; IsEnabled CanNavigate" Text="Navigate"/>`

By virtue of it being a work around it's obviously not ideal, but in all of my testing it has proved successful.

**Comment by nickrandolph** [comment] 2019-04-05 22:41
@Cheesebaron @martijn00 is there an issue with how we complete async navigation methods when the user presses the back button v closing the view model?

**Comment by nwilliams** [comment] 2019-04-05 22:52
> 
> 
> @Cheesebaron @martijn00 is there an issue with how we complete async navigation methods when the user presses the back button v closing the view model?

Just FYI, I've encountered this issue when closing the view model as well (albeit less frequently), so I don't think it's limited to the back button.

**Comment by agat366** [comment] 2019-10-10 17:42
I confirm that the issue exists as of 6.4.0 version.
In fact, it is actual for a long time.
I found [this issue](https://github.com/MvvmCross/MvvmCross/issues/1589) (closed by some reason), which looks like quite similar one (2.5 years(!) ago).

**And the issue is quite serious, because there always no guarantee the IMvxAsyncCommand will definitely work**, so it just eliminates a sense of using of it at all (even though the idea of using it for controls disabling until the processing (async) method finished is pretty cool).

Also, to be more clear, I stuck with it quite often lately. **And all the projects I had the issue, were Xamarin.Forms, and the issue seemed to appear on Android only**.

**Comment by Cheesebaron** [comment] 2019-10-11 07:03
It is because some async method inside of the command doesn't finish or cannot return to the context it came from and dead-locks. That is something we cannot fix from a framework perspective.

**Comment by Oxoproline** [comment] 2019-12-10 09:44
Yes this issue is here for a while and it's not just for navigation it happens for other async calls too.
And yes so far what I've seen over the years it's only android issue.

**Comment by Cheesebaron** [comment] 2019-12-11 14:50
Well if the task that runs inside a `MvxAsyncCommand` doesn't finish and you haven't allowed multiple executions, then `CanExecute` will return false until the task has finished or you have cancelled the command by calling `Cancel()` on it.

**Comment by Oxoproline** [comment] 2019-12-11 15:27
@Cheesebaron We are talking about tasks that finished. 
It is easily reproducible. Just create simple app that has two tab pages: Page1 and Page2. Place on Page1 Button with `MvxAsyncCommand(SomeTask) ` 

`
private async Task SomeTask()
        {
            await Task.Delay(5000);
        }
`

On the android click on the button and it become disabled. Move to second tab Page2. Leave the task to finish and then move back to Page1.

Button remains disabled even though the task has finished. If you test some other bindings like change the text of the button after `await Task.Delay(3000)` while you are on the tab Page2 these are working.

On iOS no issues with this, but the button is not disabled at all. It is still clickable just the command task is not invoked.

**Comment by Oxoproline** [comment] 2019-12-11 16:32
@Cheesebaron We are talking about tasks that finished.
It is reproducible on my phone xiaomi MI A1, android 9. On the emulator this example is working fine. 

Create simple app that has two tab pages: Page1 and Page2. Place on Page1 Button with MvxAsyncCommand(SomeTask)

private async Task SomeTask() { await Task.Delay(5000); }

On the android click on the button and it become disabled. Move to second tab Page2. Leave the task to finish and then move back to Page1.

Button remains disabled even though the task has finished. If you test some other bindings like change the text of the button after await Task.Delay(3000) while you are on the tab Page2 these are working.

On iOS no issues with this, but the button is not disabled at all. It is still clickable just the command task is not invoked.

here is the recording:
[recoridng.zip](https://github.com/MvvmCross/MvvmCross/files/3951442/recoridng.zip)

**Comment by mjrichards91** [comment] 2020-04-13 12:01
It seems this issue still exists and is not limited to just Android as others have suggested. I am experiencing this same issue on an Xamarin.Forms app with MvvmCross 6.4.2 running on iOS 12. However, for some reason, iOS 13 doesn't have that same issue.

**Comment by purusartha** [comment] 2020-04-18 14:22
I had the same issue, and as per the documentation [https://www.mvvmcross.com/documentation/fundamentals/navigation](url)
in the override for ViewDestroy, I set the CloseCompletionSource state, which then correctly cancelled the navigation task, thus making my control active again:
```
public override void ViewDestroy(bool viewFinishing = true)
{
           
            if (CloseCompletionSource != null && !CloseCompletionSource.Task.IsCompleted && !CloseCompletionSource.Task.IsFaulted)
                CloseCompletionSource?.TrySetCanceled();
            base.ViewDestroy(viewFinishing);
}
```

**Comment by clem13480** [comment] 2020-07-03 09:47
Any news on this issue ? Still happens in 6.4.2 on android.
There is plenty work around to make things works (like with cancellation token), but did they intent to fix the issue at it's core ?

**Comment by vineet290880** [comment] 2020-07-22 17:46
It also happens on 6.4.3

**Comment by clem13480** [comment] 2020-08-18 16:38
Still happens with mvvmcross 7.0.0 on Android. Any news concerning this issue ?

**Comment by clem13480** [comment] 2020-08-18 16:51
> I had the same issue, and as per the documentation [https://www.mvvmcross.com/documentation/fundamentals/navigation](url)
> in the override for ViewDestroy, I set the CloseCompletionSource state, which then correctly cancelled the navigation task, thus making my control active again:
> 
> ```
> public override void ViewDestroy(bool viewFinishing = true)
> {
>            
>             if (CloseCompletionSource != null && !CloseCompletionSource.Task.IsCompleted && !CloseCompletionSource.Task.IsFaulted)
>                 CloseCompletionSource?.TrySetCanceled();
>             base.ViewDestroy(viewFinishing);
> }
> ```

This work around is actually quite simple and works well.

**Comment by LITTOMA** [comment] 2020-09-18 07:08
> > I had the same issue, and as per the documentation [https://www.mvvmcross.com/documentation/fundamentals/navigation](url)
> > in the override for ViewDestroy, I set the CloseCompletionSource state, which then correctly cancelled the navigation task, thus making my control active again:
> > ```
> > public override void ViewDestroy(bool viewFinishing = true)
> > {
> >            
> >             if (CloseCompletionSource != null && !CloseCompletionSource.Task.IsCompleted && !CloseCompletionSource.Task.IsFaulted)
> >                 CloseCompletionSource?.TrySetCanceled();
> >             base.ViewDestroy(viewFinishing);
> > }
> > ```
> 
> This work around is actually quite simple and works well.

@clem13480  How does it work? CloseCompletionSource is always null.

**Comment by clem13480** [comment] 2020-09-18 07:16
> > > I had the same issue, and as per the documentation [https://www.mvvmcross.com/documentation/fundamentals/navigation](url)
> > > in the override for ViewDestroy, I set the CloseCompletionSource state, which then correctly cancelled the navigation task, thus making my control active again:
> > > ```
> > > public override void ViewDestroy(bool viewFinishing = true)
> > > {
> > >            
> > >             if (CloseCompletionSource != null && !CloseCompletionSource.Task.IsCompleted && !CloseCompletionSource.Task.IsFaulted)
> > >                 CloseCompletionSource?.TrySetCanceled();
> > >             base.ViewDestroy(viewFinishing);
> > > }
> > > ```
> > 
> > 
> > This work around is actually quite simple and works well.
> 
> @clem13480 How does it work? CloseCompletionSource is always null.

You have to be inheriting IMvxViewModel<TParameter, TResult>.
Here is my full base class. And the CloseCompletionSource is not null.

public abstract class BaseViewModel<TParameter, TResult> : BaseViewModel<TParameter>, IMvxViewModel<TParameter, TResult>, IBaseViewModel
    {
        public TaskCompletionSource<object> CloseCompletionSource { get; set; }
        public BaseViewModel(IMvxLogProvider log, IMvxNavigationService navigationService) : base(log, navigationService) { }

        public override void ViewDestroy(bool viewFinishing = true)
        {
            if (CloseCompletionSource != null && !CloseCompletionSource.Task.IsCompleted && !CloseCompletionSource.Task.IsFaulted)
                CloseCompletionSource?.TrySetCanceled();

            base.ViewDestroy(viewFinishing);
        }
    }

**Comment by JDeuker** [comment] 2020-09-29 09:18
@clem13480 I can reproduce the issue, even with CloseCompletionSource implemented. Have you implemented any cancellation logic inside your MvxAsyncCommand?

@LITTOMA  CloseCompletionSource will not be null if you navigate to it with the return object overloading.

I also noticed that this effect only occurs once for one command. After one command is disabled, the others work fine.

If I set allowConcurrentExecutions in MvxAsyncCommand to true, then it works fine. But this is not the solution.

The ViewModel navigation Task finishes properly. So maybe the MvxAsyncCommand noticing it is not implemented properly.

**Comment by deepblueday** [comment] 2020-10-13 23:03
> I had the same issue, and as per the documentation [https://www.mvvmcross.com/documentation/fundamentals/navigation](url)
> in the override for ViewDestroy, I set the CloseCompletionSource state, which then correctly cancelled the navigation task, thus making my control active again:
> 
> ```
> public override void ViewDestroy(bool viewFinishing = true)
> {
>            
>             if (CloseCompletionSource != null && !CloseCompletionSource.Task.IsCompleted && !CloseCompletionSource.Task.IsFaulted)
>                 CloseCompletionSource?.TrySetCanceled();
>             base.ViewDestroy(viewFinishing);
> }
> ```

@purusartha 's solution is a good workaround, but it has a catch. If you are only navigating from A->B, then you are golden. Hitting "back" on B causes the navigation call to return a null result which you can manage accordingly in your code. After that, the IMvxAsyncCommand works as expected.

BUT. If you do A->B and then B->C, when the B->C navigation occurs, the ViewDestroy method is invoked, thus causing the await for navigation from A->B to return a null result, even though you should techincally be still waiting for the result of A->B navigation. I had that in my code, rendering the suggested workaround unusable.

**Comment by Cheesebaron** [comment] 2021-09-08 08:17
Will be adressed in #4262

**Closed by Cheesebaron** 2021-09-08 08:17 UTC
Labels: s/needs-investigation, up-for-grabs
