### ISSUE TITLE
Can't add nuget package 3.5.1 into project targets 'MonoAndroid, Version=v5.0'

### ISSUE THREAD

**Issue by KhuongNtrd** [MvvmCross/MvvmCross#1001] opened 2015-05-08 10:41 UTC
"Could not install package 'MvvmCross.PortableSupport 3.5.1'. You are trying to install this package into a project that targets 'MonoAndroid, Version=v5.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

**Comment by nunohorta** [comment] 2015-05-15 09:36
any news here guys??

**Comment by Cheesebaron** [comment] 2015-05-15 09:44
What are your targets?

**Comment by slodge** [comment] 2015-05-15 10:04
`MonoAndroid` is your problem - you need to be on Xamarin.Android nowadays

**Comment by KhuongNtrd** [comment] 2015-05-16 18:32
Thanks all, i have fixed that issue, just some problems about the newest nuget api (api.nuget.org).

**Comment by guiwaltricke** [comment] 2015-05-20 14:10
@KhuongNtrd  how do you solve? i am getting the same error =(

**Comment by helado** [comment] 2015-05-21 08:13
Same here....

**Comment by Cheesebaron** [comment] 2015-05-21 08:54
1. Make sure you have the latest nuget plugin
2. Try setting your target to 21 or similar instead of "use SDK version"

**Comment by guiwaltricke** [comment] 2015-05-21 10:17
@Cheesebaron I did this... but does not works...

**Comment by rubenvb** [comment] 2015-06-11 19:26
Same here. VS2015 RC, installed Xamarin through its installer. The exact error is:

> Install-Package : Could not install package 'MvvmCross.PortableSupport 3.5.1'. You are trying to install this package into a project that targets 'MonoAndroid, Version=v4.4', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

It seems there is some incompatibility between current Xamarin.Android and MvvmCross. It does not matter which Android version I select as a target (I have 2.3 thru 5.1 installed, the latter is not selectable in the Droid UI project's properties)

**Comment by slodge** [comment] 2015-06-11 19:41
It really feels like this is MS/Xam bug - `MonoAndroid` is the clue to me... Xamarin have changed every Mono name they can to Xamarin... it's the brand...

**Comment by rubenvb** [comment] 2015-06-11 20:34
See below for the Mono.Android reference in my project, created as a Blank App (Android) in VS2015RC with the latest Xamarin.Android installed. A lot of the dialogs in various properties dialogs mention Xamarin.Android, but this uses Mono.Android. Is there away to make nuget fetch the mvvmcross packages for this as well?

![knipsel](https://cloud.githubusercontent.com/assets/308670/8117607/b39d1500-1089-11e5-9af8-3af815f0621c.PNG)

**Comment by slodge** [comment] 2015-06-11 21:04
Maybe @KhuongNtrd can help... he seemed to know what the problems were... :+1:

**Comment by rubenvb** [comment] 2015-06-11 22:12
See http://stackoverflow.com/q/30148092 for a workaround. Seems like the issue is localised to VS 2015 RC.

**Comment by PeterBurke** [comment] 2015-06-25 02:46
We need to get this issue addressed because there are too many upstart MvvM packages like MvvM Light nipping at the heels of MvvMCross and because MvvMCross is a much better package given the volume of already written plugins.

I have forked the NuGet project and I have started investigating the code.

**Comment by PeterBurke** [comment] 2015-06-26 02:29
OK I have done a preliminary investigation and sorry Stuart I think there may be an issues in your area that I would like your advice on.

Firstly it seems that the Source for NuGet is still in CodePlex although there is some activity in GitHub to move it to a repository NuGet3. I note that there was a release 2.8.5 March 26 that found it's way into VS 2015 RC. There was another Beta release May 7 that does not resolve the issue, and another Beta release on June 3 they are calling NuGet 3.0 RC2.

Secondly in relation to NuGet target strings I think that NuGet does not care if you use the term "Xamarin.Android" or "MonoAndroid". Looking at the code, in a files VersionUtility.cs and NetPortableProfileTable.cs string tests are case insensitive, you can drop the '.', it only cares that a string starts with what it is looking for, it groups those starting with 'Mono' and those starting with 'Xamarin' into a single group etc.

### Working through the process ###
Following the actual install process using the Package Manager Console, what I see happening is as follows:

1.  Install package into PCL (*downloads package, unzips it under packages, creates links to the assemblies in the csproj*)
```
PM> Install-Package Cheesebaron.MvxPlugins.FormsPresenters -DependencyVersion Lowest -ProjectName SampleApp
```

2. Cheesebaron.MvxPlugins.FormsPresenters has a dependency in its NuSpec on MvvmCross.HotTuna.CrossCore so it knows that it must download that package also (*downloads package, unzips it under packages, creates links to the assemblies in the csproj*)

3. MvvmCross.HotTuna.CrossCore has a dependency in its NuSpec on MvvmCross.PortableSupport so it knows that it must download that package also (*downloads package, unzips it under packages)

At this point everything appears to be OK. But the Droid and iOS installs will fail.

### MvvmCross.PortableSupport package seems flawed ###
I note that the MvvmCross.PortableSupport seems flawed. That package contains a single directory under its lib directory: "portable-win+net45+wp8+win8+wpa81" and that directory contains a single file "-.-" that is 92 characters long and reads: "Please ignore this file - just needed to make nuget work with our portable support libraries". Thus the package has no assemblies that can be linked into the PCL csproj, but it has no assemblies at all. I checked the MvvmCross.PortableSupport.3.5.1.nupkg file that was downloaded. This is actually a zipped file with contents exactly as they were originally created. **The package contains no assemblies.**

Now that has to be an issue when we come to install the Droid and iOS packages, because for these two targets we actually need MvvmCross.PortableSupport do we not?

### From the NuGet Install log ###

When we attempt to install into Droid and iOS projects the NuGet Package manager reports:
```
PM> Install-Package Cheesebaron.MvxPlugins.FormsPresenters -DependencyVersion Lowest -ProjectName SampleApp.Droid
```
```
Attempting to gather dependencies information for package 'Cheesebaron.MvxPlugins.FormsPresenters.0.0.2' with respect to project targeting 'MonoAndroid, Version=v5.0'
```
```
Attempting to resolve dependencies for package 'Cheesebaron.MvxPlugins.FormsPresenters.0.0.2' with DependencyBehavior 'Lowest'
```
```
Resolving actions to install package 'Cheesebaron.MvxPlugins.FormsPresenters.0.0.2'
```
```
Resolved actions to install package 'Cheesebaron.MvxPlugins.FormsPresenters.0.0.2'
```
**Install failed. Rolling back...**
```
Package 'MvvmCross.PortableSupport 3.5.1' does not exist in project 'SampleApp.Droid'
Install-Package : Could not install package 'MvvmCross.PortableSupport 3.5.1'. You are trying to install this package into a project that targets 'MonoAndroid, Version=v5.0', but the package does not 
contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
```

Yes NuSpec log contains "... that targets 'MonoAndroid, Version=v5.0' ..." and that has thrown us off a bit, but as we determined previously when you install 'MvvmCross.PortableSupport 3.5.1' you download a package that contains no assemblies or content and that can not be correct. Surely what you want is that when you are installing a Droid or iOS target an extra assembly is then linked in?

### Nuget issues when package dependencies are complex ###

The problem here is that NuGet does not work well when you have very specialised relationships like these. I had a similar experience with the "Portable DataAnnotations" where it is not a simple case splitting the world into PCL and targets. The more recent .NET derivatives including Xamarin actually already have DataAnnotations built in, so the developers of "Portable DataAnnotations" had to resort to tricks in order to make things work.

As for the 'MonoAndroid, Version=v5.0' in the log, from what I can see in the NuSpec code so far, it seems that NuSpec has a table of ProjectTypeGuid and every CSPROJ has a ProjectTypeGuid so NuGet knows that when it is told that there is a dependency on 'MvvmCross.PortableSupport' it must visit the content and lib directories for that package and determine the correct target directory. It is my guess that when it finds nothing at all in the downloaded package it then throws the panic where maybe it did not in previous version.

**Comment by slodge** [comment] 2015-06-27 18:59
Good work going through the nugget source:+1:

> sorry Stuart I think there may be an issues in your area that I would like your advice on.

What are they?

Only specific question I could see was whether portable support is needed... To which answer is I'm not sure it is - it was originally split out so that others could use our stub dll's for pcl support. There might still be something there for mac, but I think they could possibly go...

Will be back soon... Triathlon tomorrow and then I'm free of this cycling malarkey :)

**Comment by PeterBurke** [comment] 2015-06-28 01:00
Thanks Stuart

So you are into Triathlon, I am into that sort of thing myself, participated in the first everymans triathlon Hong Kong 1994, I get up 4.00 every morning and hit the Gym 5:30 am for 90 minutes including running uphill on a treadmill for 60 minutes. It's unseasonably cold down here right now. As I slowly drove up the Ridge a Kangaroo hopped across the road in front of me.

I am hoping to get a contract in London later this year. I have right of abode and a brother there.

What I am trying to do right now is to set up a site that demonstrates a number of Enterprise application patterns specifically using Xamarin. The outcomes from this exercise would be a number of Visual Studio project and item templates that users could use to quick start solultions.

Having deep experience with WPF and XAML specifically I want these solutions to use Xamarin.forms XAML not c#. XAML cuts out at least 80% of the finger work compared to c# and although intellisense helps in c# Blend to Edit XAML is easier still. I also wanted everything to be based on the very best MvvM available, which is of course MvvMCross. The collection of existing plugins is a great productivity tool. Of course the youngsters all want to fly by the seats of their pants and not to be held back by being at the start of a very steep learning curve.

As an aside in Visual Studio 2015  Microsoft and Xamarin are supporting new XAML extensions for the Universal App. This extension can allows the Universal App to rearrange visual elements in order to best work with the device screen geometry, See https://visualstudiomagazine.com/articles/2015/05/27/adaptive-layout-windows-universal-app-plat.aspx May 1 and VS 2015 RC and coordinated Xamarin releases introduced a new Xamarin target that targets Windows Phone and Windows store apps directly (no silverlight).

I started working with Tomasz Cielecki's Mvx.FormsPresenters. It seems to me that both MvvMCross and Mvx.FormsPresenters were built for the c# Xamarin.Forms and not the XAML developers like myself. There were no examples anywhere. However I got it working with XAML. One issue with MvvMCross and Mvx.FormsPresenters NuSpec is that it has content files that are incompatible with the XAML solution. Another issue is that the PCL Profile that it uses is now out of date due to the new UAP target.

So in summary:


1.       I would like my example solution templates to link to MvvMCross and Mvx.FormsPresenters via NuGet but that is not going to work for me right now.


2.       In MvvMCross the reference to MobileSupport that does not need to be there causes the latest NuGet to throw an exception. It's not needed on the three standard Xamarin and one new Xamarin targets, but may be needed on Xamarin.Mac or WPF.


3.       PCL profiles in the CSPROJ files need to be updated.


4.       We need an additional FormsPresenter for the new Xamarin target.

OK so what I think would be the best way forward right now is that I fork MvvMCross and Mvx.FormsPresenters and also create a NuSpec package that has a different name. However we need to do some long term planning on how things should evolve going forward. In my view this exercise should ultimately merge back into the Origin via a pull request, it could even form the basis for MvvMCross4. For that to happen I would need your guidance along the way so that the transition is a smooth one. By the way, it would also be helpful in FormsPresenters merged into this root as well but I will have to think of some way to compensate Tomasz for that.

As for the NuSpec source, I can dig deeper into that if you want, it could prove useful later, especially after it completes its move to GitHub as it will become a lot easier to make changes to NuSpec like adding new ProjectTypeGuids and install rules for new project types.

Best

Peter Burke

**Comment by martijn00** [comment] 2015-06-29 08:20
@PeterBurke It seems you did a extensive investigation on the current structure, and have some good idea's for improvements. I think it indeed would be good that you make a PR for those changes. One thing i am wondering i we should start a new sub-repo for the forms stuff and add it as an official MvvmCross project, just like we did with [MvvmCross-AndroidSupport](https://github.com/MvvmCross/MvvmCross-AndroidSupport)

What does @Cheesebaron think about that?

**Comment by Cheesebaron** [comment] 2015-06-29 08:38
I haven't read the wall of text yet. But cleaning up the NuGet's would be very nice.

**Comment by martijn00** [comment] 2015-06-29 08:49
@Cheesebaron Yea, it's a bit of a read, but what i was referring to for you is, what do you think of creating a repo for Forms just like we did with Android-Support?

**Comment by PeterBurke** [comment] 2015-06-29 08:55
Thanks for your interest Martijn.

Tomasz Cielecki [notifications@github.com] just replied: "I haven't read the wall of text yet. But cleaning up the NuGet's would be very nice."

OK so a sub-repo is forked from the Hot Tuna origin. I already did that for the CheeseBaron contribution, but I am only really touching FormsPresenters and its Example, CheeseBarron has an excellent set of additional plug-ins as well and I might even get to use some of them in my educational "how to put it together" VS templates exercise.

But now I find that the Hot tuna stuff has similar issues too. So now I would need to fork that as well.

I could open access to these forks if there are more than myself who need to update them, and later when I don't want to be the owner any more get it back into the origin.

But ultimately there has to be some kind of reorganisation to be able to support both c# and xaml, plus I would like it to evolve into something distinct.

Best Peter

**Comment by martijn00** [comment] 2015-06-29 09:07
I would prefer to have all fixes merged back into origin so everyone can profit from it. If you make the changes to support both Xaml and C#, and the nuget changes i would be happy to test and review them so they can be merged back into origin.

**Comment by Cheesebaron** [comment] 2015-06-29 10:58
[**@martijn00**](https://github.com/martijn00) commented on [Jun 29, 2015, 10:49 AM GMT+2](https://github.com/MvvmCross/MvvmCross/issues/1001#issuecomment-116530875 "2015-06-29T08:49:47Z - Replied by Github Comment Enhancer"):
> @Cheesebaron Yea, it's a bit of a read, but what i was referring to for you is, what do you think of creating a repo for Forms just like we did with Android-Support?

It could be done. The FormsPresenters repo @PeterBurke is referring to is the one in my MvxPlugins repo. Whether or not to keep it there, I don't really care.

**Comment by PeterBurke** [comment] 2015-06-29 12:01
OK So we have these issues:


1.       Hot Tuna + Forms Presenters - PCL projects meed to target PCL Profile 259. This should not impact existing users because it does not remove targets, just adds  new targets: Windows 8, Windows Phone 8.1 (no silverlight)


2.       Hot Tuna + Forms Presenters - NuSpec both add content that is inappropriate in a XAML based solution, but these must remain for existing users. So I need to create another NuSpec that packages things differently. It should have a meaningful name, e.g. mvvmcross for xaml, likewise Mvx Forms Presenters for xaml, while I am developing this NuSpec I need to be the owner, but can surrender the Name when the pull back to origin occurs.


3.       Visual Studio 2015 RC incorporated a new version of Nuget and it does not like what it sees in MvvMCross. When installing / restoring NuGet packages we start with Mvx.FormsPresenters, this has a reference to MvvMCross.HotTuna.CrossCore. But the NuSpec for that has a reference to MvvmCross.Portable support that is in fact not needed by any of the targets in PCL Profile 259. Stuart suggests that it might no longer be required by any target. Its purpose would be to provide namespace functionality on a platform that is missing something. For example the MvvMCross WPF target is based on .NET 3.5. Now some time ago someone put a file "-.-" into the packages targeting Xamarin.iOS and Xamarin.Droid so that NuSpec would not complain about being directed via reference to an empty package. But now NuSpec is complaining again. We could actually get around this issue via separate NuSpecs for Xamarin.Forms one for C# and one for XAML. Of course these would not support WPF and Xamarin.MAC and that might disappoint some. Basically this problem will go away if someone can solve the "-.-" file problem, I have seen similar problems elsewhere, it is quite tedious to fix. Right now though I want to move forward on the other issues.

I actually like what Tomasz suggests having a new Repo that targets Xamarin.Forms both c# and xaml. Tomasz could the owner as long as I can update it in the early development stage. Getting it merged back into the origin should be a longer term objective but in the mean time it is open source you can pull changes that you need in the Origin when you need them and when you are ready, and yes thanks for the offer to review and test.

**Comment by martijn00** [comment] 2015-06-29 12:27
The repo is up now: https://github.com/MvvmCross/MvvmCross-Forms
I'll start by adding the current code of @Cheesebaron to the repo, and make some name changes. After that we need the nuspecs so we can put out a new release which contains the Forms stuff.

**Comment by Cheesebaron** [comment] 2015-06-29 12:32
I have nuspecs for the FormsPresenters stuff already, you should be able to just modify those.

**Comment by martijn00** [comment] 2015-06-29 13:16
My proposal as structure would be:
> MvvmCross_Forms (Solution)
> > Presenter (Project folder)
> > > Cirrious.MvvmCross.Forms.Presenter.Core (Project)
> > > Cirrious.MvvmCross.Forms.Presenter.Droid (Project)
> > > Cirrious.MvvmCross.Forms.Presenter.Touch (Project)
> > > Cirrious.MvvmCross.Forms.Presenter.WindowsPhone (Project)
> > > Cirrious.MvvmCross.Forms.Presenter.WindowsStore (Project)

Agree on that @Cheesebaron and @PeterBurke ?

**Comment by martijn00** [comment] 2015-06-30 08:16
PR is online: https://github.com/MvvmCross/MvvmCross-Forms/pull/1

**Comment by martijn00** [comment] 2015-06-30 10:54
@PeterBurke The initial version for Forms is up! You can make a PR now to fix the stuff you want.

**Comment by PeterBurke** [comment] 2015-06-30 10:58
Thanks so much Martijn

About to go to sleep 😉 will look at it and prepare a list to do on the morning.

Sent from my Windows Phone
________________________________

**Comment by jbeckton** [comment] 2015-07-06 02:37
I too am trying to resolve this issue. I just started looking at Xamarin a week ago so I have the latest versions. The Droid UI project I just created uses the Mono Android DLL not the Xamarin.Android DLL. As far as MvvmCross goes there are dozens of nuget packages out there and it's really hard to figure out which ones to use, any plans to clean that up?

**Comment by PeterBurke** [comment] 2015-07-06 03:36
Hi, this thread is quite long now, so it is difficult to know what problem you are also having. But it sounds like your problem is in fact that you have selected an obsolete NuGet package. MvvMCross no longer supports Mono Android and requires Xamarin Android.

Nuget packages contain references that tell Nuget what additional packages to restore. So if you are creating a PCL based Android solution from first principals you should start by selecting each project in turn, then "manage NuGet Packages" search installed packages then uninstall MvvMCross packages one by one.

Next search MvvMCross and install MvvMCross, this will install all the packages you need.

Example in the Android project you should see these packages: MvvMCross, MvvMCross.HotTuna.CrossCore MvvMCross.HotTuna.CrossLibraries, MvvMCross.HotTuna.StarterPack, MvvMCross.MobileSupport

Note however that ***rubenvb  commented 24 days ago*** and was the first to raise an issue that started with Visual Studio 2015 RC due to a tightening up in the NuSpec causing an exception to be thrown when NuSpec is told to link in a package and finds no content there. The reference to Mono.Android instead of Xamarin.Android pops out of NuSpec and of course is very confusing but the issue has nothing to do with Mono vs. Xamarin. In NuSpec they are the same!

He then posted a workaround: ***See http://stackoverflow.com/q/30148092 for a workaround.***

It seems that MvvMCross.MobileSupport is not really needed except by the MvvMCross WPF Target as it is .NET3.5 and is missing things. Currently for other platforms the NuSpec loads an empty package but that is no longer allowed. I have this issue on my list to fix and raise PR but it is lower down on my to do list.

**Comment by Cheesebaron** [comment] 2015-07-06 15:33
If you want a nuget cleanup, please open a new issue, where we figure out which exact packages need to either be removed or rebuilt etc.

**Comment by PeterBurke** [comment] 2015-07-07 01:41
See https://github.com/MvvmCross/MvvmCross/issues/1053 for recommended cleanup.

I do have plans to raise additional issues in relation to content both in MvvmCross.HotTuna.CrossCore and also MvvMCross.Forms NuSpecs. But these are unrelated unrelated to issue #1001 this issue.

**Comment by markmadlangbayan** [comment] 2015-07-24 03:47
FYI, this is still an issue with VS 2015 RTM (14.0.23107.0 D14 REL) and MvvmCross.HotTuna.MvvmCrossLibraries 3.5.1.  (As noted above, installing the package from VS 2013 worked as an interim solution.)

**Comment by matthewmauger** [comment] 2015-07-24 11:44
I'm still having the same problem with Xamarin Studio. I cannot install the MVVMCross nuget packages on any target version of Android other than 4.0.1, otherwise I get the error:

Could not install package MvvmCross.PortableSupport 3.5.1'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v4.4'

Unfortunately the Xamarin Google Play Services packages don't install with a target framework of 4.0.1, and I need both.

I note that Peter Burke has done a pull request that removes this dependency and thus resolves this issue. What is the easiest way for me to resolve this issue - will I need to build the MVVMCross source code and manually copy across the assemblies?

Matthew

**Comment by martijn00** [comment] 2015-07-24 11:48
The pull request of @PeterBurke is already merged in, so you could try to install the MvvmCross 4.0.0 Alpha9

**Comment by matthewmauger** [comment] 2015-07-24 13:20
Thanks Martijn! I found the Alpha packages in nuget and they have mostly
installed well, except for the json package which introduces an issue where
Json.net 7.0.1 doesn't want to target Android. Chasing that through then
fingers crossed that everything works!

**Comment by Cheesebaron** [comment] 2015-07-24 13:29
Json.net works fine on Android targets. Make sure you have a NuGet package manager version which understands that.

**Comment by matthewmauger** [comment] 2015-07-24 20:03
Thanks Cheesebaron - I needed to install Visual Studio 2013 then repair my Xamarin installation.

https://forums.xamarin.com/discussion/44770/problem-installing-json-net-in-visual-studio-2013

**Comment by matthewmauger** [comment] 2015-07-24 20:30
In addition to the Cheesebaron and Martijn I'd just like to say a HUGE thank you to Peter Burke for taking the time to get to the bottom of this! I was in debugging hell for a week trying to figure out how to bring my old Android 2.3.3 MvvmCross v1 project up to Android 4.0.3 MvvmCross v3 and this was the last fix that has made it possible. At least I can write code and stop fighting the tools...

**Closed** 2015-08-09 17:56 UTC

**Comment by imanabidi** [comment] 2016-09-29 09:57
1- with Nuget Package Explorer 3.18 installed

2- right click lib library and add  **Mono** Folder

![2016-09-29_13-25-49](https://cloud.githubusercontent.com/assets/1475559/18949459/561d7c2c-8648-11e6-8a23-4ba01ab96b68.png)

3- save and publish

**Comment by Cheesebaron** [comment] 2016-09-29 09:59
@imanabidi how is this relevant today?

**Comment by imanabidi** [comment] 2016-09-29 14:50
@Cheesebaron , I end up here after searching for my issue regarding targeting Mono 6. i thought i should be somehow irrelevant to this exact topic.

but  this was the solution that helped me and if you think this is not welcome here and cannot help somebody, can be deleted safely.
