### ISSUE TITLE
Update nuspecs to support new Nuget configuration

### ISSUE THREAD

**Issue by martijn00** [MvvmCross/MvvmCross#1082] opened 2015-07-29 09:02 UTC
As explained here: http://www.mikeobrien.net/blog/writing-a-nuget-package-for-vs2015-rtm-and-uwp/

We should configure the dependencies so that MvvmCross will install correctly.
Also it is no longer possible to add files or code to the project, so we probably need to write some stuff so it is clear what to do to get running.

```xml
<?xml version="1.0"?>
<package>
<metadata>
   <id>SampleNuGetPackage</id>
   <version>1.0.0.2</version>
   <title>Sample NuGet Package</title>
   <authors>Lucian Wischik</authors>
   <owners>Lucian Wischik</owners>
   <requireLicenseAcceptance>false</requireLicenseAcceptance>
   <description>This is a demo portable .NET class library</description>
   <summary>It is referencable by all >=.NET45 clients, including WindowsStore and Phone</summary>
   <dependencies>
     <group targetFramework ="net">
       <dependency id="Newtonsoft.Json" version="7.0.1" />
     </group>
     <group targetFramework ="win">
       <dependency id="Newtonsoft.Json" version="7.0.1" />
     </group>
     <group targetFramework ="wp">
       <dependency id="Newtonsoft.Json" version="7.0.1" />
     </group>
     <group targetFramework ="wpa">
       <dependency id="Newtonsoft.Json" version="7.0.1" />
     </group>
     <group targetFramework ="MonoAndroid">
       <dependency id="Newtonsoft.Json" version="7.0.1" />
     </group>
     <group targetFramework ="MonoTouch">
       <dependency id="Newtonsoft.Json" version="7.0.1" />
     </group>
     <group targetFramework ="Xamarin.iOS">
       <dependency id="Newtonsoft.Json" version="7.0.1" />
     </group>
     <group targetFramework ="portable-net45+win8+wpa81+wp8">
       <dependency id="Newtonsoft.Json" version="7.0.1" />
     </group>
     <group targetFramework ="uap">
       <dependency id="Newtonsoft.Json" version="7.0.1" />
       <dependency id="System.Runtime" version="4.0.0"/>
       <dependency id="System.Resources.ResourceManager" version="4.0.0"/>
       <dependency id="System.Collections" version="4.0.0"/>
       <dependency id="System.Linq" version="4.0.0"/>
     </group>
     <group targetFramework ="dotnet">
       <dependency id="Newtonsoft.Json" version="7.0.1" />
       <dependency id="System.Runtime" version="4.0.0"/>
       <dependency id="System.Resources.ResourceManager" version="4.0.0"/>
       <dependency id="System.Collections" version="4.0.0"/>
       <dependency id="System.Linq" version="4.0.0"/>
     </group>
   </dependencies>
</metadata>
</package>
```

**Comment by martijn00** [comment] 2015-07-30 09:11
Some readings about it.
* http://www.mikeobrien.net/blog/writing-a-nuget-package-for-vs2015-rtm-and-uwp/
* http://oren.codes/2015/07/29/targeting-net-core/
* http://oren.codes/2015/06/16/demystifying-pcls-net-core-dnx-and-uwp-redux/

@PeterBurke you did some nuspec work in MvvmCross. Do you have any idea's how we could fix this?

**Comment by PeterBurke** [comment] 2015-07-30 10:03
I am not sure what the issue is.

The MvvmCross-Forms projects for both Xamarin.iOS and Xamarin.Droid when compiled came up with warnings about incompatible .NET Framework assemblies. These assemblies are not referenced via NuGet but via Reference assemblies on the build machine. The build output:

```
2>  Consider app.config remapping of assembly
    "System.Runtime, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"
	from Version "1.5.11.0" [] to Version "4.0.0.0"
	[C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\Xamarin.iOS\v1.0\Facades\System.Runtime.dll]
	to solve conflict and get rid of warning.
	
2>  Consider app.config remapping of assembly 
    "System.IO, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" 
	from Version "1.5.11.0" [] to Version "4.0.0.0" 
	[C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\Xamarin.iOS\v1.0\Facades\System.IO.dll] 
	to solve conflict and get rid of warning.
	
2>  Consider app.config remapping of assembly
    "System.Net.Primitives, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"
	from Version "3.9.0.0" [] to Version "4.0.0.0"
	[C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\Xamarin.iOS\v1.0\Facades\System.Net.Primitives.dll]
	to solve conflict and get rid of warning.
	
2>  Consider app.config remapping of assembly
    "System.Net.Requests, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"
	from Version "3.9.0.0" [] to Version "4.0.0.0"
	[C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\Xamarin.iOS\v1.0\Facades\System.Net.Requests.dll]
	to solve conflict and get rid of warning.
	
2>  Consider app.config remapping of assembly
    "System.Net.Http, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"
	from Version "1.5.0.0"
	[\\PETERSSURFACE\VSProjects\MvvMCrossGroup\MvvmCross-Forms\Samples\Example002CSharp\Example\bin\Debug\System.Net.Http.dll]
	to Version "4.0.0.0"
	[C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\MonoAndroid\v1.0\System.Net.Http.dll]
	to solve conflict and get rid of warning.
	
2>  Consider app.config remapping of assembly
    "System.Threading.Tasks, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"
	from Version "1.5.11.0" [] to Version "4.0.0.0"
	[C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\Xamarin.iOS\v1.0\Facades\System.Threading.Tasks.dll]
	to solve conflict and get rid of warning.
	
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1712,3): 
    warning MSB3247: Found conflicts between different versions of the same dependent assembly.
	In Visual Studio, double-click this warning (or select it and press Enter) to fix the conflicts;
	otherwise, add the following binding redirects to the "runtime" node in the application configuration file:
  <runtime>
     <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
        <dependentAssembly>
           <assemblyIdentity name="System.Runtime" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" />
           <bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" />
        </dependentAssembly>
     </assemblyBinding>
     <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
        <dependentAssembly>
           <assemblyIdentity name="System.IO" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" />
           <bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" />
        </dependentAssembly>
     </assemblyBinding>
     <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
        <dependentAssembly>
           <assemblyIdentity name="System.Net.Primitives" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" />
           <bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" />
        </dependentAssembly>
     </assemblyBinding>
     <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
        <dependentAssembly>
           <assemblyIdentity name="System.Net.Requests" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" />
           <bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" />
        </dependentAssembly>
     </assemblyBinding>
     <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
        <dependentAssembly>
           <assemblyIdentity name="System.Net.Http" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" />
           <bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" />
        </dependentAssembly>
     </assemblyBinding>
     <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
        <dependentAssembly>
           <assemblyIdentity name="System.Threading.Tasks" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" />
           <bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" />
        </dependentAssembly>
     </assemblyBinding>
  </runtime>
``` 

Where do the dependencies on Version "1.5.11.0" assemblies come from? They are not in the project file and so they must be dependencies in NuGet references. This does not tell you which NeGet assemblies have these references though so it would be a tedious process of investigation finding them.

Note: previously we were getting errors compiling under VS 2013 that could be fixed by adding the reference to the equivalent .NET Framework Façade DLL in directory:
C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\Xamarin.iOS\v1.0\Facades\
These facades do not in fact contain any coding, just assembly redirects and the purpose seems to be that the project output in CIL does not need them on the build box, and Xamarin provide native equivalents in the install environment. That is why I made the projects reference these facades.

But that does not solve the problem of the Version "1.5.11.0" / "3.9.0.0" references. Despite having set up the App.config as suggested the warning does not go away.

I will investigate these issues further and check the readings you provided.

**Comment by martijn00** [comment] 2015-07-31 09:56
First proposal is in: https://github.com/MvvmCross/MvvmCross/pull/1084
We should still go over all projects and add the references they use to the "dotnet" and "uap" sections

**Comment by martijn00** [comment] 2015-08-09 13:58
Added section for "dotnet" files in: https://github.com/MvvmCross/MvvmCross/pull/1089
Dependencies for dotnet should still be fixed.

**Comment by martijn00** [comment] 2015-09-20 13:32
Tried to install @onovotny [ReferenceGenerator](https://github.com/onovotny/ReferenceGenerator), but i can't get it to work.

**Comment by onovotny** [comment] 2015-09-20 14:17
What's the error you're getting?

**Comment by martijn00** [comment] 2015-09-20 14:57
Nothing really. After adding the nuget and building no nuspecs are added. So i thought i might need to change the path and some settings, but that didn't help either.

**Comment by onovotny** [comment] 2015-09-20 15:01
Is there a branch I can look at? I need a bit more to go on than that :)

What project did you add it to? Where is the nuspec and do the names match? The default conventions assume there's a nuspec underneath the sln root that has the same name as the project you've added it to. If they don't match, the properties can be set to specify it.

The thing that helps is to do a detailed level build log and see the conditions in the `UpdateNuspecDependencies` target. It verifies 

`Condition=" @(NuSpecFile) != '' and $(NuSpecTfm) != '' and @(NuSpecLibContent) != '' and @(NuSpecProjectFile) != ''" `

**Comment by martijn00** [comment] 2015-09-20 15:05
There is not a specific branch where this is, the current one is here: https://github.com/MvvmCross/MvvmCross/tree/4.0/nuspec

I am based on that installing the ReferenceGenerator for all projects.

The nuget fixes need to go into the plugins as well i think: https://github.com/MvvmCross/MvvmCross-Plugins/tree/master/nuspec

I'll try to get a detailed log now.

**Comment by onovotny** [comment] 2015-09-20 15:08
Do all of the projects target dotnet/UWP (the PCL projects or UWP-specific ones)?  Just the ones that do, should have it. If there are some that are just for android/ios/down-level platforms, they don't need the tool as there's nothing to add.

**Comment by martijn00** [comment] 2015-09-20 15:22
No not all of them. Most plugins contain 1 PCL and 1 UWP (or WindowsCommon) project. The main repo has several PCL projects too.

**Comment by Cheesebaron** [comment] 2015-09-21 18:04
WindowsCommon as in WPA8.1+WP8.1

**Comment by lothrop** [comment] 2016-01-04 06:28
Is there anything still to do here?

**Comment by martijn00** [comment] 2016-01-04 08:16
I think we have only one official UWP project, and for that one the dependencies are now defined. I am wondering if we should make the WindowsCommon projects UWP specific too...

**Comment by lothrop** [comment] 2016-01-05 20:15
@martijn00 Can we then not have content files for UWP? It's the only platform without.

**Comment by martijn00** [comment] 2016-01-05 21:31
@lothrop what do you mean with that?

**Comment by onovotny** [comment] 2016-01-05 21:35
You can have content files now but long as they're read-only. It was part of NuGet 3.3.

http://docs.nuget.org/Create/NuSpec-Reference#contentfiles-with-visual-studio-2015-update-1-and-later

The idea is that those files are immutable but will be included in the project at build time. There's another task to have content that's user-editable.

**Closed** 2016-02-05 13:44 UTC
Labels: Needs investigation, up-for-grabs
