### ISSUE TITLE
Add the ability to only use one instance of a given fragment

### ISSUE THREAD

**Issue by tbalcom** [MvvmCross/MvvmCross#2694] opened 2018-03-16 15:58 UTC
It would be great if the `MvxFragmentPresentation` attribute had a flag to tell the presenter to only allow one instance of the fragment at a time. An example scenario where this feature would be useful:

1. A `HomeViewModel` is navigated to when the program starts.
2. The user opens the hamburger menu and clicks the Home item to display `HomeViewModel`.
3. Now there are two instances of the `HomeViewModel` when it would be desirable to only have the one instance active at a time.

### Configuration :wrench:

**Version:** 6.x

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment] 2018-03-21 06:46
Duplicate of https://github.com/MvvmCross/MvvmCross/issues/2707

**Closed by martijn00** 2018-03-21 06:46 UTC
