### ISSUE TITLE
Forms: TargetInvocationException when using ShowViewModel with parameter

### ISSUE THREAD

**Issue by Sebastian1989101** [MvvmCross/MvvmCross#2363] opened 2017-11-07 21:30 UTC
### Steps to reproduce :scroll:

1. Just use ShowViewModel<VMType, string>("qq"); and it will crash with an TargetInvocationException...

### Expected behavior :thinking:
Maybe it should work to parse a parameter to another ViewModel like in any other version before?

### Actual behavior :bug:
TargetInvocationException is thrown.

### Configuration :wrench:

**Version:** 5.4.2

**Platform:** 
- [x] :iphone: iOS - only tested within a Forms project
- [x] :robot: Android - only tested within a Forms project
- [ ] :checkered_flag: WPF - not tested
- [ ] :earth_americas: UWP - not tested
- [ ] :apple: MacOS - not tested
- [ ] :tv: tvOS - not tested
- [x] :monkey: Xamarin.Forms

-----
 
Is it allowed to ask a question? I only hear good stuff from using MvvmCross but I never created native Apps with Xamarin yet. I use MvvmCross since it adds the support for Xamarin.Forms but I have no good experience with it yet. Always so much stuff bugged, not working or not working as expected. Are the "RC"-Versions actual tested before releasing them? It feels like it goes live without any tests all the time because 90% of the bugs I encounter so far would be easy eliminated with UnitTests.

**Comment by martijn00** [comment] 2017-11-08 00:16
I've made a fix for this regression. There are a couple of things why this might feel a bit off. ShowViewModel is deprecated for a couple of releases now and this works with the NavigationService. Also Native Xamarin exists a lot longer then Forms, and since Forms is an abstraction it brings its own problems on top of everything else.

We would love to have more unit-tests and this is something you and anyone else could actively contribute in! We would be happy to see those PR's coming!

**Comment by Sebastian1989101** [comment] 2017-11-08 20:57
If ShowViewModel is deprecated should it not have the ObsoleteAttribute? I mean how should the user of your framework otherwise know if this is "the old way"?

**Closed** 2017-11-10 10:54 UTC
