### ISSUE TITLE
rendering issue with dynamic sized UILabels using Constraints

### ISSUE THREAD

**Issue by aaronlab** [MvvmCross/MvvmCross#1468] opened 2016-10-18 16:10 UTC
Creating cells in iOS where UILabel have automatic calculating height does not update height calculation when dequeuing cells.  This functionality used to work properly in MvvmCross 3.5.2 - broke in MvvmCross 4.2.3.  

1.)  Create a Cell with a UILabel in it.

2.)  Set the properties on the label to:
      Lines = 0,
      LineBreakMode = UILineBreakMode.WordWrap

3.)  On the UITableView set the row height to dynamic:
TableView.RowHeight = UITableView.AutomaticDimension; 

4.)  Set NSLayoutContraints properly in the UITableViewCell.

5.)  Have sample data of various length of text for the label.

When this bug happens the dequeuing of the cell and the delay binding doesn't happen within the lifecycle properly and the constraints aren't adjusted for the new text value size so you will either have too much space allocated for the text (the cell draws with the height not adjusted) or you get text cut off. 

I have created a video to explain the bug in detail along with showing the issue at hand:
https://1drv.ms/v/s!AvHqnmN_ypIXgc5sqVI5iW0faUOnzQ

An example project can be found at:
https://github.com/aaronlab/Xamarin-MvvmCross-iOS-Multiline-Sample

The work around we have created involves removing and re-adding in all bindings when the cell is returned from the dequeuing process - how ever this has other rendering issues when you hide and show cells dynamically, which we do in our production app that is plagued with this issue.  Again all this worked in MvvmCross 3.5.2 without issues.

-Aaron

**Comment by Cheesebaron** [comment] 2016-10-18 16:11
Possible dupe of #1423

Could you check if solution in the associated PR fixes cells for you?

**Comment by aaronlab** [comment] 2016-10-18 16:39
@Cheesebaron - I can confirm that this is the same issue I'm seeing and the proposed solution should fix the issue.

**Comment by promontis** [comment] 2016-11-01 11:45
@aaronlab if fixed could you close this issue?

**Closed** 2016-12-06 16:41 UTC
