### ISSUE TITLE
Lets track upgrading to MvvmCross 8 issues here

### ISSUE THREAD

**Issue by Cheesebaron** [MvvmCross/MvvmCross#4201] opened 2021-06-14 21:41 UTC
## 📃 Documentation

Please add your documentation issues upgrading to MvvmCross 8, here in this thread. This way we can keep track of everything needed and add it to the documentation as need.

- [x] #4199 undocumented changes needed to create a Setup.cs file

**Comment by EricEzaM** [comment] 2021-06-21 03:30
Hello,

I had a lot of trouble with getting my WPF views to work after upgrading from 7.1.2. 
Finally I found this: https://github.com/MvvmCross/MvvmCross-Samples/pull/159/files#diff-6e3eaf2bf0784ad72aa337c2e02e25023abb1fa10b0371fdcb5431c3af0ad679

Which seemed to indicate that I need to add the below attributes to get it to work. After adding `[MvxContentPresentation]` my view finally appeared in my main window.
```csharp
[MvxContentPresentation]
[MvxViewFor(typeof(TipViewModel))]
```

**Comment by Cheesebaron** [comment] 2021-06-21 07:57
@EricEzaM I am not sure if it is a new issue I introduced making 8.x, but I noticed I needed that attribute. I will create a new issue for this and link here. Also document the workaround. Thanks!

**Comment by stephannn** [comment] 2021-06-21 18:16
@EricEzaM,
In my case I had to add [MvxContentPresentation] to get my main app windows working again.

Besides, when I try to call a second window with:
new MvxAsyncCommand(async () => await NavigationService.Navigate<TestViewModel>());
I receive the error: [20:04:19 VRB] PresentationAttribute not found for TestView. Assuming window presentation

**Comment by bradykelly** [comment] 2021-06-21 22:05
I am stuck creating my own `Setup` class for logging. The help shows a setup class derived from `MvxAndroidSetup<App>`, but when I change this to `MvxWpfSetup<App>` , the compiler complains:

> The non-generic type 'MvxWpfSetup' cannot be used with type arguments

**Comment by follesoe** [comment] 2021-06-26 10:25
My MvxTabBarViewController no longer works/displays the tabs as expected. No code change beyond upgrading from MvvmCross 7.0.1 to 8.0.1. Debugging it now.

**Comment by follesoe** [comment] 2021-06-27 15:18
I see that `MvvmCross.Plugin.File` is not upgraded and is still only available as 7.0.1, causing a build error due to conflicting references to MvvmCross

**Comment by tommyzzj** [comment] 2021-07-14 07:12
Hi,

I'm trying to update my Xamarin.Droid application from 6.2.1 to 8.0.1.   Heading lots of errors and there's no document for 6 to 7.
Most of those errors are about `InitializeFirstChance`, `IMvxLogProvider` and `MvxNavigationService`.

Is there any sample code or solution for that?

**Comment by alyxal** [comment] 2021-07-15 15:20
Hi,

Upgrading from 7 to 8, there's an issue with the `MvxDialogFragmentPresentationAttribute` fro; the Android View Presenter. The property `Cancelable` is no longer at `true` by default, although it is specified by the docs here : https://www.mvvmcross.com/documentation/platform/android/android-view-presenter#mvxdialogfragmentpresentationattribute

I don't know if it's a bug or wanted behaviour, but it is not written anywhere in the migration docs.
So if you want to migrate to MvvmCross 8 and you have cancelable fragments using `MvxDialogFragmentPresentationAttribute`, you have to replace it by `[MvxDialogFragmentPresentation(Cancelable = true)]`

**Comment by Cheesebaron** [comment] 2021-07-20 07:22
View <-> ViewModel associations have nothing to do with the presenter.

Do you have your Views in a different assembly?
Do you have your ViewModels in a different assembly?

If any of these, did you ensure the assembly is loaded for consideration in your Setup file?

**Comment by IainS1986** [comment] 2021-07-20 07:57
So my project setup is just the usual Project.Core, Project.Droid and Project.iOS

Like I say, everything has been working fine, just this upgrade has knocked it out of whack. 

Views in Porject.Droid and VMs in Project.Core.

Assumed it was presenter related as it takes the view assemblies as an argument.

So my Setup doesn't do any assembly loading - does tipcalc or somewhere have an example of what you mean?

**Comment by Cheesebaron** [comment] 2021-07-20 08:29
It could actually be something else triggering this exception, can you enable all exceptions and run your App? It might be something else not loading messing up the startup process.

**Comment by IainS1986** [comment] 2021-07-20 08:32
Will do!

Just fyi, I tried overriding InitializeLookupDictionary(IMvxIoCProvider iocProvider) in my setup. When I step over the base call it doesn't continue to the next line so somethings throwing a wobbly.

![Screenshot 2021-07-20 at 09 31 44](https://user-images.githubusercontent.com/16193452/126288641-3940071f-b911-4bca-bd0e-cafd012efa22.png)

**Comment by IainS1986** [comment] 2021-07-20 08:36
Ok so yes, errors are throwing.

Its saying 'An item with the same key has already been added. Key: XXX.Core.ViewModels.OnBoarding.SelectMeasuringUnitViewModel'

So, i've looked and theres only one fragment in my Droid project with that (again, not changed anything around it either in the upgrade changes from 7->8)

Interestingly, when I inspect ViewAssemblies in the Setup, my Droid DLL is listed twice?

![Screenshot 2021-07-20 at 09 35 21](https://user-images.githubusercontent.com/16193452/126289244-bfe84a80-8519-4a46-b35e-c8a027fc0367.png)

**Comment by IainS1986** [comment] 2021-07-20 08:42
Interesting one with SplashActivity too?
![Screenshot 2021-07-20 at 09 41 23](https://user-images.githubusercontent.com/16193452/126290090-0456219e-018b-4520-a8bb-571306a41d92.png)

**Comment by IainS1986** [comment] 2021-07-20 08:52
Ok so I went back to my branch from before the upgrade.

That exception in SplashActivity is thrown in 7.X too so can likely ignore.

However my ViewAssemblies correctly only contains 1 instance of my Droid DLL, so InitializeLookupDictionary() works fine (and finds 55 mappings).

So somewhere in 8.X my apps now adding in the Droid assembly twice.

**Comment by IainS1986** [comment] 2021-07-20 09:16
Resolved it!

Before in 7.X the ViewAssemblies in Setup would generally just get set to whatever is passed in, but now its a collection thats added too and combined.

I was wrongly registering the Setup twice essentially.

I have a MainApplication class with the following signature

`public class MainApplication : MvxAndroidApplication<Setup, App>`

But I also have a SplashActivity with the following signature

`public class SplashActivity : MvxSplashScreenActivity<Setup, App>`



In 7.X the ViewAssemblies would be loaded in MainApplication, then loaded again in SplashActivity but it would simply override. In 8.X they now combine.

Fixed by changing SplashActivity to simply

`public class SplashActivity : MvxSplashScreenActivity`

**Comment by pwisk** [comment] 2021-07-23 10:03
After upgrading from 7.1.2 to 8.0.1 I have problem witch **MvxMasterDetailPagePresentation** and HamburgerMenu. Structure is made as here: https://stackoverflow.com/questions/48980485/how-to-create-a-masterdetailpage-using-mvvmcross

MenuPage and MenuViewModel are called on app initialization.
ViewAppearing for MenuViewModel isn't called.

Detail page is loading fine. When i call MenuPage as Detail, not Master it also loads fine. For Master option area is always blank.

Root page also reauires change **MasterBehavior** to **FlyoutLayoutBehavior**.

There are no errors during debug. Master just doesn't load even if navidation service call the model and page.

**Comment by IvoKrugers** [comment] 2021-08-16 14:40
Value Type return values (TResult) in modal ViewModels are not allowed anymore in MvvmCross 8. 
Is wrapping them in a class the only way to fix this?

**Comment by Cheesebaron** [comment] 2021-08-17 10:23
@IvoKrugers for now yes. I was looking into removing the constraints here, but it just opened a big can of worms that I am not sure I want to handle right now.

**Comment by hubocan** [comment] 2021-08-21 13:04
> Interesting one with SplashActivity too?
> ![Screenshot 2021-07-20 at 09 41 23](https://user-images.githubusercontent.com/16193452/126290090-0456219e-018b-4520-a8bb-571306a41d92.png)

I have exactly the same exception. Is it normal that my "public class SplashScreen : MvxSplashScreenActivity" is looking for view model? I was thinking that it is the difference, that the MvxSplashScreenActivity have no view model and doesn't perform any binding.

**Comment by IainS1986** [comment] 2021-08-21 16:54
@hubocan not saying this is definitely the case but could be related to something I had issues with above, I see your SplashActivity registers the Setup and App classes, do you also have a MainApplication also registering those?

Before this error didn't cause any issues but now it can.

**Comment by IainS1986** [comment] 2021-08-21 17:00
I started replying @hubocan but not sure what your issue is. If it's related to what i said then I've given the solution above - don't register your Setup twice.

**Comment by hubocan** [comment] 2021-08-21 17:03
I have read your solution, but that is not my case as my splash screen is defined exactly like this:
```
    [Activity(Label = "@string/app_name", MainLauncher = true, NoHistory = true, Theme = "@style/AppTheme", ConfigurationChanges = ConfigChanges.Orientation | ConfigChanges.ScreenSize)]
    public class SplashScreen : MvxSplashScreenActivity
    {
    }
```
But still, I get the exact exception. (The image is just the quote of your comment.)

**Comment by IainS1986** [comment] 2021-08-21 17:25
Yeah, as I stated above I also saw that in 7.x too, but it gets caught and handled internally inside mvvm and doesn't cause any issues (for me at least). I only see it if I'm trying to break on all System.Exceptions

**Comment by hubocan** [comment] 2021-08-21 17:52
Exactly, but it seems like some legit internal issue.

**Comment by jooni91** [comment] 2021-08-31 13:09
> @IvoKrugers for now yes. I was looking into removing the constraints here, but it just opened a big can of worms that I am not sure I want to handle right now.

@Cheesebaron This should be marked as a breaking change. I am using value types as return types a lot in my applications. So is it worth the effort to create wrappers as a workaround solution or should I wait for constraint removal? What's the issue, anything the community can help with?

**Comment by Cheesebaron** [comment] 2021-08-31 13:30
As always PRs are welcome. People mainly come here to log issues, but never do anything else about it 🥲 So if you feel like you want and have time to fix it. Go ahead.

You can try removing the constraints yourself and see how far you get.

**Comment by IainS1986** [comment] 2021-09-01 08:08
@jooni91 It **is** marked as a breaking change at the top of the change log https://www.mvvmcross.com/mvvmcross-8.0.0-release/

Its not the most elegant but its not too tricky to just write wrappers for any value types you might use that previously you handled 'nulls' as a return (I did this by having 'null' being handled as if the user cancelled out of a process or hit back buttons/hardware back)

I had bools and some enums so a couple quick wrappers and its all sorted

```
// MvvmCross 8.0 made a restriction on IMvcViewModelResult TResult generic being of type class (reference type)
// So bool (and enums) can't be used! Bit of a pain. This is quite a hacky workaround for bool
public class BoolReference
{
    public bool Value { get; set; } = false;

    public BoolReference()
        => Value = false;

    public BoolReference(bool value)
        => Value = value;

    public static implicit operator BoolReference(bool val)
        => new BoolReference(val);

    public static bool operator true(BoolReference val) => val?.Value == true;

    public static bool operator false(BoolReference val) => val?.Value != true;
}

// MvvmCross 8.0 made a restriction on IMvcViewModelResult TResult generic being of type class (reference type)
// So bool (and enums) can't be used! Bit of a pain. This is quite a hacky workaround for wrapping the enum response
public class EnumReference<T> where T : Enum
{
    public T Value { get; set; } = default(T);
 
    public EnumReference()
        => Value = default(T);

    public EnumReference(T type)
        => Value = type;
}
```

**Comment by DavidH685** [comment] 2021-09-01 12:48
I've just upgraded to MvvmCross 8 and have also had problems with it not finding the views.

Thanks to the comment by IainS1986 pointing me in the right direction I can see that the ViewAssemblies list has my Android assembly listed twice. I don't have the setup registered twice and can't see anywhere else in my code that it's being added. 

The last log entry is "[MvvmCross.Core.MvxSetup] [Verbose] Setup: Lookup Dictionary start" so I added this to my Setup class:

        protected override IDictionary<Type, Type> InitializeLookupDictionary(IMvxIoCProvider iocProvider)
        {
            return base.InitializeLookupDictionary(iocProvider);
        }

since this method seems to be where it is failing and then got a new exception:

System.ArgumentException: 'An item with the same key has already been added. Key: ABCViewModel'

As a test I updated the method to make the ViewAssemblies list unique and it now finds the views:

        protected override IDictionary<Type, Type> InitializeLookupDictionary(IMvxIoCProvider iocProvider)
        {

            var viewAssemblies = ViewAssemblies.Distinct().ToList();
            ViewAssemblies.Clear();
            ViewAssemblies.AddRange(viewAssemblies);

            return base.InitializeLookupDictionary(iocProvider);
        }

Looking at the MvvmCross code the argument exception appears, at a guess, to be raised in the MvxTypeToTypeLookupBuilder.Build method if there are duplicate assemblies when it creates the dictionary.

I would prefer to fix this properly but I'm struggling to find a simple way to debug into MvvmCross to find where the assemblies are being added to the list. If anyone has any suggestions please let me know.

**Comment by hubocan** [comment] 2021-09-01 12:54
@DavidH685 I have the same problem, when I access Context in the MvxAndroidApplication<Setup, App> class.

**Comment by DavidH685** [comment] 2021-09-01 16:05
@hubocan OK. I'm glad you got it working.

**Comment by dubstepadii** [comment] 2021-09-07 14:12
After migration from 7.1.2 -> 8.0.2, did all things with logging, but faced `Failed resolution of: Androidx/core/view/OnReceiveContentViewBehavior;` error - in end update all **Xamarin.AndroidX** packages that are referenced to proj, that helped me to get Droid running.

**Comment by jbouche-work** [comment] 2021-09-21 15:27
> 
> 
> Resolved it!
> 
> Before in 7.X the ViewAssemblies in Setup would generally just get set to whatever is passed in, but now its a collection thats added too and combined.
> 
> I was wrongly registering the Setup twice essentially.
> 
> I have a MainApplication class with the following signature
> 
> `public class MainApplication : MvxAndroidApplication<Setup, App>`
> 
> But I also have a SplashActivity with the following signature
> 
> `public class SplashActivity : MvxSplashScreenActivity<Setup, App>`
> 
> In 7.X the ViewAssemblies would be loaded in MainApplication, then loaded again in SplashActivity but it would simply override. In 8.X they now combine.
> 
> Fixed by changing SplashActivity to simply
> 
> `public class SplashActivity : MvxSplashScreenActivity`

Thanks a lot for your return IainS1986, I had the same concern.

**Comment by DavidH685** [comment] 2022-05-27 10:41
@kriskoch Did you add the overrides listed above? Even though they don't do anything having them in my code showed other exceptions in the logs that didn't appear when they weren't there for me. In my case there were duplicates but even if that isn't the same in your case hopefully you'll get an exception that helps you find the cause.

**Comment by kriskoch** [comment] 2022-05-27 11:04
@DavidH685 yeah i do have those overrides. I put breakpoints and it hits the breakpoint but it's not where the exception is being thrown

**Comment by DavidH685** [comment] 2022-05-27 11:30
Sorry the only thing I can suggest is to look for the last MVVMCross log entry before your exception and hopefully that will help. You can search the MVVMCross code for that log message and that will tell you what was called after it.

**Comment by kriskoch** [comment] 2022-05-27 14:09
Oh mine was a really stupid mistake.
When I upgraded MVVMCross from 6.4 to 8 I forgot to remove the references to  old mvvmcross packages (MvvmCross.Droid.Support.V7.*).

After removing those , and looking at this page - https://www.mvvmcross.com/mvvmcross-7.0.0-release/
I got it to build navigate between controllers. My views all look like a mess, but at least I got this working.

**Closed** 2023-07-20 20:17 UTC
Labels: t/docs
