### ISSUE TITLE
Xamarin Forms Context seem incorrect in MvxFormsAndroidSetup.FormsApplication

### ISSUE THREAD

**Issue by Thetyne** [MvvmCross/MvvmCross#2832] opened 2018-04-25 08:53 UTC
After i update mvvcross 5.6 to 6.0, ZXing.Mobile.Forms crash.
I found the problem.
Inside ZXingScannerViewRenderer, it use deprecated Xamarin Forms Context.

Mvvmcross initialize Forms inside MvxFormsAndroidSetup.FormsApplication accessor.

```
if (!Xamarin.Forms.Forms.IsInitialized)
{
var activity = Mvx.Resolve<IMvxAndroidCurrentTopActivity>()?.Activity ?? ApplicationContext;
var asmb = activity.GetType().Assembly;
Xamarin.Forms.Forms.Init(activity, null, ViewAssemblies.FirstOrDefault() ?? asmb);               
}
```

Mvx.Resolve<IMvxAndroidCurrentTopActivity>()?.Activity is null, so Xamarin Forms Context is set with ApplicationContext. 
At this moment, Zxing fail to create Android.Views.SurfaceView

But when i recall Xamarin.Forms.Forms.Init(this, bundle); inside MainActivity.OnCreate. Xamarin Forms Context is set with MainActivity.
Now, Zxing can create Android.Views.SurfaceView.

My question:
Recall Xamarin.Forms.Forms.Init(this, bundle) renew set Context with the MainActivity Context.
So, What is the problem with ApplicationContext?

Maybe a bug due change #2777 

` Xamarin.Forms.Forms.Init(activity, null, activity.GetType().Assembly);`

changed to

```
var asmb = activity.GetType().Assembly;
Xamarin.Forms.Forms.Init(activity, null, ViewAssemblies.FirstOrDefault() ??asmb);
```

### Configuration :wrench:

**Version:** 6.0
Xamarin.Forms 2.5.1.444934.

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by Thetyne** [comment] 2018-04-25 08:57
Maybe a bug due change #2777

**Comment by nickrandolph** [comment] 2018-04-30 03:11
@Thetyne are you able to reproduce this using the Playground sample in the Mvvmcross source code (develop branch)? If you can, please submit a PR demonstrating this. We can help investigate to work out a fix.

**Comment by kciesiel** [comment] 2018-04-30 08:30
I have the same problem.
The `var asmb = activity.GetType().Assembly;
Xamarin.Forms.Forms.Init(activity, null, ViewAssemblies != null ? ViewAssemblies.FirstOrDefault() : asmb);`
fixed this problem, but after that I have just white screen without anything.

**Comment by nickrandolph** [comment] 2018-08-09 05:12
@Thetyne would you be able to retest this on v6.2?

**Comment by Thetyne** [comment] 2018-08-27 12:11
Sorry, it's my day off.

i can't test at the moment

**Comment by martijn00** [comment] 2019-05-13 17:43
The workaround for this seems to be sort of working. Closing this for now.

**Closed by martijn00** 2019-05-13 17:43 UTC
Labels: p/android, p/forms, t/bug

**Comment by zoli13** [comment] 2020-12-10 08:55
@martijn00 could you please provide the code for the workaround? I think you are referring to @kciesiel 2 lines code, but where to put it exactly?
