### ISSUE TITLE
How can we do IntuneMAM Activity inherit to MVX Activity

### ISSUE THREAD

**Issue by sureshbabu4** [MvvmCross/MvvmCross#3327] opened 2019-03-21 08:07 UTC
### Configuration

**Version:** 6.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment] 2019-03-21 13:40
Duplicate of #3328

**Closed by martijn00** 2019-03-21 13:40 UTC

**Comment by sureshbabu4** [comment] 2019-03-28 14:21
@martijn00,Thanks a lot for Good explaination
