### ISSUE TITLE
Java.Lang.IllegalStateException in Playgournd.Droid project

### ISSUE THREAD

**Issue by xufeipyxis** [MvvmCross/MvvmCross#3212] opened 2018-11-23 01:41 UTC
## 🐛 Bug Report
When I download the release/6.2.2 branch and run the playground.droid project, I have the exception of Java.Lang.IllegalStateException:

```
Java.Lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00089] in <0ad2222fd7074badb5de547b1521aab0>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0005d] in <0ad2222fd7074badb5de547b1521aab0>:0 
  at Android.App.Activity.SetContentView (Android.Views.View view) [0x00031] in <ad2f15102b3a4d36b40e9b0cbc11c376>:0 
  at MvvmCross.Droid.Support.V7.AppCompat.MvxSplashScreenAppCompatActivity.OnCreate (Android.OS.Bundle bundle) [0x0004c] in D:\github\MvvmCross\MvvmCross.Android.Support\V7.AppCompat\MvxSplashScreenAppCompatActivity.cs:59 
  at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x00011] in <ad2f15102b3a4d36b40e9b0cbc11c376>:0 
```
This line of code `var content = LayoutInflater.Inflate(_resourceId, null);` in 
```cs
        protected override void OnCreate(Bundle bundle)
        {
            RequestWindowFeatures();

            _bundle = bundle;

            var setup = MvxAndroidSetupSingleton.EnsureSingletonAvailable(ApplicationContext);
            setup.InitializeAndMonitor(this);

            base.OnCreate(bundle);

            if (_resourceId != NoContent)
            {
                // Set our view from the "splash" layout resource
                // Be careful to use non-binding inflation
                var content = LayoutInflater.Inflate(_resourceId, null);
                SetContentView(content);
            }
        }
```
seems to be suspecious but I can't figure it out.

I checked the styles.xml and the AppTheme.Splash is actually a descendant of Theme.AppCompat.
I did not change any code, just download and run.
```xml
<style name="AppTheme.Splash"
		parent="AppTheme.Base">
		<item name="android:statusBarColor">@color/colorPrimaryDark</item>
		<item name="android:windowNoTitle">true</item>
		<item name="android:windowBackground">@color/colorAccent</item>
	</style>

<style name="AppTheme.Base"
		parent="Theme.AppCompat.Light.NoActionBar">
</style>
```
### Expected behavior
playground.droid runs.
### Reproduction steps
download the release/6.2.2 branch and run the playground.droid project
### Configuration
release/6.2.2, no code change
VS2017, v15.9.2
**Version:** 6.x

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by tbalcom** [comment] 2019-02-04 22:01
That's the kind of error you would typically see if Xamarin bugs out. It's usually fixed by manually deleting the bin & obj folders then rebuilding the solution. I can't reproduce this issue with Visual Studio 2017 15.9.6, Xamarin 4.12.3.79, and Xamarin.Android 9.1.5.0.

I did notice MvvmCross.Forms & Playground.Droid.Forms both initially fail to build while using the Build Solution command.  I have to manually right click MvvmCross.Forms > Build once then the Build Solution command works without error. Seems like there is a timing or dependency issue there if building from inside Visual Studio?

> Error	MSB4018	MvvmCross.Forms	C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets	1327	The "ResolveLibraryProjectImports" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load assembly 'MvvmCross.Droid.Support.Design, Version=0.0.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'MvvmCross.Droid.Support.Design.dll'
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(String fullName)
   at Xamarin.Android.Tasks.ResolveLibraryProjectImports.Extract(DirectoryAssemblyResolver res, ICollection`1 jars, ICollection`1 resolvedResourceDirectories, ICollection`1 resolvedAssetDirectories, ICollection`1 resolvedEnvironments)
   at Xamarin.Android.Tasks.ResolveLibraryProjectImports.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	

> Error		Playground.Forms.Droid			Could not load assembly 'MvvmCross.Forms, Version=0.0.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   at Xamarin.Android.Tasks.GetAdditionalResourcesFromAssemblies.<>c__DisplayClass37_0.<DoExecute>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Closed** 2019-03-25 15:03 UTC
Labels: s/invalid
