### ISSUE TITLE
IMvxAndroidCurrentTopActivity.Activity is null when returning from permission request in Android

### ISSUE THREAD

**Issue by claudioredi** [MvvmCross/MvvmCross#3485] opened 2019-08-05 15:13 UTC
## 🐛 Bug Report

Method `OnRequestPermissionsResult` executes before `MvxApplicationCallbacksCurrentTopActivity` sets the current activity on method `OnResume`. Because of this, any operation requiring current activity inmediately after requesting a permission will fail.

I'm using the permissions plugin from Montemagno and have something like this

    var result = await permissions.RequestPermissionsAsync(new[] { Permission.Location });
    // Now I have logic requiring current activity to be set, since it is not, it fails

I implemented a workaround for now where I force current activity to be set on `OnRequestPermissionsResult` for `MvxApplicationCallbacksCurrentTopActivity`

### Expected behavior
This was working on mvvmcross 5.7.1, it started happening after migrating to mvvmcross 6.x

### Reproduction steps
Request a permission in Android and perform any operation on method `OnRequestPermissionsResult` requiring `IMvxAndroidCurrentTopActivity.Activity` to have something valid... since no activity is active, it will fail

### Configuration

**Version:** 6.3.1

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment] 2019-08-06 08:23
Duplicate of #3455

**Closed by Cheesebaron** 2019-08-06 08:23 UTC
