### ISSUE TITLE
ViewModel with return parameter broken after Upgrade

### ISSUE THREAD

**Issue by Sebastian1989101** [MvvmCross/MvvmCross#3577] opened 2019-09-25 21:54 UTC
## 🐛 Bug Report

After upgrading MVX from 6.1.2 to 6.3.x the navigation from ViewModels with return parameter is broken in the following case: ViewModel A to ViewModel B, then ViewModel B to ViewModel C (at this point, ViewModel A gets a _NULL_ reponse from ViewModel B which is wrong because B was never closed), next ViewModel C returns the value to B which trys to return it to A by calling the Close with itself + the parameter, now the crash happens because MVX closed it in the background already.

### Expected behavior

ViewModel B should not return a _NULL_ value if the close was not called. 

### Reproduction steps

See description above

### Configuration

**Version:** 6.3.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by softlion** [comment] 2019-10-03 15:23
duplicate of https://github.com/MvvmCross/MvvmCross/issues/3570 ?

**Closed** 2019-10-04 11:01 UTC
Labels: s/duplicate
