### ISSUE TITLE
Deadlock for some awaited calls in MvxViewModel.Initialize()

### ISSUE THREAD

**Issue by eriove** [MvvmCross/MvvmCross#3618] opened 2019-10-25 14:19 UTC
## 🐛 Bug Report

If `await base.Initialize()` is un-commented on line 206 in [RootViewModel.Initialize()](https://github.com/MvvmCross/MvvmCross/blob/develop/Projects/Playground/Playground.Core/ViewModels/RootViewModel.cs#L206) the WPF (Core and Framework) playground application dead locks/fails to start.

Since `MakeRequest()` doesn't dead lock it isn't as simple as all async methods dead-locking. I've observed the same behavior in a larger application as well.

Below is the tasks view and the parallel stack
![tasks](https://user-images.githubusercontent.com/9482927/67578566-fdd4e180-f742-11e9-8094-6be191cf770b.png)
![stacks](https://user-images.githubusercontent.com/9482927/67578616-1cd37380-f743-11e9-882c-a5038f470e93.png)

### Expected behavior
The application starts 

### Reproduction steps
Un-comment `await base.Initialize()` on line 206 in [RootViewModel.Initialize()](https://github.com/MvvmCross/MvvmCross/blob/develop/Projects/Playground/Playground.Core/ViewModels/RootViewModel.cs#L206) and run Playground.Wpf or Playground.WpfCore. The application never starts.

### Configuration
Windows 10 1809
Visual Studio 16.3.5

**Version:** 6.4.1 (commit [1ad188286503bebaf6f2630676db80ba630bc97e](https://github.com/MvvmCross/MvvmCross/commit/1ad188286503bebaf6f2630676db80ba630bc97e))

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [x] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment] 2021-04-06 07:29
Duplicate of #3114

**Closed by Cheesebaron** 2021-04-06 07:29 UTC
Labels: s/duplicate
