### ISSUE TITLE
Plugin "MethodBinding" does not work in WPF 

### ISSUE THREAD

**Issue by behzad62** [MvvmCross/MvvmCross#3171] opened 2018-10-21 20:34 UTC
## 🐛 Bug Report
Since version 6, the method binding plugin does not work in WPF apps anymore.
### Expected behavior
`<Button  mvx:Bi.nd="Command SomeMethod" />`

A xaml code like above should call method "SomeMethod". 

### Reproduction steps
Just try to bind a Command property of a 'Button' to a source ViewModel method
### Configuration

**Version:** 6.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [x] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment] 2018-10-23 06:57
Is the method public?

**Comment by Cheesebaron** [comment] 2018-10-24 20:06
I cannot reproduce. Make sure that the MethodBinding plugin is loaded correctly.

You can try override `LoadPlugins` in your `Setup`:

```csharp
public class Setup : MvxWpfSetup<Core.App>
{
    public override void LoadPlugins(IMvxPluginManager pluginManager)
    {
        base.LoadPlugins(pluginManager);

        pluginManager.EnsurePluginLoaded<MvvmCross.Plugin.MethodBinding.Plugin>(true);
    }
}
```

**Comment by behzad62** [comment] 2018-10-25 04:49
Yes it seems that this plugin needs to be loaded explicitly in setup. It was not the case in ver 5.x, that's why it confused me. Thanks for your time.

**Comment by Cheesebaron** [comment] 2018-10-25 11:43
Duplicate of #3164

**Closed by Cheesebaron** 2018-10-25 11:43 UTC
Labels: Duplicate, WPF
