### ISSUE TITLE
Playing with the Xamarin.Forms TipCalc app crashes

### ISSUE THREAD

**Issue by CamiloTerevinto** [MvvmCross/MvvmCross#3297] opened 2019-02-23 19:24 UTC
## 🐛 Bug Report

Since I've to get into a Xamarin.Forms project that uses MvvmCross, I've decided to at least run the most basic tutorial. I'm disappointed that following the tutorial results in an app that crashes so easily.
The first time I started from a Xamarin.Forms project with Android and resulted in this. The second time I followed carefully the steps, creating a .NET Standard 2.0 TipCalc.Core project, a .NET Standard 2.0 TipCalc.Forms.UI project and an Android TipCalc.Forms.Droid project.

Output console:

> 02-23 16:18:42.721 I/zygote64( 5132): Do partial code cache collection, code=29KB, data=29KB
> 02-23 16:18:42.721 I/zygote64( 5132): After code cache collection, code=29KB, data=29KB
> 02-23 16:18:42.721 I/zygote64( 5132): Increasing code cache capacity to 128KB
> 02-23 16:18:44.928 I/zygote64( 5132): Do partial code cache collection, code=58KB, data=59KB
> 02-23 16:18:44.931 I/zygote64( 5132): After code cache collection, code=58KB, data=59KB
> 02-23 16:18:44.931 I/zygote64( 5132): Increasing code cache capacity to 256KB
> 02-23 16:18:46.156 I/zygote64( 5132): Compiler allocated 5MB to compile void android.view.ViewRootImpl.performTraversals()
> 02-23 16:18:46.989 I/zygote64( 5132): Do full code cache collection, code=123KB, data=114KB
> 02-23 16:18:46.994 I/zygote64( 5132): After code cache collection, code=115KB, data=87KB
> 02-23 16:18:47.702 I/zygote64( 5132): Do partial code cache collection, code=119KB, data=101KB
> 02-23 16:18:47.702 I/zygote64( 5132): After code cache collection, code=119KB, data=101KB
> 02-23 16:18:47.702 I/zygote64( 5132): Increasing code cache capacity to 512KB
> 02-23 16:18:57.436 I/zygote64( 5132): Do full code cache collection, code=249KB, data=184KB
> 02-23 16:18:57.436 I/zygote64( 5132): After code cache collection, code=247KB, data=167KB
> 02-23 16:18:59.568 I/zygote64( 5132): Explicit concurrent copying GC freed 3662(143KB) AllocSpace objects, 0(0B) LOS objects, 50% free, 1526KB/2MB, paused 3.170ms total 11.131ms
> 02-23 16:18:59.571 D/Mono    ( 5132): GC_TAR_BRIDGE bridges 62 objects 1212 opaque 848 colors 62 colors-bridged 62 colors-visible 62 xref 4 cache-hit 0 cache-semihit 0 cache-miss 0 setup 0.26ms tarjan 0.42ms scc-setup 0.07ms gather-xref 0.03ms xref-setup 0.03ms cleanup 0.57ms
> 02-23 16:18:59.571 D/Mono    ( 5132): GC_BRIDGE: Complete, was running for 15.74ms
> 02-23 16:18:59.571 D/Mono    ( 5132): GC_MINOR: (Nursery full) time 6.56ms, stw 10.44ms promoted 862K major size: 2368K in use: 1639K los size: 1024K in use: 288K
> 02-23 16:19:04.179 I/zygote64( 5132): Do partial code cache collection, code=250KB, data=175KB
> 02-23 16:19:04.180 I/zygote64( 5132): After code cache collection, code=250KB, data=175KB
> 02-23 16:19:04.180 I/zygote64( 5132): Increasing code cache capacity to 1024KB
> 02-23 16:19:09.063 E/mono-rt ( 5132): Stacktrace:
> 02-23 16:19:09.063 E/mono-rt ( 5132): 
> 02-23 16:19:09.064 E/mono-rt ( 5132): /proc/self/maps:
> 02-23 16:19:09.064 E/mono-rt ( 5132): 12c00000-32c00000 rw-p 00000000 00:01 8636                               /dev/ashmem/dalvik-main space (region space) (deleted)
> 02-23 16:19:09.064 E/mono-rt ( 5132): 40313000-403f3000 rwxp 00000000 00:00 0 
> 02-23 16:19:09.064 E/mono-rt ( 5132): 4048d000-40491000 rw-p 00000000 00:01 10222                              /dev/ashmem/dalvik-large object space allocation (deleted)
> 02-23 16:19:09.064 E/mono-rt ( 5132): 405ca000-405d0000 rw-p 00000000 00:01 10215                              /dev/ashmem/dalvik-large object space allocation (deleted)
> 02-23 16:19:09.064 E/mono-rt ( 5132): 40685000-4068d000 rw-p 00000000 00:01 66319                              /dev/ashmem/dalvik-large object space allocation (deleted)
> 02-23 16:19:09.064 E/mono-rt ( 5132): 40836000-4083d000 rw-p 00000000 00:01 10214                              /dev/ashmem/dalvik-large object space allocation (deleted)
> 02-23 16:19:09.064 E/mono-rt ( 5132): 40ae0000-40aed000 rw-p 00000000 00:01 10225                              /dev/ashmem/dalvik-large object space allocation (deleted)
> 02-23 16:19:09.064 E/mono-rt ( 5132): 40be8000-40bf6000 rw-p 00000000 00:01 10213                              /dev/ashmem/dalvik-large object space allocation (deleted)
> 02-23 16:19:09.064 E/mono-rt ( 5132): 40e3a000-40fc3000 rwxp 00000000 00:00 0 
> 02-23 16:19:09.064 E/mono-rt ( 5132): 40fd2000-40fd7000 rw-p 00000000 00:01 10211                              /dev/ashmem/dalvik-large object space allocation (deleted)
> 02-23 16:19:09.064 E/mono-rt ( 5132): 4108c000-410ac000 rwxp 00000000 00:00 0 
> 02-23 16:19:09.064 E/mono-rt ( 5132): 410b3000-410be000 rw-p 00000000 00:01 10212                              /dev/ashmem/dalvik-large object space allocation (deleted)
> 02-23 16:19:09.064 E/mono-rt ( 5132): 41434000-4143e000 rw-p 00000000 00:01 10228                              /dev/ashmem/dalvik-large object space allocation (deleted)
> 02-23 16:19:09.065 E/mono-rt ( 5132): 415e6000-41647000 rw-p 00000000 00:01 10223                              /dev/ashmem/dalvik-large object space allocation (deleted)
> 02-23 16:19:09.065 E/mono-rt ( 5132): 41647000-4164b000 rw-p 00000000 00:01 10226                              /dev/ashmem/dalvik-large object space allocation (deleted)
> 02-23 16:19:09.065 E/mono-rt ( 5132): 4164b000-417df000 rwxp 00000000 00:00 0 
> 02-23 16:19:09.065 E/mono-rt ( 5132): 417e0000-417e5000 rw-p 00000000 00:01 10250                              /dev/ashmem/dalvik-large object space allocation (deleted)
> 02-23 16:19:09.065 E/mono-rt ( 5132): 418a3000-418a8000 rw-p 00000000 00:01 10220                              /dev/ashmem/dalvik-large object space allocation (deleted)
> 02-23 16:19:09.065 E/mono-rt ( 5132): 419d7000-419de000 rw-p 00000000 00:01 10216                              /dev/ashmem/dalvik-large object space allocation (deleted)
> 02-23 16:19:09.065 E/mono-rt ( 5132): 41a01000-41b21000 rwxp 00000000 00:00 0 
> 02-23 16:19:09.065 E/mono-rt ( 5132): 41b2a000-41b30000 rw-p 00000000 00:01 10224                              /dev/ashmem/dalvik-large object space allocation (deleted)
> 02-23 16:19:09.065 E/mono-rt ( 5132): 41bfe000-41c0e000 rwxp 00000000 00:00 0 
> 02-23 16:19:09.065 E/mono-rt ( 5132): 41c1a000-41c20000 rw-p 00000000 00:01 10219                              /dev/ashmem/dalvik-large object space allocation (deleted)
> 02-23 16:19:09.065 E/mono-rt ( 5132): 41c52000-41c56000 rw-p 00000000 00:01 10247                              /dev/ashmem/dalvik-large object space allocation (deleted)
> 02-23 16:19:09.065 E/mono-rt ( 5132): 41cb0000-41d00000 rwxp 00000000 00:00 0 
> 02-23 16:19:09.065 E/mono-rt ( 5132): Memory around native instruction pointer (0x77781568ca75):
> 02-23 16:19:09.065 E/mono-rt ( 5132): 0x77781568ca65  00 49 8b 86 c8 00 00 00 48 85 c0 74 1d 0f b7 10  .I......H..t....
> 02-23 16:19:09.065 E/mono-rt ( 5132): 0x77781568ca75  49 63 8c 24 bc 00 00 00 39 ca 7c 0e 48 8b 44 c8  Ic.$....9.|.H.D.
> 02-23 16:19:09.065 E/mono-rt ( 5132): 0x77781568ca85  08 48 85 c0 0f 85 5a 01 00 00 c7 03 00 00 00 00  .H....Z.........
> 02-23 16:19:09.066 E/mono-rt ( 5132): 0x77781568ca95  e8 46 94 fd ff 4c 89 e7 e8 5e 44 f9 ff 49 8b ae  .F...L...^D..I..
> 02-23 16:19:09.066 E/mono-rt ( 5132): 
> 02-23 16:19:09.066 E/mono-rt ( 5132): No native Android stacktrace (see debuggerd output).
> 02-23 16:19:09.066 E/mono-rt ( 5132): 
> 02-23 16:19:09.066 E/mono-rt ( 5132): 
> 02-23 16:19:09.066 E/mono-rt ( 5132): =================================================================
> 02-23 16:19:09.066 E/mono-rt ( 5132): Got a SIGSEGV while executing native code. This usually indicates
> 02-23 16:19:09.066 E/mono-rt ( 5132): a fatal error in the mono runtime or one of the native libraries 
> 02-23 16:19:09.066 E/mono-rt ( 5132): used by your application.
> 02-23 16:19:09.066 E/mono-rt ( 5132): =================================================================
> 02-23 16:19:09.066 E/mono-rt ( 5132): 
> 02-23 16:19:09.066 F/libc    ( 5132): Fatal signal 11 (SIGSEGV), code 1, fault addr 0xbc in tid 5167 (AsyncTask #1), pid 5132 (alc.Forms.Droid)
> 

### Expected behavior
Moving the slider shouldn't crash the application.

### Reproduction steps
Move the slider around and watch for the output window, it crashes in a few seconds.

### Configuration
Visual Studio: 2019 Preview 3.0
**Version:** 6.2.3

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [X] :monkey: Xamarin.Forms

**Comment by nmilcoff** [comment] 2019-02-24 19:56
Can you please provide us with some repro steps? Also would you mind trying with the "completed" version we provide? [Reference](https://github.com/MvvmCross/MvvmCross-Samples/tree/master/TipCalc)

**Comment by CamiloTerevinto** [comment] 2019-02-24 22:12
Repro is pretty easy:

1. Follow this to create the Core project: https://www.mvvmcross.com/documentation/tutorials/tipcalc/the-core-project?scroll=1710
2. Follow this to create the Forms and Android projects: https://www.mvvmcross.com/documentation/tutorials/tipcalc/a-xamarin-forms-version?scroll=1710
3. Test by launching the app and moving the scrollbar. In my testing, a couple of times it took a minute for it to crash and other times it crashed in as much as 5 seconds.

After downloading the reference version, VS asked me to download another Android SDK and I couldn't reproduce the issue. Updating all packages to match my version and still couldn't reproduce. I am going to take a look at the code to spot differences.

**Comment by Cheesebaron** [comment] 2019-03-21 18:40
Please verify it in Visual Studio 2017 and see if you still see the issue. I have seen some strange issues with the mono runtime in Visual Studio 2019 which randomly crashes my apps.

**Comment by dlpopescu** [comment] 2019-04-09 10:24
This also happens in one of our projects, with VS 2019 on a Mac, trying to put a repro project together. The error message is the same

`Fatal signal 11 (SIGSEGV), code 1, fault addr 0xbc (AsyncTask #1)`

**Comment by Cheesebaron** [comment] 2019-04-09 18:36
Dupe of https://github.com/xamarin/xamarin-android/issues/2920

**Closed by Cheesebaron** 2019-04-09 18:36 UTC
Labels: p/android, p/samples, s/needs-more-info
