### ISSUE TITLE
Bindings in 4.2.x  System.AggregateException caught in HockeyApp

### ISSUE THREAD

**Issue by NielsWillems** [MvvmCross/MvvmCross#1398] opened 2016-07-18 11:02 UTC
When binding an observable collection as ItemSource for a MvxTableViewSource it works without HockeyApp. When HockeyApp is added the app crashes unless I comment out the bindings in a cell. When I want to use both I have to add the following to the Setup.cs file of the iOS app.:

`Mvx.RegisterType<IMvxBindingContext, MvxBindingContext>();`

The stack trace is provided  further down this post.
### Expected behavior

Properties in cell should be rebound
### Actual behavior

App crashes
### Configuration

**Version:** 4.2.2 (I believe also 4.2.0 but not 100% sure)

**Platform:** iOS

**HockeyApp StackTrace:**

```
Application Specific Information:
*** Terminating app due to uncaught exception 'System.AggregateException', reason: 'System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
  at System.ThrowHelper.ThrowInvalidOperationException (ExceptionResource resource) [0x00000] in /Users/builder/data/lanes/3412/3cf8aaed/source/maccore/_build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/external/referencesource/mscorlib/system/throwhelper.cs:99 
  at System.Collections.Generic.List`1+Enumerator[T].MoveNextRare () [0x00016] in /Users/builder/data/lanes/3412/3cf8aaed/source/maccore/_build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/external/referencesource/mscorlib/system/collections/generic/list.cs:1180 
  at System.Collections.Generic.List`1+Enumerator[T].MoveNext () [0x00050] in /Users/builder/data/lanes/3412/3cf8aaed/source/maccore/_build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/external/referencesource/mscorlib/system/collections/generic/list.cs:1174 
  at MvvmCross.Binding.BindingContext.MvxTaskBasedBindingContext.<OnDataContextChange>b__20_0 () [0x0008d] in C:\vcs\git\MvvmCross\MvvmCross\Core\Binding\BindingContext\MvxTaskBasedBindingContext.cs:127 
  at System.Threading.Tasks.Task.InnerInvoke () [0x00012] in /Users/builder/data/lanes/3412/3cf8aaed/source/maccore/_build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/external/referencesource/mscorlib/system/threading/Tasks/Task.cs:2879 
  at System.Threading.Tasks.Task.Execute () [0x00016] in /Users/builder/data/lanes/3412/3cf8aaed/source/maccore/_build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/external/referencesource/mscorlib/system/threading/Tasks/Task.cs:2502 
  --- End of inner exception stack trace ---
---> (Inner Exception #0) System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
  at System.ThrowHelper.ThrowInvalidOperationException (ExceptionResource resource) [0x00000] in /Users/builder/data/lanes/3412/3cf8aaed/source/maccore/_build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/external/referencesource/mscorlib/system/throwhelper.cs:99 
  at System.Collections.Generic.List`1+Enumerator[T].MoveNextRare () [0x00016] in /Users/builder/data/lanes/3412/3cf8aaed/source/maccore/_build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/external/referencesource/mscorlib/system/collections/generic/list.cs:1180 
  at System.Collections.Generic.List`1+Enumerator[T].MoveNext () [0x00050] in /Users/builder/data/lanes/3412/3cf8aaed/source/maccore/_build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/external/referencesource/mscorlib/system/collections/generic/list.cs:1174 
  at MvvmCross.Binding.BindingContext.MvxTaskBasedBindingContext.<OnDataContextChange>b__20_0 () [0x0008d] in C:\vcs\git\MvvmCross\MvvmCross\Core\Binding\BindingContext\MvxTaskBasedBindingContext.cs:127 
  at System.Threading.Tasks.Task.InnerInvoke () [0x00012] in /Users/builder/data/lanes/3412/3cf8aaed/source/maccore/_build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/external/referencesource/mscorlib/system/threading/Tasks/Task.cs:2879 
  at System.Threading.Tasks.Task.Execute () [0x00016] in /Users/builder/data/lanes/3412/3cf8aaed/source/maccore/_build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/external/referencesource/mscorlib/system/threading/Tasks/Task.cs:2502 <---
'
```

**Comment by Cheesebaron** [comment] 2016-07-18 11:28
Thanks for filing the issue.

I don't think it is directly related to HockeyApp. The problem is, however, that the Lists are enumerated in a Task, which means the Lists can be modified while the enumeration is going on. This will give you `System.InvalidOperationException: Collection was modified; enumeration operation may not execute.` as you are seeing.

The easiest fix is to add `ToArray()` or `ToList()` before enumerating to get a copy of the list, which can't be modified when enumerating. However, I think we should use a blocking list type instead. Such as ConcurrentList, from System.Collections.Concurrent.

**Comment by KLytvynenko** [comment] 2016-10-12 14:34
Will this fixed be merged in new MvvmCross dll ?

**Comment by martijn00** [comment] 2016-10-12 14:36
Only if a pull request is made. We can't merge this.

**Comment by claudioredi** [comment] 2017-02-09 22:26
Is there any workaround for this until this fix gets released? It doesn't happen a lot in my case but happens enough to brought our attention. I get "Collection was modified; enumeration operation may not execute." in different places on my app.

```
System.InvalidOperationExceptionCollection was modified; enumeration operation may not execute.
  at System.ThrowHelper.ThrowInvalidOperationException (System.ExceptionResource resource) <0x100b836a0 + 0x00024> in <15e850188d9f425bbeae90f0bbc51e17#f67f805b09c9b6026f3212c51c9af7f0>:0 
  at System.Collections.Generic.List`1+Enumerator[T].MoveNextRare () <0x100a778c0 + 0x0002f> in <15e850188d9f425bbeae90f0bbc51e17#f67f805b09c9b6026f3212c51c9af7f0>:0 
  at System.Collections.Generic.List`1+Enumerator[T].MoveNext () <0x100a777f0 + 0x0009f> in <15e850188d9f425bbeae90f0bbc51e17#f67f805b09c9b6026f3212c51c9af7f0>:0 
  at MvvmCross.Binding.BindingContext.MvxTaskBasedBindingContext.<OnDataContextChange>b__20_0 () <0x1018b0860 + 0x0023f> in <152bcd8562a44d46b235d7867373a218#f67f805b09c9b6026f3212c51c9af7f0>:0 
  at System.Threading.Tasks.Task.InnerInvoke () <0x100b713d0 + 0x0005f> in <15e850188d9f425bbeae90f0bbc51e17#f67f805b09c9b6026f3212c51c9af7f0>:0 
  at System.Threading.Tasks.Task.Execute () <0x100b70bf0 + 0x00043> in <15e850188d9f425bbeae90f0bbc51e17#f67f805b09c9b6026f3212c51c9af7f0>:0 
```

Thanks!

**Comment by Cheesebaron** [comment] 2017-02-09 22:32
You can try and see if you still see the issues when you use the NuGets from the MyGet repository: https://www.myget.org/F/mvvmcross/api/v2

**Comment by claudioredi** [comment] 2017-02-09 22:36
Thanks @Cheesebaron: it might take long to give you an answer since we only see this logged on production app and it's totally "random". I don't know a way to force it to happen.

**Comment by kjeremy** [comment] 2017-02-09 22:39
#1501 was merged earlier today which should hopefully fix this.

**Comment by kjeremy** [comment] 2017-02-09 22:40
I'm going to close this now since the fix is in.  We can reopen it if it pops up again.

**Closed by kjeremy** 2017-02-09 22:40 UTC
Labels: Bug, up-for-grabs

**Comment by claudioredi** [comment] 2017-02-09 22:50
Yes I saw it merged Today but didn't know how long it would take to be released, that's why I checked for a workaround. Not a very serious problem for my app so probably we can just wait. Thasks!

**Comment by ruhanijeb** [comment] 2018-12-04 13:32
i am facing this issue. i upgraded from 4.2.0 to 5.0.0 .  but still my app getting crash automatically and i am getting the above stack trace on hockey app.

**Comment by ruhanijeb** [comment] 2018-12-04 13:33
this happens on my login screen and i am not using any list in my login screen.
