### ISSUE TITLE
Mvx.IoCProvider.Resolve<IMvxAndroidCurrentTopActivity>() return Activity Null

### ISSUE THREAD

**Issue by StefanoPaparesta** [MvvmCross/MvvmCross#4334] opened 2021-12-01 11:13 UTC
## 🐛 Bug Report
When i call `Mvx.IoCProvider.Resolve<IMvxAndroidCurrentTopActivity>()`  return the property Activity null.

I have a class DialogService in Droid project

``` c#
public class DialogService : IDialogService
    {
        /// <summary>Alerts the user with a simple OK dialog and provides a <paramref name="message"/>.</summary>
        /// <param name="message">The message.</param>
        /// <param name="title">The title.</param>
        /// <param name="okbtnText">The okbtn text.</param>
        public void Alert(string message, string title, string okbtnText)
        {

          var top = Mvx.IoCProvider.Resolve<IMvxAndroidCurrentTopActivity>();
          var act = top.Activity;
        
            var adb = new AlertDialog.Builder(act);
            adb.SetTitle(title);
            adb.SetMessage(message);
            //adb.SetIcon(Resource.Drawable.Icon);
            adb.SetPositiveButton(okbtnText, (sender, args) => { /* some logic */ });
            adb.Create().Show();

        }
}
```

### Expected behavior

When call Alert("MESSAGE","TITLE","OK")  from my view
this code in DialogService class

```c#
var top = Mvx.IoCProvider.Resolve<IMvxAndroidCurrentTopActivity>();
var act = top.Activity;
```

the variable **act** is **not null**;

### Configuration

Setup 

```c#
public class Setup : MvxFormsAndroidSetup<Core.App, UI.App>
    {
        protected override ILoggerProvider CreateLogProvider() => new SerilogLoggerProvider();

        protected override ILoggerFactory CreateLogFactory()
        {
            Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Debug()
                .WriteTo.AndroidLog()
                .CreateLogger();

            return new SerilogLoggerFactory();
        }

        protected override void InitializeFirstChance(IMvxIoCProvider iocProvider)
        {

            iocProvider.ConstructAndRegisterSingleton<ISqliteConnectionService, SqliteConnectionService>();
            iocProvider.ConstructAndRegisterSingleton<IDeviceId, DeviceIdService>();
            iocProvider.ConstructAndRegisterSingleton<IDialogService, DialogService>();

            base.InitializeFirstChance(iocProvider);

        }


  }
```

View

```c#
private IDialogService _dialogService;

//Ctor

public MissioneViewModel(IDialogService dialogService)
{
    _dialogService = dialogService;
}

public void HandleMissioneCommand()
{
  _dialogService .Alert("MESSAGE","TITLE","OK");
}
```
Interface
```c#
 public interface IDialogService
 {
        void Alert(string message, string title, string okbtnText);
 }
```
**Workaround:**
I found this workaround

```c#
[Activity(Theme = "@style/AppTheme")]
    public class MainActivity : MvxFormsAppCompatActivity<MainViewModel>
    {

        public MainActivity()
        {

        }
        
        // workaround
        static MainActivity Instance { get; private set; }

        protected override void OnCreate(Bundle bundle)
        {
            TabLayoutResource = Resource.Layout.Tabbar;
            ToolbarResource = Resource.Layout.Toolbar;

            base.OnCreate(bundle);
            Xamarin.Essentials.Platform.Init(this, bundle);
            // workaround
            Instance = this;
        }
}

```

```c#
public class DialogService : IDialogService
    {
        /// <summary>Alerts the user with a simple OK dialog and provides a <paramref name="message"/>.</summary>
        /// <param name="message">The message.</param>
        /// <param name="title">The title.</param>
        /// <param name="okbtnText">The okbtn text.</param>
        public void Alert(string message, string title, string okbtnText)
        {

            // IsBroken
            // var top = Mvx.IoCProvider.Resolve<IMvxAndroidCurrentTopActivity>();
            // var act = top.Activity;

            // This is a workaround
            var adb = new AlertDialog.Builder(MainActivity.Instance);
            adb.SetTitle(title);
            adb.SetMessage(message);
            //adb.SetIcon(Resource.Drawable.Icon);
            adb.SetPositiveButton(okbtnText, (sender, args) => { /* some logic */ });
            adb.Create().Show();

        }
}
```

**Version:** 8.0.2

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [X] :monkey: Xamarin.Forms

**Comment by jmetcal4** [comment] 2021-12-15 22:48
I'm also seeing this issue. `IMvxAndroidCurrentTopActivity.Activity` initially returns `SplashActivity` during startup, but is returning null once `MainActivity` is started.

#### Versions:
_MvvmCross 8.0.2
Xamarin.Forms 5.0.0.2244_

**Comment by DuncanMT** [comment] 2022-04-14 10:39
I am also seeing this.  The MvxAndroidLifetimeMonitor OnCreate does not get called for MainActivity, however, OnDestroy for the splash screen activity does get called setting  Acvitiy to null.

```
 case MvxActivityState.OnDestroy:
     if (e.Activity == Activity)
         Activity = null;
         break;
 ```

**Comment by DuncanMT** [comment] 2022-11-01 10:37
Ran into this issue again in a fresh project and took another look at this issue.  @jmetcal4 @StefanoPaparesta 

This issue is apparently caused by MvxFormsAppCompatActivity not inheriting from MvxActivity, which is the only place that AddEventListeners is called.  
```
protected MvxActivity()
{
    BindingContext = new MvxAndroidBindingContext(this, this);
    this.AddEventListeners();
}
```
Since MvxFormsAppCompatActivity inherits from FormsAppCompatActivity instead if we add the AddEventListeners call to the constructor everything starts to work properly again.
```
public MainActivity()
{
    this.AddEventListeners();
}
```

**Comment by Cheesebaron** [comment] 2023-01-20 14:14
Closing. Forms is not supported anymore.

**Closed** 2023-01-20 14:14 UTC
