### ISSUE TITLE
override Close is not called when Mac Window is closed using x button

### ISSUE THREAD

**Issue by tofutim** [MvvmCross/MvvmCross#2199] opened 2017-09-17 21:50 UTC
In Playground.Mac, when the "Close" button is pressed, Close is called in the Presenter. However, when the X button is pressed, Close is not called.

**Comment by nmilcoff** [comment] 2017-09-17 21:57
You're right, it is not supported yet. Do you think you can make a PR for it? :)

**Comment by tofutim** [comment] 2017-09-18 16:02
I'm not sure. Given a "Window" closing, how do I know what ViewModel is in it? Would there be multiple ViewModels? What if it is like a tab? Hmmm.

**Comment by nmilcoff** [comment] 2017-09-18 17:53
Thinking a bit more about this... 

Close is called only when a ViewModel is closed (`MvxClosePresentationHint`). if a View is closed in any other way, like using a platform-provided way, then I wouldn't expect ViewPresenter.Close to be called.

This doesn't mean the issue is invalid, because we keep a [`List<NSWindow>`](https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross/Mac/Mac/Views/Presenters/MvxMacViewPresenter.cs#L26) that can potentially be obsolete. 

I think we could get rid of that List and only use the newly added ConditionalWeakTable to keep track of the opened windows.

**Closed** 2017-12-03 08:25 UTC
Labels: Mac
