### ISSUE TITLE
Async Startup in Ios

### ISSUE THREAD

**Issue by pablo0219** [MvvmCross/MvvmCross#3300] opened 2019-02-25 17:31 UTC
## 🚀 Feature Requests

I know mvvmcross contributors has been working on Async Startup for some time so far. However, I have seen a lot of post with people talking about these issues. How to solve it, etc. Reality is mvvmcross has had this buggy problem for some time. This problem really affect the cross platform advantages. I have been working on an android app for sometime now. I decided to take advantage of Ios these last days. Result: Ios doesn't work in the same way. The app hangs in LaunchScreen when Task.Delay(1) is included. A deadlocking issue.

### Contextualize the feature
You can see this problem in Playground.Ios  when you uncomment -- await Task.Delay(5000); Even it could be 1ms.mThis is a headache for a cross platform app. I really think that the focus of development should be centered on this problem. My problem is in Ios; however, I'm not excluding others. I have had this problem in Android in the past.

        public override async Task Initialize()
        {
            Log.Warn(() => "Testing log");

            await base.Initialize();

            // Uncomment this to demonstrate use of StartAsync for async first navigation
            // await Task.Delay(5000);

            _mvxViewModelLoader.LoadViewModel(MvxViewModelRequest.GetDefaultRequest(typeof(ChildViewModel)),
                new SampleModel
                {
                    Message = "From locator",
                    Value = 2
                },
                null);

            await MakeRequest();
        }

### Platforms affected (mark all that apply)
- [x ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment] 2019-03-01 09:40
Duplicate of #3209

**Closed by Cheesebaron** 2019-03-01 09:40 UTC
