### ISSUE TITLE
How to use prepopulated DB in sqlite plugin

### ISSUE THREAD

**Issue by vinodh06** [MvvmCross/MvvmCross#1280] opened 2016-04-05 11:24 UTC

**Comment by Cheesebaron** [comment] 2016-04-05 11:24
Thanks for opening this issue. Please use and fill out the issue template. Closing it for now until actual details are provided.

**Closed by Cheesebaron** 2016-04-05 11:24 UTC

**Comment by Cheesebaron** [comment] 2016-04-05 14:54
Duplicate of #1279
