### ISSUE TITLE
Images never load first time using DownloadCache plugin

### ISSUE THREAD

**Issue by kartheeknagasuri** [MvvmCross/MvvmCross#1056] opened 2015-07-09 14:30 UTC
Tried to debug the problem, it never returns after the first statement. went through the code, code looks fine.
//in MvxImageCache.cs file. 

var stream = await _fileDownloadCache.RequestLocalFilePath(url);
  await ProcessFilePath(url, stream);

**Comment by martijn00** [comment] 2015-07-09 14:42
What platform are you on? What version of MvvmCross do you use?

**Comment by kartheeknagasuri** [comment] 2015-07-10 03:21
I am using this library with Xamrin iOS, i have taken the latest version that is available on Git.

**Comment by kartheeknagasuri** [comment] 2015-07-10 07:25
Checked with 3.5.1 - this issue is not there. thanks for asking the question.

**Comment by martijn00** [comment] 2015-07-10 07:35
There where other issue's in there as well: https://github.com/MvvmCross/MvvmCross/issues/1041
This is our sample repo to reproduce the bug: https://github.com/SimonSimCity/MvvmCrossImageBug
Can you make something like that sample as well, so we can debug it?

**Comment by Cheesebaron** [comment] 2015-07-10 16:58
It seems to be broken. I might give it a go during the weekend and fix it.

**Comment by dbeattie71** [comment] 2015-07-12 21:09
Not sure what the exact problem is yet but it seems to happen at RequestImage in MvxImageCache.  The call to RequestImage from MvxImageRequest is never returned even though the TaskCompletionSource is set.  Monitor.Exit is called before the tcs is returned.

**Comment by Cheesebaron** [comment] 2015-07-15 08:26
I think this is fixed in the latest alpha.

**Closed** 2015-07-15 08:36 UTC
Labels: Needs More Info
