### ISSUE TITLE
Update to 6.1.2 causes reference error in .Android project for MvxAndroidApplication

### ISSUE THREAD

**Issue by svenbayoo** [MvvmCross/MvvmCross#2968] opened 2018-06-19 12:48 UTC
Hi, 
I updated my project from 5.6.3. to 6.1.2 and could resolve all error in my .Core project, yet the .Android project of my PCL has a problem. For the update process I used Nuget Package Manager in VS2017 and before updating to 6.1.2 I changed the target framework for the .Android project to 8.1 in order to be able to use the MvvmCross.Droid.Support.V7.AppCompat.

In the project with 5.6.3 I used the previously existing Setup.cs to pass the database path to my App-instance and registered an MvxLanguageConverter for localization.

```
protected override IMvxApplication CreateApp()
        {
            var dbPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Personal),"MyDatabase.db");
            return new App(dbPath);
        }

protected override IMvxTrace CreateDebugTrace()
        {
            return new DebugTrace();
        }

protected override void FillValueConverters(MvvmCross.Converters.IMvxValueConverterRegistry registry)
        {
            base.FillValueConverters(registry);
            registry.AddOrOverwrite("Language", new MvxLanguageConverter());
        }
```

After the update I created a MainApplication.cs and it inherits from
MvxAppCompatApplication<MvxAppCompatSetup<App>, App>. As to my knowledge this is now the "replacement" for the Setup.cs, as a change from 5.6.X to 6.X

The error I now get is the following:

> Reference to type 'MvxAndroidApplication' claims it is defined in 'MvvmCross', but it could not be found.

Further when building the app, it cannot resolve the local:MvxBind and local:MvxLang command in the .axml files, using `xmlns:local="http://schemas.android.com/apk/res-auto"`.

Anyone has an idea why it is searching for MvxAndroidApplication and can't find it as well as about the now missing?

**Platform:** 
- [X] :robot: Android

**Comment by martijn00** [comment] 2018-07-11 15:13
Can you make a reproduction repo for this?

**Comment by nmilcoff** [comment] 2018-07-28 20:36
This looks like an environment problem. Can you try removing the nuget packages on your Android project and adding them back? 

It is also weird that you're using `MvxAppCompatApplication` and there is an error for `MvxAndroidApplication`, where do you see it?

**Comment by nickrandolph** [comment] 2018-08-08 04:27
@svenbayoo were you able to resolve this issue?

**Comment by nmilcoff** [comment] 2018-11-26 02:37
I'll close this for now, as it seems there are no problems related to MvvmCross itself. Please feel free to reopen it if you think otherwise

**Closed by nmilcoff** 2018-11-26 02:37 UTC
Labels: Android, AndroidSupport, Deprecated
