### ISSUE TITLE
Unable to update MVVM Cross from v7.1.2 to 8.0.1 with Xamarin Forms 5.0.2083

### ISSUE THREAD

**Issue by Daverism** [MvvmCross/MvvmCross#4228] opened 2021-07-20 09:38 UTC
## 🐛 Bug Report

Unable to update MVVM Cross from v7.1.2 to 8.0.1 with Xamarin Forms 5.0.2083

NU1107: Version conflict detected for Xamarin.Google.Android.Material. Install/reference Xamarin.Google.Android.Material 1.3.0.1 directly to project Nsml.SavingsApp.Android to resolve this issue. 
{Project} -> MvvmCross 8.0.1 -> Xamarin.Google.Android.Material (>= 1.3.0.1) 
{Project}-> Xamarin.Forms 5.0.0.2083 -> Xamarin.Google.Android.Material (>= 1.2.1.1 && < 1.3.0).

NU1608: Detected package version outside of dependency constraint: Xamarin.Forms 5.0.0.2083 requires Xamarin.Google.Android.Material (>= 1.2.1.1 && < 1.3.0) but version Xamarin.Google.Android.Material 1.3.0.1 was resolved.

### Expected behavior

MVVM Cross updates successfully to 8.0.1

### Reproduction steps
update existing project to Xamarin.Forms 5.0.2083
update MVVM Cross 7.1.2 to 8.0.1

### Configuration

**Version:** 8.0.1

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment] 2021-07-20 09:53
Please complain to the Xamarin.Forms team, they've imposed upper bound restrictions on their NuGet packages in their latest releases.

Duplicate of #4225

**Closed by Cheesebaron** 2021-07-20 09:53 UTC
Labels: s/duplicate

**Comment by Daverism** [comment] 2021-07-20 10:25
Great, will do. Thanks!
