### ISSUE TITLE
[Bug]: Clicked event not getting triggered since .NET 8 in combination with MvvmCross 9.2.0

### ISSUE THREAD

**Issue by dgyesbreghs** [MvvmCross/MvvmCross#4833] opened 2024-03-01 08:24 UTC
### Description

Since we upgraded to our project to .NET 8 for Android in comabination with MvvmCross 9.2.0.
Clicked events from the RecyclerView are not triggered anymore.

Do you know if something did change?

### Version with bug

9.2.0

### Is this a regression from previous behavior?

Yes, this used to work in a previous version

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by Cheesebaron** [comment] 2024-03-01 09:35
Hard to guess what the issue is without more information.

Are you using `ItemClick` command on the Adapter or is it something else you are referring to? Does it only happen in Release mode or also in Debug builds? Anything else I need to guess or will you provide a bit more info? ;)

**Comment by Cheesebaron** [comment] 2024-03-04 18:57
Closing as no more info provided by author.

**Closed** 2024-03-04 18:57 UTC
Labels: t/bug, s/needs-more-info
