### ISSUE TITLE
New presenter for Android

### ISSUE THREAD

**Issue by martijn00** [MvvmCross/MvvmCross#1934] opened 2017-06-09 17:34 UTC
The current Android presenter is very limited. Out of the box there is no support for Fragments, Dialogs, or other navigation patterns. To fix this we need to develop a new presenter which will replace the current one as default. The new presenter should support:

- [x] Fragments (Nested)
- [x] Activity's
- [x] Dialogs
- [x] Tabs / ViewPager

Navigation patterns that should be easy to implement with this are:

- [x] NavigationDrawer
- [ ] BottomNavigationBar
- [x] BottomSheetDialog
- [x] Master/Detail Flows
- [x] Nested navigation

Other requirements are:

- [ ] Unit Tests
- [x] Support for Native and AppCompat views
- [ ] Handle tombstoning
- [x] Easy usage of animations
- [x] Closing of views as well as showing
- [ ] Handling the backstack
- [ ] Caching fragments
- [ ] Comply with the [Android Architecture](https://developer.android.com/topic/libraries/architecture/index.html) components

The plan is to implement it similar to the new iOS presenter, were we have multiple View attributes to indicate how the view will be shown. Also a interface can be implemented to customize view behaviour at runtime.

**Comment by Cheesebaron** [comment] 2017-06-09 17:49
We should really concentrate on keeping this super simple. The MvxCachingFragmentActivity stuff has grown into a complex Fragments monster.

Hopefully those Android Architecture bits can help us out here a bit.

**Comment by PelleRavn** [comment] 2017-06-23 13:46
Also it would be nice if the same core-interface (e.g. the tab presenter) on both iOS and Android shared the same interface. Then it would be a lot easier to implement it on both platforms, without having to do something specific for each platform in core.

**Comment by nmilcoff** [comment] 2017-06-25 14:17
#1917 is a feature request for the presenter

**Comment by nmilcoff** [comment] 2017-07-11 18:25
Based on #1264 and #1986, it would be great if the new presenter could improve the caching mechanism for fragments, current caching strategy sometimes leads to issues.

The problem is that Android automatically caches the state of all controls that have an `android:id` set. This means that when a fragment is displayed for a second time, it contains old data. The current workaround for that is to avoid caching on such fragments (mainly fragments that contain form inputs)

**Comment by nmilcoff** [comment] 2017-08-03 14:40
#1373 is also related (fragment caching issue)

**Comment by nmilcoff** [comment] 2017-08-08 18:58
Maybe #962 can be fixed in the new Presenter PR, what do you guys think? All that is necessary is to remove `ActivityFlags.NewTask` from [here](https://github.com/MvvmCross/MvvmCross/blob/f9f6e2643d2defc6ccc033f899a8ecf599441e67/MvvmCross/Droid/Droid/Views/MvxAndroidViewsContainer.cs#L147).

**Comment by nmilcoff** [comment] 2017-08-12 21:13
In my opinion, we shouldn't provide a very specialized caching feature for fragments this time. 

I might be wrong, but everything I've been reading about it makes me think it is not the _standard_ way to work with fragments. Reason being is they are quite large objects, and when an app becomes big, the amount of cached fragments can become a problem. Also memory related issues are not simple to solve, so we shouldn't be adding complexity to the matter.

My proposal is not to kill the feature, but to keep it simple and not to make it the default behavior.

IF you agree with this, the new presenter already has something done in this field (it holds the cached fragments in a ConditionalWeakTable), we should just adjust some issues and it is good to go.

**Closed** 2017-09-04 13:47 UTC
Labels: Android, AndroidSupport, Feature request

**Comment by Cheesebaron** [comment] 2017-09-05 15:32
@martijn00 should this be closed? The work is not entirely done?

**Comment by martijn00** [comment] 2017-09-05 16:20
I've updated the checkboxes to the current state. Most stuff is done and i'm not exactly sure how we could add unit tests for this. I think we probably receive some bug reports after the release, which we then can fix.

**Comment by nmilcoff** [comment] 2017-09-05 16:23
I think caching of fragments and tombstoning are not done yet (unless I missed something here). 
Maybe we should look into that before closing this issue and all the other ones related to the old logic.

**Comment by ornolisvt** [comment] 2017-10-20 14:56
Hi. Please, you can provide a example de nested fragments with viewpager?

**Comment by martijn00** [comment] 2017-10-20 15:31
Look at the playground samples like: https://github.com/MvvmCross/MvvmCross/blob/develop/TestProjects/Playground/Playground.Droid/Views/Tab1View.cs#L12

**Comment by ornolisvt** [comment] 2017-10-20 16:27
Thank you very much, I will check it. I I really appreciate your help
