### ISSUE TITLE
The type or namespace name 'MvxSplashScreenActivity' could not be found (are you missing a using directive or an assembly reference?)	

### ISSUE THREAD

**Issue by rathanakumarsekar21** [MvvmCross/MvvmCross#4625] opened 2023-07-06 10:03 UTC
## 🐛 Bug Report

I'm unable to build TipCalc sample application in Android. I'm getting the below mentioned issue.

_The type or namespace name 'MvxSplashScreenActivity' could not be found (are you missing a using directive or an assembly reference?)_	

![Error](https://github.com/MvvmCross/MvvmCross/assets/104616600/5d970a98-8200-406f-9a73-5b04b1f4e3c8)

### Expected behavior

 TipCalc sample app should run properly in Android.

### Reproduction steps

Download and run the TipCalc sample application in Android.

### Configuration

**Version:** 9.0.10

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by rathanakumarsekar21** [comment] 2023-07-06 10:06
![Error1](https://github.com/MvvmCross/MvvmCross/assets/104616600/cfd7db3c-0a6e-4642-90f5-c373d8db6614)

**Comment by rathanakumarsekar21** [comment] 2023-07-07 03:59
Any update on this?

**Comment by Cheesebaron** [comment] 2023-07-07 17:53
Duplicate of #4621

**Closed by Cheesebaron** 2023-07-07 17:53 UTC
Labels: t/bug
