### ISSUE TITLE
ModalViewController dismissed on click native popup

### ISSUE THREAD

**Issue by luigisaggese** [MvvmCross/MvvmCross#2094] opened 2017-08-02 15:11 UTC
I have a MvxViewController defined in that way

[Register("OpenAdvertView")]
[MvxModalPresentation(WrapInNavigationController = true)]
public class OpenAdvertView : MvxViewController<OpenAdvertViewModel>

This ViewController contains inside a WKWebView to show a web page that could have an upload button. When click on a upload button it shows a native popup to upload content from iCloud or Photo. 

Any click on native popup dismiss ViewController
### Steps to reproduce

1. Create a MvxViewController of type MvxModalPresentation

2. Click on web button that open a native element

3. Click on an element of native popup, this dismiss MvxViewController 

### Expected behavior
Dismiss of native popup must not dismiss MvxViewController

### Actual behavior
MvxViewController is dismissed

### Configuration

**Version:** 5.1.1

**Platform:** 
- [x] iOS
- [ ] Android
- [ ] WPF
- [ ] UWP

![simulator screen shot 2 aug 2017 17 05 05](https://user-images.githubusercontent.com/1014210/28880506-8f256792-77a5-11e7-8459-4cd34fa17d2e.png)

**Comment by nmilcoff** [comment] 2017-08-02 15:14
Thanks for reporting this issue. Can you provide us with a small sample where we can follow the steps you mentioned?

**Comment by luigisaggese** [comment] 2017-08-03 10:25
It's inside all flow of my app. But if you do as reported (WebView inside MvxModalPresentation) with a page that have a upload button is easy to replicate

**Comment by martijn00** [comment] 2017-08-03 10:50
Can you make a PR to add this scenario to the Playground project so we can reproduce it?

**Comment by luigisaggese** [comment] 2017-08-04 07:55
It's possible to test with this version of ModalNavView.cs inside Playground Project.

```
using Foundation;
using System;
using UIKit;
using MvvmCross.iOS.Views;
using Playground.Core.ViewModels;
using MvvmCross.Binding.BindingContext;
using MvvmCross.iOS.Views.Presenters.Attributes;
using WebKit;
using CoreGraphics;

namespace Playground.iOS.Views
{
    [MvxFromStoryboard("Main")]
    [MvxModalPresentation(WrapInNavigationController = true)]
    public partial class ModalNavView : MvxViewController<ModalNavViewModel>
    {
		public WKWebView webView;

		public ModalNavView(IntPtr handle) : base(handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            View.BackgroundColor = UIColor.Red;
			webView = new WKWebView(new CGRect(0, 60, View.Frame.Size.Width, View.Frame.Size.Height - 120), new WKWebViewConfiguration());
			webView.BackgroundColor = UIColor.White;
			webView.AllowsBackForwardNavigationGestures = true;

			webView.ScrollView.ScrollEnabled = true;
			//webView.ScrollView.ContentInset = new UIEdgeInsets(0, 0, 64, 0);
			webView.LoadRequest(GenerateRequest("https://joblink.allibo.com/ats4/job-offer.aspx?DM=1310&ID=12525&LN=EN&SG=3&FT=3&MD=1&PRV=46"));
			View.AddSubview(webView);
			View.BackgroundColor = UIColor.Orange;
            var set = this.CreateBindingSet<ModalNavView, ModalNavViewModel>();

            set.Bind(btnShowChild).To(vm => vm.ShowChildCommand);
            set.Bind(btnClose).To(vm => vm.CloseCommand);

            set.Apply();
        }
		Foundation.NSMutableUrlRequest GenerateRequest(string url)
		{
			Uri uri;
			Uri.TryCreate(url, UriKind.Absolute, out uri);

			var nsurl = new NSUrl(uri.GetComponents(UriComponents.HttpRequestUrl, UriFormat.UriEscaped));
			var request = new NSMutableUrlRequest(nsurl);
			request["User-Agent"] = "Mozilla/5.0 (iPhone; U; CPU like Mac OS X; en) AppleWebKit/420+ (KHTML, like Gecko) Version/3.0 Mobile/1A543a Safari/419.3";
			return request;
		}
    }
}
```

**Comment by luigisaggese** [comment] 2017-08-07 08:19
@martijn00 @nmilcoff do you have some workaround or how to try to fix it?

**Comment by luigisaggese** [comment] 2017-08-07 08:44
Maybe MvxNavigationController must check this condition on Dismiss

```
 public override void DismissViewController(bool animated, Action completionHandler)
        {
            if (PresentedViewController != null)
            {
                base.DismissViewController(animated, completionHandler);
            }
        }
```

**Comment by nmilcoff** [comment] 2017-08-13 22:17
After doing some research, I've found the issue has been [reported in WebKit](https://bugs.webkit.org/show_bug.cgi?id=165225) and it has also been solved.

If you're still facing the issue, you should be able to implement the workaround in your own `NavigationController`. To do so with the `MvxIosViewPresenter`, you need to subclass it first, and then override the method [`CreateNavigationController`](https://github.com/MvvmCross/MvvmCross/blob/eef8f2f48187fcd28f2683b7ba8fe532dc92d9a0/MvvmCross/iOS/iOS/Views/Presenters/MvxIosViewPresenter.cs#L301). 

Please notice we can't implement it in MvxNavigationController directly, since it can break other scenarios (the workaround basically modifies the default behavior of `DismissViewController`).

I'm closing this issue, as it isn't directly related to MvvmCross. Please feel free to reopen it if you consider it necessary.

**Closed by nmilcoff** 2017-08-13 22:17 UTC

**Comment by JacobJT** [comment] 2018-07-03 21:00
Sorry for the only tangentially related comment on a closed thread, but this was one of the first pages I stumbled across with the same issue, except with a UIWebView, so I wanted to drop it for anyone else who came across it:

WKWebView has solved the issue when using the image picker controller to take a picture or select from photo library, so if you're using a UIWebView, switch to WKWebView and you should be set. 

Unfortunately, this issue does still exist for the Document selector. As noted, this is only when a webview is inside a ViewController presented modally.
