### ISSUE TITLE
MvxImageView Issue with nested MvxRecyclerView

### ISSUE THREAD

**Issue by bchaitani** [MvvmCross/MvvmCross#1444] opened 2016-09-30 10:05 UTC
I am using nested MvxRecyclerView. The first one has a vertical lineralayout manager and the first row contains a horizontal scrolling MvxRecyclerView.
Both contain MvxImageView in their templates. Some of the images of the horizontal recyclerview disappears when scrolling the main recyclerview view (Vertical Scroll).

Steps to reproduce
1. Scroll fast vertically.

MvvmCross Version 4.3.0
Platform: Android

Sample Project: https://github.com/bchaitani/MvvmCross

**Comment by kjeremy** [comment] 2016-09-30 11:38
Thanks for reporting this. The issue is that we clear the bindings when the
view is detached and that just doesn't work for nested recyclerviews.  I'm
working on a more general fix to the bindings so that we can hopefully
remove that code.

**Comment by kjeremy** [comment] 2016-09-30 22:21
A workaround would be to override `ClearAllBindings` in your `HomeListAdapterand` to just return.  Then override `MvxRecyclerAdapter` and do the same thing.  Example:

```csharp
public override RecyclerView.ViewHolder OnCreateViewHolder(ViewGroup parent, int viewType)
        {
            var holder = base.OnCreateViewHolder(parent, viewType);
            var child = holder.ItemView.FindViewById<MvxRecyclerView>(Resource.Id.cards_recycler_view);
            if (child != null)
            {
                child.Adapter = new DumbAdapter(bindingContext);
                child.SetLayoutManager(new LinearLayoutManager(parent.Context, LinearLayoutManager.Horizontal, false));
            }

            return holder;
        }

        public override void ClearAllBindings()
        {
        }
    } 

    public class DumbAdapter : MvxRecyclerAdapter
    {
        public DumbAdapter(IMvxAndroidBindingContext bindingContext)
            : base(bindingContext)
        {}

        public override void ClearAllBindings()
        {
        }
    }
```

`ClearAllBindings` was added to address memory issues with the `MvxRecyclerView` where there is no reliable place to clear the bindings.  Be warned that if you do this and then wrap everything in a `ViewPager` or similar may cause app crashes.

**Comment by bchaitani** [comment] 2016-10-06 14:42
It is causing an out off memory issue when added a load more option on scroll. Even if I don't use the work around.

**Comment by kjeremy** [comment] 2016-10-06 16:03
You may want to dispose of the image in your viewholder's `OnViewRecycled`

**Comment by bchaitani** [comment] 2016-10-07 06:34
I did override OnViewRecycled as below with disposing the images, and it is still crashing.

`public override void OnViewRecycled(Object holder)
        {
            base.OnViewRecycled(holder);

            var image1 = ((RecyclerView.ViewHolder)holder).ItemView.FindViewById<MvxImageView>(Resource.Id.image1);
            var image2 = ((RecyclerView.ViewHolder)holder).ItemView.FindViewById<MvxImageView>(Resource.Id.image2);

            if (image1 != null)
                image1.Dispose();
            if (image2 != null)
                image2.Dispose();
        }`

**Comment by kjeremy** [comment] 2016-10-07 11:47
You're disposing the image view not the image.

**Comment by bchaitani** [comment] 2016-10-07 11:50
I couldn't access the Image or the Drawable of the Imageview.

**Comment by kjeremy** [comment] 2016-10-07 13:32
Maybe just set the ImageView's drawable to null?

**Comment by kjeremy** [comment] 2016-10-07 13:33
Please push a new version to the github repo that shows the crash and I'll look at it.

**Comment by bchaitani** [comment] 2016-10-09 13:10
I pushed a updated version to the github repo
Sample Project link: [https://github.com/bchaitani/MvvmCross](url)

**Comment by kjeremy** [comment] 2016-11-24 16:42
@bchaitani does this still happen with 4.4?

**Comment by kjeremy** [comment] 2016-12-20 16:27
This should be fixed with the WeakReferences + the removal of views when the RecyclerView is detached.  If it is not then reopen.

**Closed by kjeremy** 2016-12-20 16:27 UTC
Labels: Android, AndroidSupport, Needs investigation
