### ISSUE TITLE
New nav service "deep link" conflict with viewmodel parameters when param is string

### ISSUE THREAD

**Issue by softlion** [MvvmCross/MvvmCross#2080] opened 2017-07-28 16:41 UTC
If a viewmodel derive from MvxViewModel<string>, sending a string parameter never works, as it is interpreted as a deep link instead.

### Steps to reproduce

1. Create a viewmodel B deriving from MvxViewModel<string>, override its Initialize(string xxx) method

2. From another viewmodel A, navigate to the viewmodel B using the navigation service. nav.Navigate<B,string>("test");

3. Using the debugger, cerify that Initialize(string) is not called at all, or that its parameter is not "test".

### Expected behavior
Initialize is call and its parameter is "test"

### Actual behavior
Initialize is not called

### Configuration
**Version:** 5.1
**Platform:** 
- [x] iOS
- [ ] Android
- [ ] WPF
- [ ] UWP

**Comment by martijn00** [comment] 2017-07-28 18:41
I've tried to reproduce this, but this exact situation is working in our test projects. Please provide more details. Also i don't see how this has anything to do with deeplinking

**Comment by softlion** [comment] 2017-07-29 10:10
Which test project are you using ? Will try it.

**Comment by martijn00** [comment] 2017-07-29 12:46
I'm using the routingsample. I modified the `TestAViewModel` to receive a string and pass one into it on the `MainViewModel`. That seems to work fine on both iOS and Android.

**Comment by ferrydeboer** [comment] 2017-09-02 15:08
So I tried to repro this in a test. By now the api's have changed and Initialize has become prepare. But in order to get this to compile as you subscribe. `Navigate<B, string>("test");` requires B to implement IMvxViewModel<string> which in turn requires you to implement Prepare(string param).

This is called when doing `Navigate<B, string>("test");` Prepare is called with "test"

**Comment by nmilcoff** [comment] 2017-10-13 02:30
Closing this as @ferrydeboer did some tests and couldn't reproduce the issue.

**Closed by nmilcoff** 2017-10-13 02:30 UTC
