### ISSUE TITLE
MvxNavigationService.Navigate(Type) returns before completing

### ISSUE THREAD

**Issue by borbmizzet** [MvvmCross/MvvmCross#2827] opened 2018-04-23 22:34 UTC
### Steps to reproduce :scroll:

1. Bind a button on a NavigationPage to 
`public IMvxCommand Command1 => new MvxCommand(() => _mvxNotifyTask = MvxNotifyTask.Create(() => _mvxNavigationService.Navigate(typeof(OtherViewModel))),
() => _mvxNotifyTask is null || !_mvxNotifyTask .IsNotCompleted)`

OR

`IMvxAsyncCommand command => new MvxAsyncCommand(() => _mvxNavigationService.Navigate(typeof(OtherViewModel)))`

2. Press the button rapidly.

### Expected behavior :thinking:
After the first press, a single OtherPage should be navigated to and any subsequent presses before it displays should not be allowed to execute

### Actual behavior :bug:
MvxNavigationService.Navigate() returns before the new page appears, and the command is triggered multiple times, thus constructing, initializing, and pushing multiple instances of OtherPage onto the navigation stack.

### Configuration :wrench:

**Version:** 6.0

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by nickrandolph** [comment] 2018-04-23 23:12
Is this a duplicate of this: https://github.com/MvvmCross/MvvmCross/issues/2740
(or at least the same cause)

**Comment by borbmizzet** [comment] 2018-04-24 13:51
I don't think so.  This is about returning before even displaying the view.

**Comment by nmilcoff** [comment] 2018-04-24 13:53
You're right on that @borbmizzet, but the cause is the same. Not really a duplicate but both issues are related 🙂

**Comment by nickrandolph** [comment] 2018-08-09 05:12
This should be fixed in v6.2

**Closed by nickrandolph** 2018-08-09 05:12 UTC

**Comment by DaniusLabs** [comment] 2020-01-02 15:10
I can still reproduce wit. MvvmCross 6.4.1?!
