### ISSUE TITLE
MvxAppCompatDialogFragment Attempt to invoke virtual method on a null object reference

### ISSUE THREAD

**Issue by tbalcom** [MvvmCross/MvvmCross#2378] opened 2017-11-10 20:04 UTC
MvxAppCompatDialogFragment Attempt to invoke virtual method 'android.support.v4.app.FragmentTransaction android.support.v4.app.FragmentManager.beginTransaction()' on a null object reference

[GitHub repository demonstrating the problem](https://github.com/tbalcom/MvxDialogBackButton). See `RotateCrashViewModel` & `RotateCrashFragment`.

### Steps to reproduce :scroll:

1. Launch the application.

2. Click the "Show Dialog" button.

3. Rotate the screen any number of times.

4. Click the "Close" button in the dialog. Observe an unhandled exception with the following stack trace:

```
 UNHANDLED EXCEPTION:
 Java.Lang.NullPointerException: Attempt to invoke virtual method 'android.support.v4.app.FragmentTransaction android.support.v4.app.FragmentManager.beginTransaction()' on a null object reference
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
   at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method) [0x00088] in <7cfbebb561c54efc9010b018c0846c7e>:0 
   at Android.Runtime.JNIEnv.CallNonvirtualVoidMethod (System.IntPtr jobject, System.IntPtr jclass, System.IntPtr jmethod) [0x00015] in <e975227ac8644a30bb0866117325de0d>:0 
   at Android.Support.V4.App.DialogFragment.DismissAllowingStateLoss () [0x00079] in <7e083afc7c9045f59e01d9c14931060d>:0 
   at MvvmCross.Droid.Support.V7.AppCompat.MvxAppCompatDialogFragment.DismissAllowingStateLoss () [0x00000] in C:\projects\mvvmcross\MvvmCross-AndroidSupport\MvvmCross.Droid.Support.V7.AppCompat\MvxAppCompatDialogFragment.cs:115 
   at MvvmCross.Droid.Support.V7.AppCompat.MvxAppCompatViewPresenter.CloseFragmentDialog (MvvmCross.Core.ViewModels.IMvxViewModel viewModel, MvvmCross.Droid.Views.Attributes.MvxDialogFragmentPresentationAttribute attribute) [0x00010] in C:\projects\mvvmcross\MvvmCross-AndroidSupport\MvvmCross.Droid.Support.V7.AppCompat\MvxAppCompatViewPresenter.cs:462 
   at MvvmCross.Droid.Views.MvxAndroidViewPresenter.<RegisterAttributeTypes>b__34_5 (MvvmCross.Core.ViewModels.IMvxViewModel viewModel, MvvmCross.Core.Views.MvxBasePresentationAttribute attribute) [0x00000] in C:\projects\mvvmcross\MvvmCross\Droid\Droid\Views\MvxAndroidViewPresenter.cs:165 
   at MvvmCross.Droid.Views.MvxAndroidViewPresenter.Close (MvvmCross.Core.ViewModels.IMvxViewModel viewModel) [0x00042] in C:\projects\mvvmcross\MvvmCross\Droid\Droid\Views\MvxAndroidViewPresenter.cs:555 
   at MvvmCross.Droid.Views.MvxAndroidViewPresenter.ChangePresentation (MvvmCross.Core.ViewModels.MvxPresentationHint hint) [0x00014] in C:\projects\mvvmcross\MvvmCross\Droid\Droid\Views\MvxAndroidViewPresenter.cs:536 
   at MvvmCross.Droid.Views.MvxAndroidViewDispatcher+<>c__DisplayClass3_0.<ChangePresentation>b__0 () [0x00000] in C:\projects\mvvmcross\MvvmCross\Droid\Droid\Views\MvxAndroidViewDispatcher.cs:31 
   at MvvmCross.Droid.Views.MvxAndroidMainThreadDispatcher.RequestMainThreadAction (System.Action action, System.Boolean maskExceptions) [0x00020] in C:\projects\mvvmcross\MvvmCross\Droid\Droid\Views\MvxAndroidMainThreadDispatcher.cs:20 
   at MvvmCross.Droid.Views.MvxAndroidViewDispatcher.ChangePresentation (MvvmCross.Core.ViewModels.MvxPresentationHint hint) [0x00014] in C:\projects\mvvmcross\MvvmCross\Droid\Droid\Views\MvxAndroidViewDispatcher.cs:31 
   at MvvmCross.Core.Navigation.MvxNavigationService.Close (MvvmCross.Core.ViewModels.IMvxViewModel viewModel) [0x0000f] in C:\projects\mvvmcross\MvvmCross\Core\Core\Navigation\MvxNavigationService.cs:385 
   at MvxDialogBackButton.Core.ViewModels.RotateCrashViewModel.OnCloseAsync () [0x00001] in E:\src\MvxDialogBackButton\MvxDialogBackButton\MvxDialogBackButton.Core\ViewModels\RotateCrashViewModel.cs:20 
   at MvvmCross.Core.ViewModels.MvxAsyncCommand+<>c__DisplayClass2_0.<.ctor>b__0 (System.Threading.CancellationToken cancellationToken) [0x00000] in C:\projects\mvvmcross\MvvmCross\Core\Core\ViewModels\MvxAsyncCommand.cs:183 
   at MvvmCross.Core.ViewModels.MvxAsyncCommand.ExecuteAsyncImpl (System.Object parameter) [0x00000] in C:\projects\mvvmcross\MvvmCross\Core\Core\ViewModels\MvxAsyncCommand.cs:201 
   at MvvmCross.Core.ViewModels.MvxAsyncCommandBase+<ExecuteConcurrentAsync>d__17.MoveNext () [0x000a9] in C:\projects\mvvmcross\MvvmCross\Core\Core\ViewModels\MvxAsyncCommand.cs:114 
 --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () [0x00000] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
   at MvvmCross.Core.ViewModels.MvxAsyncCommandBase+<ExecuteAsync>d__16.MoveNext () [0x00040] in C:\projects\mvvmcross\MvvmCross\Core\Core\ViewModels\MvxAsyncCommand.cs:81 
 --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () [0x00000] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
   at MvvmCross.Core.ViewModels.MvxAsyncCommandBase+<Execute>d__14.MoveNext () [0x00096] in C:\projects\mvvmcross\MvvmCross\Core\Core\ViewModels\MvxAsyncCommand.cs:68 
 --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) [0x00000] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
   at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <e975227ac8644a30bb0866117325de0d>:0 
   at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <e975227ac8644a30bb0866117325de0d>:0 
   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <e975227ac8644a30bb0866117325de0d>:0 
   at (wrapper dynamic-method) System.Object:36a6f093-edda-4ec6-9cdb-653a943b59d2 (intptr,intptr)
   --- End of managed Java.Lang.NullPointerException stack trace ---
 java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.v4.app.FragmentTransaction android.support.v4.app.FragmentManager.beginTransaction()' on a null object reference
 	at android.support.v4.app.DialogFragment.dismissInternal(DialogFragment.java:200)
 	at android.support.v4.app.DialogFragment.dismissAllowingStateLoss(DialogFragment.java:181)
 	at mono.android.view.View_OnClickListenerImplementor.n_onClick(Native Method)
 	at mono.android.view.View_OnClickListenerImplementor.onClick(View_OnClickListenerImplementor.java:30)
 	at android.view.View.performClick(View.java:5612)
 	at android.view.View$PerformClick.run(View.java:22285)
 	at android.os.Handler.handleCallback(Handler.java:751)
 	at android.os.Handler.dispatchMessage(Handler.java:95)
 	at android.os.Looper.loop(Looper.java:154)
 	at android.app.ActivityThread.main(ActivityThread.java:6154)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
```

### Expected behavior :thinking:
The dialog should close successfully even if the screen was rotated.

### Actual behavior :bug:
The dialog crashes when `IMvxNavigationService.Close()` is called on the ViewModel. The crash is triggered if you rotate the screen at least once. The crash is avoided if you don't rotate the screen.

### Configuration :wrench:

**Version:** 
MvvmCross 5.4.2
Targeting Android 8.0
Xamarin 4.7.10.38 (34c1b6c)
Xamarin.Android SDK 8.0.2.1 (HEAD/c2a33d8ea)
Visual Stuido 2017 15.4.3

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Nickolas-** [comment] 2017-11-19 17:12
HI, 

It is a because 
   

>     protected virtual ConditionalWeakTable<IMvxViewModel, DialogFragment> Dialogs { get; } = new ConditionalWeakTable<IMvxViewModel, DialogFragment>();

still hold a reference on it. I guess it's a question to @martijn00. The problem is we still hold a reference on MCW but in JVM Fragment is dead. For right now if it a stopper, just add in constructor a `RetainInstance = true;` and override OnDestroyView , so you dialog won't disappear after rotation.

```
public override void OnDestroyView()
        {
            if (Dialog != null && RetainInstance)
            {
                Dialog.SetDismissMessage(null);
            }
            base.OnDestroyView();
        }
```

@martijn00  I guess ConditionWeakTable wouldn't help is such situation. It just wouldn't provide 
any information about objects in JVM , if it still alive. I guess we need to think in other way. I like better a old approach.

Nick

**Comment by nmilcoff** [comment] 2018-01-07 00:31
I confirm this issue is reproducible in our `TestProjects/Playground.Droid ` by simply opening "ModalView" and rotating the screen.

Also the workaround suggested by @Nickolas- works.

**Comment by aaaabcv** [comment] 2018-02-06 17:55
Hi @nmilcoff, I think I found some issue which might be related. In the current version of the presenter (AppCompat), there is the code to close a DialogFragment. This code additionally calls Dispose() on the Fragment. (https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross.Android.Support/V7.AppCompat/MvxAppCompatViewPresenter.cs:473 Method CloseFragmentDialog)

This Dispose() Method belongs to Java.Lang.Object and dissociates the Java Object with the Mono Managed Object allowing the JVM to collect the object. But doing so also requires a new instance to be recovered when there are any callbacks to the dialog fragment.
I figured, that if you call Dispose() the fragment's constructor will be called with the JniHandle and transfer parameters. But any members are not restored since the original Mono instance is not associated with the java object anymore. Instead a clean new instance is created this way.
This leaves most members assigned to null and caused problems - at least in my case.

I did not test this specific case but I think that it could be related. I removed the call to Dispose() from the presenter and my issue was solved as the old Mono Manager instance was still associated with the Java Object when OnDestroy / OnDismissed, etc. was called.

Could you please review the call to Dispose()?

**Comment by aaaabcv** [comment] 2018-02-21 22:32
Ok, while my previous comment is valid it does not present the root cause of the crash.
I digged a bit deeper and found that there is a map in the presenter caching all the Dialogs along their viewmodels.
If Close is invoked, the DialogFragment of the cache is taken and disposed of using DismissAllowingStateLoss.
But: If the activity Hosting the Fragment has been destroyed (e.g. by rotating), the Fragment instance in the Dialogs map/Cache is the "old" ony which has been previously lived in the already destroyed Activity. As such, it has been destroyed too. Invoking Close and calling Dismiss on this instance causes the Crash.
Instead relying on the Dialogs Cache, I'd recommend changing the Code of the presenter and search in the current FragmentManager for an instance of the tag to get the living Fragment, similar like that:


```
protected override bool CloseFragmentDialog(IMvxViewModel viewModel, MvxDialogFragmentPresentationAttribute attribute)
        {
            if (Dialogs.TryGetValue(viewModel, out DialogFragment dialog))
            {
                string tag = FragmentJavaName(dialog.GetType());
                dialog = CurrentFragmentManager.FindFragmentByTag(tag) as DialogFragment;
                dialog.DismissAllowingStateLoss();
                Dialogs.Remove(viewModel);
                return true;
            }
            return false;
        }
```

I'm not so deep in the whole Topic, so please Review it and opt to implement the changes. For my personal Tests I found this Code sufficient.

**Comment by nmilcoff** [comment] 2018-03-21 04:04
This happens on "pure" Android too. PR incoming

**Closed** 2018-03-21 05:59 UTC
Labels: Android, AndroidSupport, Bug
