### ISSUE TITLE
Playground.Droid can't navigate to RootViewModel

### ISSUE THREAD

**Issue by tbalcom** [MvvmCross/MvvmCross#3083] opened 2018-08-31 14:48 UTC
## 🐛 Bug Report
`MvxDefaultViewModelLocator.RunViewModelLifecycle(IMvxViewModel viewModel, IMvxBundle parameterValues, IMvxBundle savedState, IMvxNavigateEventArgs navigationArgs)` is throwing a NullReferenceException because `navigationArgs` is null.

> MvvmCross.Exceptions.MvxException: Problem navigating to ViewModel RootViewModel ---> MvvmCross.Exceptions.MvxException: Failed to construct and initialize ViewModel for type Playground.Core.ViewModels.RootViewModel from locator MvxDefaultViewModelLocator - check InnerException for more information ---> MvvmCross.Exceptions.MvxException: Problem running viewModel lifecycle of type RootViewModel ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at MvvmCross.ViewModels.MvxDefaultViewModelLocator.RunViewModelLifecycle (MvvmCross.ViewModels.IMvxViewModel viewModel, MvvmCross.ViewModels.IMvxBundle parameterValues, MvvmCross.ViewModels.IMvxBundle savedState, MvvmCross.Navigation.EventArguments.IMvxNavigateEventArgs navigationArgs) [0x0001d] in E:\src\MvvmCross\MvvmCross\ViewModels\MvxDefaultViewModelLocator.cs:103 
    --- End of inner exception stack trace ---
   at MvvmCross.ViewModels.MvxDefaultViewModelLocator.RunViewModelLifecycle (MvvmCross.ViewModels.IMvxViewModel viewModel, MvvmCross.ViewModels.IMvxBundle parameterValues, MvvmCross.ViewModels.IMvxBundle savedState, MvvmCross.Navigation.EventArguments.IMvxNavigateEventArgs navigationArgs) [0x000af] in E:\src\MvvmCross\MvvmCross\ViewModels\MvxDefaultViewModelLocator.cs:123 
   at MvvmCross.ViewModels.MvxDefaultViewModelLocator.Load (System.Type viewModelType, MvvmCross.ViewModels.IMvxBundle parameterValues, MvvmCross.ViewModels.IMvxBundle savedState, MvvmCross.Navigation.EventArguments.IMvxNavigateEventArgs navigationArgs) [0x00033] in E:\src\MvvmCross\MvvmCross\ViewModels\MvxDefaultViewModelLocator.cs:63 
   at MvvmCross.ViewModels.MvxViewModelLoader.LoadViewModel (MvvmCross.ViewModels.MvxViewModelRequest request, MvvmCross.ViewModels.IMvxBundle savedState, MvvmCross.Navigation.EventArguments.IMvxNavigateEventArgs navigationArgs) [0x0003b] in E:\src\MvvmCross\MvvmCross\ViewModels\MvxViewModelLoader.cs:73 
    --- End of inner exception stack trace ---
   at MvvmCross.ViewModels.MvxViewModelLoader.LoadViewModel (MvvmCross.ViewModels.MvxViewModelRequest request, MvvmCross.ViewModels.IMvxBundle savedState, MvvmCross.Navigation.EventArguments.IMvxNavigateEventArgs navigationArgs) [0x00051] in E:\src\MvvmCross\MvvmCross\ViewModels\MvxViewModelLoader.cs:77 
   at MvvmCross.Navigation.MvxNavigationService+<Navigate>d__53.MoveNext () [0x0003c] in E:\src\MvvmCross\MvvmCross\Navigation\MvxNavigationService.cs:394 
 --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <43dbbdc147f2482093d8409abb04c233>:0 
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <43dbbdc147f2482093d8409abb04c233>:0 
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <43dbbdc147f2482093d8409abb04c233>:0 
   at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <43dbbdc147f2482093d8409abb04c233>:0 
   at MvvmCross.ViewModels.MvxAppStart`1+<NavigateToFirstViewModel>d__1[TViewModel].MoveNext () [0x00038] in E:\src\MvvmCross\MvvmCross\ViewModels\MvxAppStart.cs:79 
    --- End of inner exception stack trace ---
   at MvvmCross.ViewModels.MvxAppStart`1+<NavigateToFirstViewModel>d__1[TViewModel].MoveNext () [0x0009a] in E:\src\MvvmCross\MvvmCross\ViewModels\MvxAppStart.cs:83 
 --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <43dbbdc147f2482093d8409abb04c233>:0 
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <43dbbdc147f2482093d8409abb04c233>:0 
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <43dbbdc147f2482093d8409abb04c233>:0 
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <43dbbdc147f2482093d8409abb04c233>:0 
   at MvvmCross.ViewModels.MvxAppStart+<StartAsync>d__5.MoveNext () [0x000f4] in E:\src\MvvmCross\MvvmCross\ViewModels\MvxAppStart.cs:43 
 --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <43dbbdc147f2482093d8409abb04c233>:0 
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <43dbbdc147f2482093d8409abb04c233>:0 
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <43dbbdc147f2482093d8409abb04c233>:0 
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <43dbbdc147f2482093d8409abb04c233>:0 

### Expected behavior
RootViewModel should be displayed when Playground.Droid is started.

### Reproduction steps
Build Playground.Droid on current develop branch and start it.

### Configuration

**Version:** 6.2.0

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by MartinZikmund** [comment] 2018-09-02 08:28
Can confirm this affects all platforms, your proposed solution fixes them all, not just Android :-)

**Comment by markuspalme** [comment] 2018-09-04 18:58
I can confirm that this fixed the problem for Android. But is this solving the problem at the root cause? Do we understand why the `navigationArgs` are suddenly null?

**Comment by tbalcom** [comment] 2018-09-04 19:51
We probably need some input from @nickrandolph here. `navigationArgs` was recently added in PR #3046.

**Comment by nmilcoff** [comment] 2018-09-04 20:31
Well, looking at the source code, `null` is the default value there (the parameter is marked as optional only on the interface and not on the implementation). So I think the PR is good. But we better wait until he reviews it

**Comment by nickrandolph** [comment] 2018-09-04 22:11
The PR is good but I agree that there is a concern as to why the value is null. Think we need to investigate that before closing this issue.

**Closed** 2018-09-12 08:28 UTC
