### ISSUE TITLE
`Navigate<TResult>` unable to handle app suspension / tombstoning

### ISSUE THREAD

**Issue by ElteHupkes** [MvvmCross/MvvmCross#2458] opened 2017-12-11 14:14 UTC
(Sorry for abandoning the issue template, but this fits an open story format a bit better).

The new result passing mechanism using `IMvxNavigationService.Navigate<TResult>(...)` in combination with `IMvxNavigationService.Close<TResult>(...)` is very nice in theory, but can fundamentally never support app tombstoning / suspension. I can think of (and have experienced both myself and from our users) several scenarios in which this is relevant:

- Switching to another app in a low memory scenario during data entry, e.g. to check something or when receiving a phone call.
- Pressing the sleep button on the phone because of an interruption (or accidentally)
- Just general sloppiness leaving a data entry or selection screen for another app and returning to it later

This works out fine in some cases if the service layer is still in tact, but in many others only app state is persisted and all memory is purged. When the receiving view model is revived there is of course no way to restore its state to where it was awaiting so no result passing will take place, resulting in confusion and possibly data loss or errors if you're unlucky. 

Now if you know and understand all this then you might either choose to ignore it (it'll still only affect a small percentage of users) or work around it, but I'm guessing most people don't think about it, which means most people will implement an encouraged navigation pattern that doesn't support all cases. 

Personally I use a different approach, which I've isolated and explained in [this repository](https://github.com/ElteHupkes/MvxViewModelCommunication). I'm not saying MvvmCross should adopt this approach by default, I'm mostly interested in raising a bit of awareness about the issue.

**Comment by aaaabcv** [comment] 2018-01-07 18:40
I think you are right regarding the problem. 
Further, I think that destroyed ViewModels are ust one problem. If you consider that the whole process is killed (Android) I highly doubt that MvvmCross can restore the activity state completely as the initial Setup will need to be executed which in response will trigger the first navigation etc.
Since this situation is only likely to occur if the application has been dormant in the background a while I belive it might be acceptable. 
A more sever problem is the destruction of Views during presence of other activities. This can be easily the case if e.g. a camera app or picture chooser is invoked which typically puts high memory pressure on the app during image processing. As such the system will try to destroy not visible activities.
Your approach is one, another approach could be to also cache ViewModels awaiting a result. I debugged a bit and it appears that there is only a cache present which can hole a single ViewModel. If a parent Activity is destroyed, it's viewmodel is not cached. But since that viewmodel is awaiting a response from the child viewmodel is still lives in memory. But when navigating back a new ViewModel instance is created, it's state restored and the original ViewModel instance receives the result.
So one view of the problem could also be that the ViewModel should "live" as long it is waiting for a result and re-used instead of a new viewmodel being created.

**Comment by ElteHupkes** [comment] 2018-01-08 13:18
Restoring the entire state actually works just fine. Setup and AppStart are separated, initial navigation is triggered by `MvxSplashScreenActivity`. Each `MvxActivity` will make sure that Setup has happened in `OnCreate`, likewise for fragment activities.

ViewModel caches are kind of ugly and also kind of detrimental if the system is trying to clear memory. In my experience the view model cache is the main source of memory leaks / unexpected lingering event handlers. I see how it's necessary for activity recreation when the phone is rotated, but I'm not a fan of caching even more view models. Also, suspending entire applications seems to happen quite rapidly on my phone if I have many of them open. My phone's not the newest but it's definitely not old (Xperia X Compact). Plus why not cater for all possible scenarios if we can?

**Comment by aaaabcv** [comment] 2018-01-08 13:56
You're right. The async navigation pattern never can support thombstoning completely and I think your approach is completely valid. I didn't know that it happens that often (I don't use a Droid for typical usage,  just for development). 
On the other hand, I think viewmodel caching is quite valid since why serializing and deserializing all that stuff if it could be kept alive? If you look ad the newly added ViewModel approach of Android, you'dd recognize that they too have a kind of cache (ViewModelProviders) which associate Activities to ViewModels. It might be even benificial to use the AndroidViewModel as container to cache the MxvViewModel instances instead of the Mvx cache.
https://developer.android.com/topic/libraries/architecture/viewmodel.html

**Comment by ElteHupkes** [comment] 2018-01-09 16:13
Interesting, I didn't know about the Android ViewModel stuff! I'm going to read into that. It's a valid point that any (de)serialization that can be skipped is a good thing. The current behavior is kind of confusing though, I remember I once went down the rabbit hole of finding out where my view models were cached and found two separate single view model caches for separate scenarios. Don't have the specifics right now, maybe I need to go down that rabbit hole again ;).

**Comment by ornolisvt** [comment] 2018-04-05 17:05
I have the same issue but it happens randomly. However I have been able to reproduce it in the following way:

From a notification I use
await NavigationService.Navigate<ViewModel, TModel>(data);

In the ViewModel runs smoothly Prepare
public override void Prepare (TModel parameter)

Then execute ViewCreated
public override void ViewCreated ()
{
            base.ViewCreated ();
            LoadCommand.Execute (null);
}

LoadCommand makes a call to a REST service but since the user is not logged not have Token to access the service, therefore from that call it is navigated to
Navigate <LoginViewModel> (presentationBundle: new MvxBundle (new Dictionary <string, string> {{"NavigationMode", "BackOrInPlace"}}));
Navigating to Login view leaving it as unique in the stack with the parameters passed in the bundle

I log in and when try to navigate to the initial viewmodel
await NavigationService.Navigate <ViewModel, TModel> (data);
Just run Prepare (TModel parameter) and stay in the same view

I do not know why this happens, you can help me?
Thanks

**Comment by nickrandolph** [comment] 2018-08-09 21:54
@ElteHupkes I think with v6.2 we should be in a better position to handle this. Can you repro this scenario with the Playground sample and submit as a PR so that we can review

**Comment by ElteHupkes** [comment] 2018-08-10 07:32
@nickrandolph Interesting, how was this approached? (no need to explain everything, but some pointers to source code would be nice).

I'd like to help (and I think I still owe you a repro on another issue if I'm not mistaken) but my problem is a lack of a workable Windows installation at the moment, and last I checked I couldn't build the Playground on Mac. As soon as I've mustered up the will to dedicate an afternoon (let's not pretend it takes any less time than that) to getting my VS on Windows back in a state where it doesn't freeze for 10 seconds after each key stroke I'll be very happy to check it out...

**Comment by ElteHupkes** [comment] 2018-09-05 10:29
Okay, I've setup my Windows environment (half a day), produced a working emulator (another half a day; still, every second build fails to deploy. Seriously, I used to work on Windows, this is far worse than I remember) and produced a navigation sample in the Playground (about 10 minutes). However, whether it is Playground.Droid or something with the emulator on Windows, my usual approach to testing what happens when the entire process is gone (which is killing the process through ADB with "Don't keep activities on" and the target activity minimized) doesn't work. Forcing the emulator into IDLE mode either renders the emulator unresponsive, doesn't end the process or both (depending on the emulator). Meanwhile Visual Studio just keeps on crashing, right now I can't deploy anything anymore, it just hangs.

I'm afraid I'm going to have to shelve this project again to protect my mental sanity. FWIW, the branch I was working on is located here: https://github.com/ElteHupkes/MvvmCross/tree/issues/2458-data-navigation-tombstoning.

**Comment by SSElliott** [comment] 2018-12-19 10:37
I came across this problem a few days ago when, my solution was to write my own mini-message hub, that unlike MvxMessenger kept the message if it is not got any subscribers, and publishes immediately on a subscribe when a ViewModel is restored. I found the ViewCreatedView the best place to do this with android as it gets around Widgets remembering their state.

**Comment by ElteHupkes** [comment] 2018-12-19 17:19
@SSElliot I've done view model communication with a messenger hub in the past, but personally I find it kind of a drag; too many edge cases where view models that weren't quite garbage collected yet would snag up a message not intended for them. Of course my solution isn't fundamentally different from a messenger except it is a bit more targeted. If this works in your scenario though, great!

**Comment by SSElliott** [comment] 2018-12-19 17:30
@ElteHupkes You are right about that. In a single application I have to be super careful to unsubscribe  when Views are destroyed. I look forward to when this is addressed in a future release (6.3?). Looking at the source though I am not sure how the current Async technique can ever work in its current form. Incorporating the structure of your solution might be the longer term fix. 

Steven

**Comment by Hackmodford** [comment] 2021-06-29 16:38
I have just ran into this issue.

I am able to reproduce it on a simulator by opening the task switcher on android.

For example if I am awaiting this line:
```var result = await _navigationService.Navigate<LoginViewModel, bool>();```

The result comes back as false as soon as the task switcher is opened.

**Closed** 2023-07-20 20:26 UTC
Labels: t/bug, s/needs-investigation
