### ISSUE TITLE
Error installing MvvmCross.HotTuna.MvvmCrossLibraries v4.0.0-beta1 in Xamarin Studio

### ISSUE THREAD

**Issue by michaeldaw** [MvvmCross/MvvmCross#1088] opened 2015-08-08 00:53 UTC
I attempted to use Nuget to install MvvmCross.HotTuna.MvvmCrossLibraries 4.0.0-beta1 in Xamarin Studio 5.9.4 (mac or windows), and the following error was displayed on the package manager console:
```
Adding MvvmCross.HotTuna.MvvmCrossLibraries...
Attempting to resolve dependency 'MvvmCross.HotTuna.CrossCore (= 4.0.0-beta1)'.
Downloading MvvmCross.HotTuna.CrossCore 4.0.0-beta1...
'MvvmCross.HotTuna.CrossCore' already has a dependency defined for 'MvvmCross.HotTuna.Binding'.
```
It seems like it must be something to do with the modifications to the nuspec files that allow operation with Visual Studio 2015.

**Comment by Cheesebaron** [comment] 2015-08-08 14:29
The problem is the NuGet client så.

**Comment by jamsoft** [comment] 2015-08-12 15:58
Michael did you get anywhere with this?  I'm having the same issues in VS2012 and I'm already on the latest version of NuGet.

**Comment by michaeldaw** [comment] 2015-08-12 16:53
I've only attempted it with VS2015, which seems to work fine. VS2015 uses Nuget version 3.0 whereas the highest version of Nuget for previous versions of VS is 2.8.6, if I'm not mistaken. That could be part of the problem.
As for Xamarin Studio, I don't know enough about it to upgrade the version of Nuget distributed with the IDE. I'm waiting for an update from Xamarin.

These are the release notes for the two recent releases of Nuget:
http://docs.nuget.org/release-notes/nuget-3.0.0
http://docs.nuget.org/release-notes/nuget-2.8.6

**Comment by jamsoft** [comment] 2015-08-12 16:55
Thanks for that Michael, I'm chatting with Martijn at the mo trying to get to the bottom of what's going on.

**Comment by martijn00** [comment] 2015-08-12 18:44
Download the official nuget command line tool: https://nuget.org/nuget.exe
Place that one in C:/
Open command prompt.
Move to C disk: cd c:/
Install the packages: nuget Install MvvmCross -Pre

For update you probably need to do some different commands. See here for the documentation: https://docs.nuget.org/Consume/Command-Line-Reference#Restore-command

**Comment by kiliman** [comment] 2015-08-19 20:06
This is still an issue. Since Xamarin doesn't support NuGet 2.8.6, I tried @martijn00 suggestion for installing it from the command line. Even with the latest version, I'm unable to install.

	D:\>nuget
	NuGet Version: 2.8.60318.667

	D:\>nuget install MvvmCross -Pre
	Attempting to resolve dependency 'MvvmCross.HotTuna.StarterPack (≥ 4.0.0-beta2)'
	.
	'MvvmCross.HotTuna.StarterPack' already has a dependency defined for 'MvvmCross.
	HotTuna.MvvmCrossLibraries'.

**Comment by martijn00** [comment] 2015-08-19 20:11
@kiliman you need at least 2.8.60717.93 

You could also try the workaround of @mrward http://forums.xamarin.com/discussion/comment/147377/#Comment_147377

**Comment by kiliman** [comment] 2015-08-19 20:14
Thanks I see that. I had downloaded the current one, but when I ran the command, it was picking up the older one from my PATH. I've updated all to latest and it appears to be working.

Thanks!

**Comment by kiliman** [comment] 2015-08-19 20:46
I tried installing the update NuGet Add-in for Xamarin Studio and got the same error you did. So I opened up the solution in VS 2015 and tried to install the MvvmCross package into my PCL project. I got this error:

	PM> Install-Package MvvmCross -pre
	Attempting to gather dependencies information for package 'MvvmCross.4.0.0-beta2' with respect to project 'CheesesquareCross.Core', targeting '.NETPortable,Version=v4.5,Profile=Profile111'
	Attempting to resolve dependencies for package 'MvvmCross.4.0.0-beta2' with DependencyBehavior 'Lowest'
	Resolving actions to install package 'MvvmCross.4.0.0-beta2'
	Resolved actions to install package 'MvvmCross.4.0.0-beta2'
	Added package 'MvvmCross.HotTuna.Binding.4.0.0-beta2' to 'packages.config'
	Successfully installed 'MvvmCross.HotTuna.Binding 4.0.0-beta2' to CheesesquareCross.Core
	Added package 'MvvmCross.HotTuna.CrossCore.4.0.0-beta2' to 'packages.config'
	Successfully installed 'MvvmCross.HotTuna.CrossCore 4.0.0-beta2' to CheesesquareCross.Core
	Added package 'MvvmCross.HotTuna.MvvmCrossLibraries.4.0.0-beta2' to 'packages.config'
	Successfully installed 'MvvmCross.HotTuna.MvvmCrossLibraries 4.0.0-beta2' to CheesesquareCross.Core
	Install failed. Rolling back...
	Package 'MvvmCross.HotTuna.StarterPack 4.0.0-beta2' does not exist in project 'CheesesquareCross.Core'
	Removed package 'MvvmCross.HotTuna.MvvmCrossLibraries 4.0.0-beta2' from 'packages.config'
	Removed package 'MvvmCross.HotTuna.CrossCore 4.0.0-beta2' from 'packages.config'
	Removed package 'MvvmCross.HotTuna.Binding 4.0.0-beta2' from 'packages.config'
	Install-Package : Could not find a part of the path 
	'C:\Users\Michael\.nuget\packages\MvvmCross.HotTuna.StarterPack\4.0.0-beta2\content\portable-win%2Bnet45%2Bwp8%2Bwin8%2Bwpa81\ViewModels\FirstViewModel.cs.pp'.


I looked and that file does exist, but the foldername uses + instead %2B. Not sure if that's an issue. Anyway, I ended up just installing the MvvmCrossLibraries package and manually creating App.cs and ViewModels.

I realize that 4.0 is a beta release, but we seriously need to get the "First Run" experience much better.

**Comment by mrward** [comment] 2015-08-20 10:56
The problem with Xamarin Studio 5.9.5 not being able to install MvvmCross.HotTuna.CrossCore version 4.0.0-beta1 is because its version of NuGet (2.8.5) is not aware of the UAP target framework. The MvvmCross.HotTuna.CrossCore 4.0.0-beta1 has a `<group targetFramework="UAP0.0">` in its .nuspec and this causes the `'MvvmCross.HotTuna.CrossCore' already has a dependency defined for 'MvvmCross.HotTuna.Binding'.` error.

In 4.0.0-beta2 the UAP group dependency has been removed so that can be installed in Xamarin Studio 5.9.5.

To support UAP in Xamarin Studio 5.9.5 currently the workaround is to manually upgrade the [NuGet addin files](http://forums.xamarin.com/discussion/comment/147377/#Comment_147377).

The `Could not find a part of the path ` error in Visual Studio 2015 is a [bug in NuGet 3](https://github.com/NuGet/Home/issues/1087) which looks like it will be fixed in NuGet 3.2.

**Comment by kiliman** [comment] 2015-08-20 14:21
@mrward Thanks for the info, but I'm not able to get your addin files to work with XS 5.9.5 on Windows. Can you upload ones that work on Windows as well as the Mac? I've got both versions.

Thanks!

**Comment by mrward** [comment] 2015-08-20 14:26
@kiliman - The latest versions on [GitHub](https://github.com/mrward/temp-addin-upload/tree/master/MonoDevelop.PackageManagement/2.8.7) work on Windows. The addin binary was fixed this morning.

**Comment by kiliman** [comment] 2015-08-20 14:41
Hmm.. that's odd. I downloaded both of them and this is the error I'm getting.

File Sizes: 

MonoDevelop.PackageManagement.dll 528,384 bytes
NuGet.Core.dll 581,632 bytes

![image](https://cloud.githubusercontent.com/assets/47168/9386047/b9e97e4c-4727-11e5-8693-df5daa91ef6b.png)

![image](https://cloud.githubusercontent.com/assets/47168/9386074/dbdb5c1e-4727-11e5-83c3-630c3a0a58fa.png)
![image](https://cloud.githubusercontent.com/assets/47168/9386079/e29dc848-4727-11e5-95d3-aee9bddd206b.png)

**Comment by mrward** [comment] 2015-08-20 14:43
You need to unblock the files after you have downloaded them. Right click the file, select Properties and then click Unblock.

**Comment by kiliman** [comment] 2015-08-20 14:57
Perfect! That was the issue. Thanks for your help.

**Closed** 2015-08-29 14:51 UTC

**Comment by b099l3** [comment] 2015-11-03 09:28
If anyone is having this issue on Xamarin Studio, If you update to 5.10 this fixes it.

**Comment by mikefills** [comment] 2016-02-17 21:44
@mrward I followed your instructions from http://forums.xamarin.com/discussion/comment/147377/#Comment_147377 but the problem I have is this:

![ios simulator screen shot jul 15 2014 3 39 20 pm](https://cloud.githubusercontent.com/assets/15019084/13125857/5c8dc086-d5d0-11e5-83ec-73d65fe1e994.png)

**Comment by mrward** [comment] 2016-02-18 09:24
@mikefills - The simplest thing to do would be to upgrade to Xamarin Studio 5.10 and install the latest NuGet extensions addin from the MonoDevelop addin repository.

An alternative would be to build the NuGet extensions addin from source, and drop the [version of its dependencies](https://github.com/mrward/monodevelop-nuget-extensions/blob/master/src/MonoDevelop.PackageManagement.Extensions/MonoDevelop.PackageManagement.Extensions.addin.xml#L24-L28) so it matches what you have. This dependency on a particular version of Xamarin Studio is just to ensure that all the NuGet versions are the same otherwise you can get run into a crash in Xamarin Studio. Once compiled from source you can generate an .mpack by running `mdtool setup pack bin\MonoDevelop.PackageManagement.Extensions.dll`.
