### ISSUE TITLE
Visibility plugin not working/loading in 6.1.*

### ISSUE THREAD

**Issue by kmjonmastro** [MvvmCross/MvvmCross#2962] opened 2018-06-14 00:29 UTC
### Steps to reproduce :scroll:
Only tested on iOS so far. Create a project referencing the Visibility Plugin on iOS and bind the visibility of a UIView element. Build in Release mode to a device. 

### Expected behavior :thinking:
Visibility plugin should be working.

### Actual behavior :bug:
The visibility of the UIElement is not changed. The root cause is that the Visibility plugin does not seem to be loaded.

### Configuration :wrench:
Updating the Setup file with the following fixes the issue.
```
public override IEnumerable<Assembly> GetPluginAssemblies()
{
	var assemblies = base.GetPluginAssemblies().ToList();
	assemblies.Add(typeof(MvvmCross.Plugin.Visibility.Platforms.Ios.Plugin).Assembly);
	assemblies.Add(typeof(MvvmCross.Plugin.Color.Platforms.Ios.Plugin).Assembly);
	assemblies.Add(typeof(MvvmCross.Plugin.Messenger.Plugin).Assembly);
	return assemblies;
}
```

**Version:** 6.1.1

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by ikomobi-apadol** [comment] 2018-06-29 14:53
I have the same behavior in debug on my machine. No need for Release build.
Also experienced it with nuget version 6.0.1.

But your workaround seems to also fix the issue on my side. Thanks !

**Comment by nickrandolph** [comment] 2018-06-30 00:57
Can you confirm this is still an issue in 6.1.2?

**Comment by ikomobi-apadol** [comment] 2018-07-02 08:03
To my experience yes it is. I upgraded my project to 6.1.2 before looking around for issues here. I still had the bug until I implemented the override of GetPluginAssemblies

**Comment by kmjonmastro** [comment] 2018-07-02 20:55
@nickrandolph I confirm this is still happening in 6.1.2

**Comment by Cheesebaron** [comment] 2018-07-24 18:10
I cannot reproduce this. Tried on the TipCalc sample in the MvvmCross-Samples repository. Added the Visibility plugin to iOS and changed linking to Link Framework SDKs Only.

I did have to add LinkerPleaseInclude stuff for `UILabel`, `UITextField` and `UISlider` for stuff to work with linking enabled.

Please provide more reproduction steps.

**Comment by nmilcoff** [comment] 2018-07-24 18:49
@Cheesebaron I could reproduce this issue in Playground.iOS (not forms), by adding a reference to the visibility plugin. Can you please double check that?

**Comment by nickrandolph** [comment] 2018-07-24 21:54
@nmilcoff so the solution is to reference in the LinkerPleaseInclude? If so, can we not just leave it at that?

**Comment by nmilcoff** [comment] 2018-07-24 22:04
Well, I think we would need to do that for each plugin then. Also it is something users would need to do after installing the nuget package, so not ideal at all.

IMO the best would be to make one step back and have some sort of configuration step for all plugins (like the bootstrap files we used in the past).

**Comment by nickrandolph** [comment] 2018-07-24 22:08
Yes, I totally agree with this - tbh I want to outlaw the excessive use of reflection in mvx for self discovery, at least to the point that developers can opt out of it. Using any form of reflection to look for types to register etc is just going to lead to perf issues. Having said that, there is an obvious balance here between the convenience of self-registration v's the performance impact reflection has.
I think we can address this issue in the short term by making it more obvious (perhaps in docs) on how to ensure plugins are loaded.
In long term (prob next major version) we need to address how plugins should work.

**Comment by kmjonmastro** [comment] 2018-07-25 00:16
This is reproducible in the [StarWarsSample](https://github.com/MvvmCross/MvvmCross-Samples/tree/master/StarWarsSample). [PersonView](PersonView) for instance uses visibility but the bindings are not working.

**Comment by nickrandolph** [comment] 2018-08-08 04:30
@nmilcoff are we ok to close this issue off, since this is effectively a limitation of the current implementation. I'd suggest we open a PR with a spike on how we can resolve this going forward?

**Closed** 2018-10-24 21:31 UTC
Labels: Bug, Needs More Info, Plugins
