### ISSUE TITLE
Value Combiner registration

### ISSUE THREAD

**Issue by DavidMarquezF** [MvvmCross/MvvmCross#4371] opened 2022-02-18 08:15 UTC
## 🚀 Feature Requests

There is no clear way to register custom ValueCombiners. I think that this should be added in the Setup class so that we can override it. Either this or improve the documentation by saying that the ValueCombiners are not registered with reflection by default like the ValueConverters and a way to do so.

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [x] :robot: Android
- [x] :checkered_flag: WPF
- [x] :earth_americas: UWP
- [x] :apple: MacOS
- [x] :tv: tvOS
- [x] :monkey: Xamarin.Forms
- [x] :🌍: Blazor

**Comment by Cheesebaron** [comment] 2022-02-18 08:42
Duplicate of #327

**Closed by Cheesebaron** 2022-02-18 08:42 UTC
Labels: s/duplicate

**Comment by DavidMarquezF** [comment] 2022-02-18 08:46
Why is it a duplicate? There is no way to override a register function for value combiners. 

For now there is no clear way on how to register them.

**Comment by Cheesebaron** [comment] 2022-02-18 10:21
You can override `InitializeBindingBuilder` and provide your own binding builder where extra value combiners are added.

**Comment by DavidMarquezF** [comment] 2022-02-18 10:45
Yes, that is what I'm currently doing, but wouldn't it be more convenient if there was an overridable function such as `FillValueCombiners` directly like with value converters?

If this is something that hasn't been added for a reason, I think that adding in the documentation how to do it would help a lot.

**Comment by Cheesebaron** [comment] 2023-05-23 11:38
@snechaev what is the proposal exactly?

**Comment by snechaev** [comment] 2023-05-23 12:27
Proposal is to add the `FillValueCombiners(IMvxValueCombinerRegistry registry)` overload to the platform-specific `Setup` classes (`MvxIosSetup`, `MvxMacSetup`, etc.). This will give the user with exactly the same experience as the for converters (except the naming-convention-based autoregistration, which was considered problematic from a performance point of view). And with such an overload, the developer will be able to easily register the combiners, either manually one-by-one or with assembly-scan or whatever.

**Comment by Cheesebaron** [comment] 2023-05-24 18:39
@snechaev ok, sounds good to me.
