### ISSUE TITLE
Null result when navigating more than two viewmodels

### ISSUE THREAD

**Issue by vvche69** [MvvmCross/MvvmCross#3980] opened 2020-11-01 16:43 UTC
## 🐛 Bug Report

View 1 navigated to View 2 for a result of View 2, but got null when View 2 navigated to View 3 for a result of View 3.

### Expected behavior
View 2 navigates to View 3 to get a result 3 and closes itself to return a result 2 to View 1.
### Configuration

**Version:** 7.1.1

**Platform:** 
- [ ] :iphone: iOS
- [x ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ x] :monkey: Xamarin.Forms

It seems that such behavior is caused by this code in MvxContentPage.cs

    ```
    protected override void OnDisappearing()
        {
            base.OnDisappearing();
            ViewModel?.ViewDisappearing();
            ViewModel?.ViewDisappeared();
            ViewModel?.ViewDestroy();   // <------ 
        }
```

**Comment by Cheesebaron** [comment] 2020-11-01 18:19
Duplicate of #3342

**Closed by Cheesebaron** 2020-11-01 18:19 UTC
