### ISSUE TITLE
Not being able to bind ItemClick in axml or programatically in Droid

### ISSUE THREAD

**Issue by raphaalvarenga** [MvvmCross/MvvmCross#2066] opened 2017-07-25 20:59 UTC
### Steps to reproduce

.Core Code:

```
//Core
public XViewModel()
{
    ShowRelatedObjectCommand = new MvxCommand<string>(ShowRelatedObject);
}
public IMvxCommand ShowRelatedObjectCommand { get; set; }
private void ShowRelatedObject(string customObject)
{
    ShowViewModel<YViewModel>(new Dictionary<string, string>
    {
        { YViewModel.CustomObjectNameKey, JsonConvert.SerializeObject(CustomObject) },
    });
}
```

.Droid axml Code:
```//Droid axml
<MvxListView
      android:id="@+id/firstList"
        android:layout_width="320dp"
        android:layout_height="fill_parent"
        android:cacheColorHint="#00000000"
        android:listSelector="#00000000"
        android:background="#00000000"
        android:fadingEdge="none"
        android:divider="@null"
        android:clickable="true"
         android:focusable="true"
        android:dividerHeight="0dp"
        android:layout_marginTop="20dp"
        android:layout_marginLeft="8dp"
        android:layout_marginRight="8dp"
        android:layout_gravity="center"
        local:MvxBind="ItemsSource Types;ItemClick ShowRelatedObjectCommand "
        local:MvxItemTemplate="@layout/firstlistitem"/>```

### Expected behavior
Bind List item click to my command.

### Actual behavior
The item click in my app don't work.

Am I missing something?
### Configuration

**Version:** 5.1

**Platform:** 
- [ ] iOS
- [x] Android
- [ ] WPF
- [ ] UWP

**Comment by nmilcoff** [comment] 2017-07-26 02:40
Thanks for filling this issue! Unfortunately the provided code doesn't seem to be enough to reproduce your issue. Can you maybe create a minimun reproducible sample in Github? 

To be honest, I don't think ItemClick is broken in MvvmCross, since you're the first and only one reporting this issue. It sounds more as if there is an issue somewhere in your code.

**Comment by Cheesebaron** [comment] 2017-08-01 09:55
Please provide a repro sample. I can't reproduce your issue in a MvvmCross project.

**Comment by Cheesebaron** [comment] 2017-08-07 19:32
Closing this as no more information has been provided. Please add a comment here if you are still having this issue and you can provide more information on how to reproduce it.

**Closed by Cheesebaron** 2017-08-07 19:32 UTC
Labels: Needs More Info
