### ISSUE TITLE
Failed to resolve !!0[] System.Array::Empty()

### ISSUE THREAD

**Issue by joashmusyoka** [MvvmCross/MvvmCross#1374] opened 2016-06-21 08:48 UTC
To help us fix your issue, please provide the information in the below template. 

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.

### Steps to reproduce

1.Upgrade all MvvmCross libs to 4.2.0

2. Re-compile the project

### Expected behavior
It should compile ok

### Actual behavior
Below link exception is thrown.

Severity	Code	Description	Project	File	Line	Suppression State
Error		The "LinkAssemblies" task failed unexpectedly.
Xamarin.Android.XamarinAndroidException: error XA2006: Reference to metadata item '!!0[] System.Array::Empty()' (defined in 'MvvmCross.Binding.Droid, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null') from 'MvvmCross.Binding.Droid, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null' could not be resolved. ---> Mono.Cecil.ResolutionException: Failed to resolve !!0[] System.Array::Empty()
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   --- End of inner exception stack trace ---
   at Xamarin.Android.Diagnostic.Error(Int32 code, Exception innerException, String message, Object[] args)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

### Configuration

**Version:** 4.2.0

**Platform:** Android

**Comment by Noires** [comment] 2016-06-21 11:03
Follow the steps listed in this issue here: #1363

**Comment by joashmusyoka** [comment] 2016-06-21 11:06
Ok, thanks

On Tue, Jun 21, 2016 at 2:04 PM, Noires <notifications@github.com> wrote:

> Follow the steps listed in this issue here: #1363
> <https://github.com/MvvmCross/MvvmCross/issues/1363>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/MvvmCross/MvvmCross/issues/1374#issuecomment-227408029>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AJthgQLCLEmkDqJ9yQGqIHPm9urzVrjyks5qN8UlgaJpZM4I6fhs>
> .
>



-- 
Kind Regards,
Musyoka.

**Comment by Cheesebaron** [comment] 2016-06-21 11:32
Dupe of #1363 

Please search for issues before you post new. Thanks.

**Closed** 2016-06-21 11:32 UTC
