### ISSUE TITLE
WinStore: suspension changes to allow persistent serialisation/deserialisation

### ISSUE THREAD

**Issue by slodge** [MvvmCross/MvvmCross#550] opened 2014-01-13 07:09 UTC
Comment on: https://twitter.com/MikeFayer/statuses/422501923309113344

Gist: https://gist.github.com/tempywritescode/8391807

Also needs looking at in the light of win8.1 which has a different suspension manager setup

**Comment by tal33** [comment] 2015-01-10 15:34
Initial tests with W(P) 8.1 Universal Apps look good.

My code in App.xaml.cs now looks like this:
var setup = new Setup(rootFrame);
setup.Initialize();
var suspensionManager = Mvx.GetSingleton<IMvxSuspensionManager>() as MvxSuspensionManager;
Debug.Assert(suspensionManager != null, "suspensionManager != null");
suspensionManager.RegisterFrame(new MvxWrappedFrame(rootFrame), "AppFrame");

Is there a smarter way to call suspensionManager.RegisterFrame. As far as I can tell MvxWindowsSetup already has the rootFrame as the right kind of object (copied my code from there), but it is private.

I was even wondering why you didn't include RegisterFrame in MvxWindowsSetup.InitializeSuspensionManager?

**Comment by tal33** [comment] 2015-01-11 19:06
Update:
 The solution I described above did only work for one Resume/Restore cycle because there are multiple MvxWrappedFrame objects but the suspension managers need to use exactly the same frame object. I added 
public IMvxWindowsFrame RootFrame { get { return _rootFrame;} }
to MvxWindowsSetup in order to access this frame object and now it seems to work fine (but I don't know why you wanted to keep it private).

Personally I would add a new parameter to MvxWindowsSetup-constructor:
string suspensionManagerSessionStateKey=null) 
and if this isn't null I would call suspensionManager.RegisterFrame in MvxWindowsSetup.InitializeSuspensionManager
This way you have backwards compatibility and the option to initialize it manually but when specifying the stateKey everything is set up nicely automatically.

**Comment by tal33** [comment] 2015-01-11 19:23
I just created a pull request for this (hope it works this way - I'm new to GutHub ;-) also to show what I meant before
https://github.com/MvvmCross/MvvmCross/pull/867

**Comment by bitdisaster** [comment] 2015-01-26 17:11
I was searching around for Suspension/Restore strategy with Mvx but I coudl find much. What is recommend strategy?
I did a demo App with the latest version from Nuget. But the SaveAsync fails with come exception even if I just try to persist a string.

_suspensionManager.SessionState.Add("test", "that");
await _suspensionManager.SaveAsync();

**Comment by tal33** [comment] 2015-01-28 12:38
The current Version of MvvmCross is broken in regard to SuspensionManager - it simply doesn't work for Universal Apps (and Windows Store apps - though I haven't tried it yet) which really is a shame since in my opinion MvvmCross in its current state is therefore unuseable for modern Windows app development unless you work around this bug :-(

I have a pending pull request (https://github.com/MvvmCross/MvvmCross/pull/867, see above) with the fixes suggested at the beginning of this thread. With these fixes it simply works according to my tests :-) 

The recommend way of using SuspensionManager in MvvmCross (at least as I understood it ;-) can be found in the "Demo App for 550" I linked above: basically you add SaveState and ReloadState (or the corresponding override SaveStateToBundle) to your viewmodel and you are done. But again: this only works if you build MvvmCross using the suggested pull request (my sample contains a build of MvvmCross with these changes but nugget is eager to replace it with the current official beta).

**Comment by bitdisaster** [comment] 2015-02-04 23:42
@tal33 thanks for your explanation. I could use your code to workaround the broken SuspensionManger. But it would be awesome if your PR would be accepted. @slodge any chance we can get this soon into the official nuget package?

**Comment by jonstoneman** [comment] 2015-02-05 00:05
FWIW, I can confirm that SuspensionManager doesn't work with Mvx and that the pull request it looks good to me.  I only saw it last night and was planning on testing it before commenting (might get chance tomorrow night, otherwise not for a while sorry) but it should be fine just to pull it in IMO.

**Comment by bitdisaster** [comment] 2015-02-05 00:46
We use MvvmCross via nuget and had no problems so far. We would like to keep using nuget and not compile ourself. I worked assertions the problem for now. But if the nuget package could get fixed, that would be perfect.

**Comment by jonstoneman** [comment] 2015-02-05 21:40
I've tested this in both WindowsStore and WindowsCommon and it's working well.

@slodge i didn't get what you were saying about back button awkwardness above - can you explain what's the issue is please?

**Comment by slodge** [comment] 2015-02-05 21:51
Can't remember the full details (I'm old... or maybe I just drink too much when I know Wales are playing England in Cardiff again...)

It was to do with https://github.com/MvvmCross/MvvmCross/pull/835

As I recall, the explanation on http://caliburnmicro.com/announcements/application-state-part-3/ was quite good - basically it said that if you set the Navigation Cache disabled, then back didn't really work... but if you did Navigation Cache enabled, then the forwards direction (after a back) would sometimes be wrong too... so that was why people wanted to use some other RootFrame (e.g. MyToolkit)...

I think that was it... @dbeattie71 and @promontis might have better opinions...

--------

So... I'm guessing that the suggestion is we should pull and merge this soon :)

**Thanks for the expertise all**

**Comment by jonstoneman** [comment] 2015-02-06 10:37
Yeah, I'd say pull it in.  Even if things do need to change following the rootFrame work then that would be the case with or without this fix.

Commiserations in advance for tonight's game...  ;)

**Comment by promontis** [comment] 2015-02-06 12:42
I'd like to give my view on this as well... currently, there are two known problems:
1) navigation stack has changed. See the blog post @ caliburn micro. We already have done some work on this in a different branch and some parts are already merged in master. I do have some local changes pending, but I want to test it a little bit more, before pushing it 
2) suspension seems to be broken. Not sure which PR's are in scope, but I took a look at #867 and that seems fine. 

All in all, I think the two problems are unrelated and can be looked at separately. So, I'd say, pull it :)

**Comment by martijn00** [comment] 2015-08-09 20:49
This has been merged in.

**Closed by martijn00** 2015-08-09 20:49 UTC
Labels: Code improvement, New code to integrate
