### ISSUE TITLE
NavigationService stuck

### ISSUE THREAD

**Issue by Emaxinvader** [MvvmCross/MvvmCross#2904] opened 2018-05-23 14:46 UTC
### Steps to reproduce :scroll:

1. ViewModelA calls NavigationService.Navigate\<ViewModelB>\()

2. ViewModelB calls NavigationService.Close(this)

### Expected behavior :thinking:
The application shows ViewA

### Actual behavior :bug:
Not always, application remains stuck to ViewB with log:

05-23 16:20:14.980 I/mono-stdout(23809): 2018-05-23 04:20:14 [TRACE] (MvvmCross.Logging.MvxLog) PresentationAttribute not found for ViewB. Assuming Activity presentation2018-05-23 04:20:14 [TRACE] (MvvmCross.Logging.MvxLog) PresentationAttribute not found for AccountView. Assuming Activity presentation

05-23 16:20:14.981 I/mono-stdout(23809): 2018-05-23 04:20:14 [WARN]  (MvvmCross.Logging.MvxLog) Ignoring close for viewmodel - rootframe has no current page2018-05-23 04:20:14 [WARN]  (MvvmCross.Logging.MvxLog) Ignoring close for viewmodel - rootframe has no current page

If I put the application in the background and then put it back in the foreground, it crashes or go back to ViewModelA like expected...

### Configuration :wrench:

core: .NET standard 2.0
app : Xamarin.Android_8.2.0

**mvvmcross Version:** 6.01

**Platform:** 
- [ ] :iphone: iOS
- [ x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Strifex** [comment] 2018-05-31 23:02
I am also experiencing this issue.  This is probably due to this code in the AndroidViewPresentor:

        protected virtual bool CloseActivity(IMvxViewModel viewModel, MvxActivityPresentationAttribute attribute)
        {
            var currentView = CurrentActivity as IMvxView;

            if (currentView == null)
            {
                MvxLog.Instance.Warn("Ignoring close for viewmodel - rootframe has no current page");
                return false;
            }

            if (currentView.ViewModel != viewModel)
            {
                MvxLog.Instance.Warn("Ignoring close for viewmodel - rootframe's current page is not the view for the requested viewmodel");
                return false;
            }

            CurrentActivity.Finish();

            return true;
        }

It appears that the default AndroidViewPresentor doesn't currently support closing activities unless that activity is currently "active".  Essentially, unless something changes we can't close Activities in the backstack from their ViewModel via the navigation service.  Perhaps either @kjeremy or @martijn00 know of a workaround?

**Comment by nickrandolph** [comment] 2018-05-31 23:08
Is this issue reproducible in the playground droid sample? If not would someone be able to modify the sample so that it is, and submit as a PR so we can take a look.

**Comment by Strifex** [comment] 2018-06-01 03:42
After further investigation, it appears my issue is slightly different. It occurs only when I try to _navigationService.Close(this) while a custom tab is currently being presented (such as during a login flow, I try to navigate to a new viewmodel and close the current viewmodel).  Therefore, it appears the original issue here is different, sorry for the confusion.  I tried to reproduce the original issue as well in the playground and couldn't, but @Emaxinvader should try and reproduce themself probably...

**Comment by Thetyne** [comment] 2018-06-01 13:39
I have the same problem. Show ViewModelA then ViewModelB then ViewModelB close push new ViewModelA.

after, unable to close ViewModelA....
Ignoring close for viewmodel - rootframe has no current page

**Comment by Thetyne** [comment] 2018-06-08 15:22
Today, I have reproduce the problem in a new project.

I navigate two time on same view model and when i close the second (with _navigationService.Close(...)), i have a log message "close for viewmodel - rootframe has no current page" and view model doesn't close.

I try reproduce it in Playground droid sample.

**Comment by Thetyne** [comment] 2018-06-08 16:20
I check at the moment at MvxApplicationCallbacksCurrentTopActivity.cs:
_Activities ConcurrentDictionary add entry by "name of activity" key.

I push the same activity two time, so it fail enter the new key inside  ConcurrentDictionary.

I wiil test a fix

**Comment by nickrandolph** [comment] 2018-08-09 05:03
@Emaxinvader can you retest this on v6.2

**Closed** 2019-07-04 06:55 UTC
Labels: p/android, s/needs-more-info, t/bug
