### ISSUE TITLE
Upgrade Analyzers VSIX project to VS2017

### ISSUE THREAD

**Issue by Cheesebaron** [MvvmCross/MvvmCross#1654] opened 2017-03-25 17:33 UTC
@azchohfi could you please look into this?

When loading the MvvmCross_All solution in VS2017, you get prompted to upgrade the VSIX project for the analyzers. Can you please look into checking that his goes OK?

**Comment by martijn00** [comment] 2017-04-28 12:21
@azchohfi any progress on this one?

**Comment by hmaheshnayak** [comment] 2017-07-15 08:07
@martijn00 I am a 'first-timer' who would like to contribute to this issue.

It seems to be caused by dependencies of certain projects on project subtypes. Removing the project type from within the <ProjectTypeGuids> tag within the affected .csproj files prevents the error on launch of MvvmCross_All solution in VS2017. For example, the project MvvmCross.Droid.Support.Compat has {EFBA0AD7-5A72-4C68-AF49-83D382785DCF} within its <ProjectTypeGuids>, removing which causes no error due to that particular project in my installation of VS.  

Is this an acceptable solution? Please advise.

**Comment by martijn00** [comment] 2017-07-27 11:35
Fixed in https://github.com/MvvmCross/MvvmCross/pull/2047

**Closed** 2017-07-27 11:35 UTC
Labels: first-timers-only, Future cleanup, up-for-grabs
