### ISSUE TITLE
MvvmCross Android: Linking kills SwitchCompat.Checked propety

### ISSUE THREAD

**Issue by Goncharuk-Nikita** [MvvmCross/MvvmCross#3169] opened 2018-10-17 07:53 UTC
## 🐛 Bug Report

I have layout with SwitchCompat binding to ViewModel

```
<android.support.v7.widget.SwitchCompat 
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_weight="1"
            app:MvxBind="Checked FlashlightEnabled;
                         Click FlashlightCheckedCommand"/>
```

I also add in LinkerPleaseInclude.cs file some Include methods

```
public void Include(Switch s)
        {
            s.CheckedChange += (sender, args)
                => s.Checked = !s.Checked;
            s.Checked = true;
        }

        public void Include(SwitchCompat sc)
        {
            sc.CheckedChange += (sender, args)
                => sc.Checked = !sc.Checked;
            sc.Checked = true;
        }
```

But when I set the **Sdk Assemblies** or  **Sdk and User Assemblies**  linking, my Checked binding is removed.

**Output Message:**

2018-10-16 12:31:17 [WARN] (MvxBind) Failed to create target binding for binding Checked for FlashlightEnabled10-16 12:31:17.143 I/mono-stdout( 5716): at System.Activator.CreateInstance (System.Type type, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[]

![devenv_2018-10-16_12-50-52](https://user-images.githubusercontent.com/30652592/47070883-e3485e00-d1fa-11e8-874a-b5468c7c012b.png)

StackOverflow: https://stackoverflow.com/questions/52832149/mvvmcross-android-linking-kills-switchcompat-checked-propety?noredirect=1#comment92581663_52832149

### Expected behavior
Checked property bind to ViewModel property

### Reproduction steps
1. Create MvvmCross Native android app
2. In your ViewModel create bool propety
3. In layout paste SwitchCompat component
4. Use MvxBind to bind Checked property to ViewModel property
5. Add linking Include method with SwitchCompat 
6. Run it with linking Sdk Assemblies or Sdk and User Assemblies

### Configuration

**Version:** 6.2.1

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment] 2018-10-17 17:18
I cannot reproduce this.

I created a fresh MvvmCross application added a `android.support.v7.widget.SwitchCompat` element to a layout with binding `app:MvxBind="Checked Herp"` where `Herp` defaults to true. Didn't have to add anything to LinkerPleaseInclude (used default one from MvxScaffolding), which has the base class which `SwitchCompat` derives from. No issues.

Can you provide a small repro sample where this is possible to reproduce?

**Comment by Goncharuk-Nikita** [comment] 2018-10-18 07:44
@Cheesebaron 
When I run your example, the switch is turned off. I add label binding to check `Herp` State

Try to run my test version and click on the switch. if the text of the label will change, then I can't even guess what my problem is.


[MyMvvmCrossApp1.zip](https://github.com/MvvmCross/MvvmCross/files/2490718/MyMvvmCrossApp1.zip)

**Comment by Cheesebaron** [comment] 2018-10-18 11:17
Can you provide the  full stack trace from the warning?

**Comment by Cheesebaron** [comment] 2018-10-25 11:49
Closing this as cannot reproduce this.

If you can provide a project where it is possible to reproduce, please open a new issue referring to this one.

**Closed by Cheesebaron** 2018-10-25 11:49 UTC
Labels: Invalid
