### ISSUE TITLE
Viewmodels not released when navigating to another viewmodel after MvvmCross 5.0.3 and any newer

### ISSUE THREAD

**Issue by ryssel** [MvvmCross/MvvmCross#2326] opened 2017-10-31 09:36 UTC
### Steps to reproduce

1. Use attached example

2. Put a breakpoint in the tree viewmodels constructors and finalizers

3. Navigate form FirstViewModel to SecondViewModel and ThirdViewModel and all the way back.

4. Note when the finalizers and constructors are called

### Expected behavior
Using MvvmCross 5.0.2 and versions before that, each viewmodel is released and finalized when you navigate away from it and reconstructed when navigation back to them.

### Actual behavior
In MvvmCross 5.0.3 and any newer release all three viewmodels is kept alive while navigating forward to ThirdViewModel.
When navigating back it works as expected, the viewmodels are released in the order they are navigated away from.

### Configuration

**Version:** 5.0.3

**Platform:** 
- [ ] iOS
- [ ] Android
- [ ] WPF
- [X] UWP
- [ ] MacOS
- [ ] tvOS
- [ ] Xamarin.Forms

[ViewModelLifetimes.zip](https://github.com/MvvmCross/MvvmCross/files/1430145/ViewModelLifetimes.zip)

**Comment by ryssel** [comment] 2017-10-31 09:37
The bug might have something to do with this issue https://github.com/MvvmCross/MvvmCross/issues/1940

**Comment by martijn00** [comment] 2017-10-31 09:44
I would say this depends on if you Navigate with a return type. It will hold a reference in a `ConditionalWeakTable` and use that to set the value. With this it will be release from memory when it is not used anymore. Do you think there is something preventing it to get removed from memory?

**Comment by ryssel** [comment] 2017-10-31 09:47
There is no returntype it is just:
ShowViewModel<SecondViewModel>();
And it works like expected in 5.0.2

**Comment by martijn00** [comment] 2017-10-31 09:56
And with the NavigationService? This is only on UWP?

**Comment by ryssel** [comment] 2017-10-31 10:26
I just tried with MvvmCross 5.3.2 and replacing ShowViewModel with:
_navigationService.Navigate<SecondViewModel>();
_navigationService.Navigate<ThirdViewModel>();
It behaves exactly the same way, releases viewmodels with 5.0.2 but not with 5.3.2

I have only tried this example with UWP, but I have another app build for IOS and Android where the IOS app does not release the viewmodels, but the Android app did. It's a long time since I was able to build the Android app, so if we could solve the UWP problem first, I would be happy to extend the example to IOS and Android afterwards. Right now I'm stuck at 5.0.2.

**Comment by nmilcoff** [comment] 2017-10-31 12:29
Can you please upload the sample to GitHub?

**Comment by ryssel** [comment] 2017-10-31 12:33
It is already uploaded in the first post in this issue. Ok?

**Comment by nmilcoff** [comment] 2017-10-31 22:22
I don't think there is an issue here. If you navigate forward, each platform has a back stack / caching mechanism that keeps Views alive in case the user navigates back.

ViewModels are being released when the View is popped / when you navigate back. So this is fine.

**Comment by dahovey** [comment] 2018-02-01 17:16
Was this changed between version 4.x and 5.x of MvvmCross for UWP?
In version 4.x I could rely on Init being called even when moving thru BackStack. Now in version 5.x I am overriding Initialize() and it is only called when ViewModel is first created not when moving thru BackStack.

If I need to re-initialize a view when moving thru BackStack do I now need to use ViewAppearing/ViewAppeared overrides?

**Comment by bastarr** [comment] 2018-04-25 17:47
This is still an issue with anything above 5.0.2.  Simple repro case is to create simple UWP or iOS application with two views and two view models using any version above 5.0.2.  Simply call ShowViewModel between these two views to toggle back and forth and do a memory snapshot after a view clicks.  You will see the ViewModel count for each type just climb and never recover.  Do the same exercise with version 5.0.2 or below and you will notice there is only 1 ViewModel of each type on the stack at any one time.   This make MVVMCross totally unusable for me with versions above 5.0.2.  I am tempted to downgrade back to 5.0.2.

**Comment by nmilcoff** [comment] 2018-04-27 15:29
@bastarr can you confirm the issue is not present in v5.0.2 but it is in v5.0.3?

**Comment by dahovey** [comment] 2018-04-27 15:51
I believe this is related to issue I submitted [https://github.com/MvvmCross/MvvmCross/issues/2578](https://github.com/MvvmCross/MvvmCross/issues/2578).

**Comment by bastarr** [comment] 2018-05-01 18:35
Yes, the issue is present in 5.0.3 (and above all the way to 6.0) but not in 5.0.2.  As mentioned, I simply created a small two view application with nothing but a textbox on each view and a button bound to a command to ShowViewModel (NavigationService.Navigate also) to the other view.  If I run this on 5.0.2, I see only one of each view model in the memory snapshot no matter how many times I bounce back and forth.  If I just upgrade to 5.0.3 and nothing else, I start seeing multiple copies of each view models in the memory snapshot.

**Comment by nickrandolph** [comment] 2018-08-10 01:28
This is either a duplicate of #2578 or working by-design. If this is not the case, please leave a comment and we can reopen

**Closed by nickrandolph** 2018-08-10 01:28 UTC
Labels: Needs investigation, UWP, iOS
