### ISSUE TITLE
nuget 8.02 version MvvmCross.Platforms.Wpf have a bug on MvxWpfViewPresenter class

### ISSUE THREAD

**Issue by levi930** [MvvmCross/MvvmCross#4321] opened 2021-11-11 03:41 UTC
### Configuration

**Version:** 8.02

**Platform:** 
- [ ] :checkered_flag: WPF

nuget 8.02 version release
MvvmCross.Platforms.Wpf

this class MvxWpfViewPresenter

![image](https://user-images.githubusercontent.com/31331264/141232898-2015b2a7-2a95-44c6-aada-39a8197dfeba.png)

this version not set default value ;

,muse set the value 

 new MvxContentPresentationAttribute { ViewType = viewType, ViewModelType = viewModelType };

![image](https://user-images.githubusercontent.com/31331264/141233026-7a2a7a73-81ee-4829-a335-bc27e0339fa0.png)

**Comment by Cheesebaron** [comment] 2021-11-11 19:44
Fixed in #4291

Duplicate of #4221

**Closed by Cheesebaron** 2021-11-11 19:44 UTC
